# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.utils_files
import django.core.serializers.json
import sapl.audiencia.models
import sapl.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnexoAudienciaPublica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.utils.texto_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                ("data", models.DateField(auto_now=True)),
                ("assunto", models.TextField(verbose_name="Assunto")),
            ],
            options={
                "verbose_name": "Anexo de Documento Acessório",
                "verbose_name_plural": "Anexo de Documentos Acessórios",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AudienciaPublica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(blank=True, verbose_name="Número"),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Audiência Pública"
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        max_length=100, verbose_name="Tema da Audiência Pública"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "hora_inicio",
                    models.CharField(
                        max_length=5, verbose_name="Horário Início(hh:mm)"
                    ),
                ),
                (
                    "hora_fim",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Horário Fim(hh:mm)"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observação"
                    ),
                ),
                (
                    "audiencia_cancelada",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Audiência Cancelada?",
                    ),
                ),
                (
                    "url_audio",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Áudio (Formatos MP3 / AAC)",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)",
                    ),
                ),
                (
                    "upload_pauta",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.audiencia.models.pauta_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Pauta da Audiência Pública",
                    ),
                ),
                (
                    "upload_ata",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.audiencia.models.ata_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Ata da Audiência Pública",
                    ),
                ),
                (
                    "upload_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.audiencia.models.anexo_upload_path,
                        verbose_name="Anexo da Audiência Pública",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audiência Pública",
                "verbose_name_plural": "Audiências Públicas",
                "ordering": ["nome", "numero", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="TipoAudienciaPublica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="Audiência Pública",
                        max_length=50,
                        verbose_name="Nome do Tipo de Audiência Pública",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("A", "Audiência Pública"),
                            ("P", "Plebiscito"),
                            ("R", "Referendo"),
                            ("I", "Iniciativa Popular"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Tipo de Audiência Pública",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Audiência Pública",
                "verbose_name_plural": "Tipos de Audiência Pública",
                "ordering": ["nome"],
            },
        ),
    ]
