# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audiencia", "0001_initial"),
        ("materia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audienciapublica",
            name="materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="materia.materialegislativa",
                verbose_name="Matéria Legislativa",
            ),
        ),
        migrations.AddField(
            model_name="anexoaudienciapublica",
            name="audiencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="audiencia.audienciapublica",
            ),
        ),
        migrations.AddField(
            model_name="audienciapublica",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="audiencia.tipoaudienciapublica",
                verbose_name="Tipo de Audiência Pública",
            ),
        ),
    ]
