# Generated by Django 5.2.14 on 2026-05-29 10:34

import cmj.utils_files
import sapl.audiencia.models
import sapl.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audiencia", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexoaudienciapublica",
            name="arquivo",
            field=sapl.utils.PortalFileField(
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.utils.texto_upload_path,
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="audienciapublica",
            name="upload_anexo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.audiencia.models.anexo_upload_path,
                verbose_name="Anexo da Audiência Pública",
            ),
        ),
        migrations.AlterField(
            model_name="audienciapublica",
            name="upload_ata",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.audiencia.models.ata_upload_path,
                validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                verbose_name="Ata da Audiência Pública",
            ),
        ),
        migrations.AlterField(
            model_name="audienciapublica",
            name="upload_pauta",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.audiencia.models.pauta_upload_path,
                validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                verbose_name="Pauta da Audiência Pública",
            ),
        ),
    ]
