# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0012_auto_20200505_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexoaudienciapublica',
            options={'ordering': ['id'], 'verbose_name': 'Anexo de Documento Acessório', 'verbose_name_plural': 'Anexo de Documentos Acessórios'},
        ),
    ]
