# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
from django.db import migrations, models

import cmj.diarios.models
import cmj.mixins
import cmj.utils_files
import sapl.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiarioOficial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "edicao",
                    models.PositiveIntegerField(default=0, verbose_name="Edição"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="Descrição"),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=cmj.diarios.models.diario_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Arquivo Digital do Diário",
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Data"),
                ),
            ],
            options={
                "verbose_name": "Diário Oficial",
                "verbose_name_plural": "Diários Oficiais",
                "ordering": ("-data", "edicao"),
            },
        ),
        migrations.CreateModel(
            name="TipoDeDiario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Diário",
                "verbose_name_plural": "Tipos de Diário",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VinculoDocDiarioOficial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pagina",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Página Inicial"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "verbose_name": "Documento Publicado no Diário Oficial",
                "verbose_name_plural": "Documentos Publicados no Diário Oficial",
                "ordering": ("id",),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
    ]
