# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("diarios", "0001_initial"),
        ("norma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diariooficial",
            name="normas",
            field=models.ManyToManyField(
                to="norma.normajuridica", verbose_name="Normas Publicadas no Diário"
            ),
        ),
        migrations.AddField(
            model_name="diariooficial",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="diarios.tipodediario",
                verbose_name="Tipo do Diário",
            ),
        ),
        migrations.AddField(
            model_name="vinculodocdiariooficial",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
                verbose_name="Espécie",
            ),
        ),
        migrations.AddField(
            model_name="vinculodocdiariooficial",
            name="diario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="diarios.diariooficial",
                verbose_name="Diário Oficial",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vinculodocdiariooficial",
            unique_together={("object_id", "content_type", "diario")},
        ),
    ]
