# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0002_auto_20190618_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariooficial',
            name='normas',
            field=models.ManyToManyField(to='norma.NormaJuridica', verbose_name='Normas Publicadas no Diário'),
        ),
    ]
