# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 13:54
from __future__ import unicode_literals

import cmj.diarios.models
from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0004_diariooficial_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariooficial',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=cmj.diarios.models.diario_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Arquivo Digital do Diário'),
        ),
    ]
