# Generated by Django 2.2.16 on 2020-10-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diarios', '0009_tipodediario_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoDocDiarioOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diarios.DiarioOficial', verbose_name='Diário Oficial')),
            ],
            options={
                'verbose_name': 'Documento Publicado no Diário Oficial',
                'verbose_name_plural': 'Documentos Publicados no Diário Oficial',
                'ordering': ('id',),
            },
        ),
    ]
