# Generated by Django 2.2.16 on 2020-10-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0011_auto_20201015_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculodocdiariooficial',
            name='pagina',
            field=models.PositiveIntegerField(default=0, verbose_name='Página Inicial'),
        ),
    ]
