# Generated by Django 2.2.16 on 2020-10-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diarios', '0012_auto_20201015_1846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vinculodocdiariooficial',
            unique_together={('object_id', 'content_type', 'diario')},
        ),
    ]
