# Generated by Django 2.2.28 on 2024-07-18 20:27

import cmj.diarios.models
from django.db import migrations
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0014_auto_20240325_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariooficial',
            name='arquivo',
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=cmj.diarios.models.diario_upload_path,
                validators=[sapl.utils.restringe_tipos_de_arquivo_txt],
                verbose_name='Arquivo Digital do Diário'),
        ),
    ]
