# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models
from pgvector.django import VectorExtension

import cmj.core.models
import cmj.mixins
import sapl.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        UnaccentExtension(),
        VectorExtension(),
        TrigramExtension(),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibilidade",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (2, "Restrição por Permissão"),
                            (1, "Restrição por Usuário"),
                            (99, "Privado"),
                            (0, "Público"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="email"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("U", "Atualizado"),
                            ("C", "Criado"),
                            ("D", "Excluído"),
                            ("P", "Pesquisa"),
                        ],
                        db_index=True,
                        max_length=1,
                        verbose_name="operation",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                (
                    "obj",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Object",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "obj_id",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="object_id"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="model"
                    ),
                ),
                (
                    "app_name",
                    models.CharField(db_index=True, max_length=100, verbose_name="app"),
                ),
            ],
            options={
                "verbose_name": "AuditLog",
                "verbose_name_plural": "AuditLogs",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=254, unique=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "codigo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Código do Bairro no Cadastro Oficial do Município",
                        verbose_name="Código",
                    ),
                ),
                (
                    "outros_nomes",
                    models.TextField(
                        blank=True,
                        help_text="Ocorrências similares",
                        verbose_name="Outros Nomes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bairro",
                "verbose_name_plural": "Bairros",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Bi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ano"),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Json results",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
            ],
            options={
                "verbose_name": "Bi",
                "verbose_name_plural": "Bi",
                "ordering": ("-id", "-ano", "content_type"),
            },
        ),
        migrations.CreateModel(
            name="Cep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=9, unique=True, verbose_name="CEP"),
                ),
            ],
            options={
                "verbose_name": "CEP",
                "verbose_name_plural": "CEP's",
                "ordering": ("numero",),
            },
        ),
        migrations.CreateModel(
            name="CertidaoPublicacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "hash_code",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Hash de Publicação"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Field Name"
                    ),
                ),
                (
                    "cancelado",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Cancelado ",
                    ),
                ),
                (
                    "revogado",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Certidão Revogada",
                    ),
                ),
                (
                    "certificado",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=cmj.core.models.certidao_create_path,
                        verbose_name="Certificado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certidão de Publicação",
                "verbose_name_plural": "Certidões de Publicação",
                "ordering": ("-id",),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=254, unique=True, verbose_name="Nome do Distrito"
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrito",
                "verbose_name_plural": "Distritos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="IAQuota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_diaria",
                    models.PositiveIntegerField(default=0, verbose_name="Quota Diária"),
                ),
                (
                    "modelo",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Modelo"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Número de requisições processadas por vez.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Tamanho do Lote",
                    ),
                ),
                (
                    "get_threads",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número de threads para processamento paralelo.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Número de Batch Create ao mesmo tempo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota IA",
                "verbose_name_plural": "Quotas IA",
                "ordering": ("-modelo",),
            },
        ),
        migrations.CreateModel(
            name="IAQuotasLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Data do Log de Quota IA",
                        verbose_name="Data",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                ("peso", models.PositiveIntegerField(default=1, verbose_name="Peso")),
            ],
            options={
                "verbose_name": "Log de Quota IA",
                "verbose_name_plural": "Logs de Quota IA",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ImpressoEnderecamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=254, verbose_name="Nome do Impresso"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ET", "Folha de Etiquetas"), ("EV", "Envelopes")],
                        default="ET",
                        max_length=2,
                        verbose_name="Tipo do Impresso",
                    ),
                ),
                (
                    "largura_pagina",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Largura da Página",
                    ),
                ),
                (
                    "altura_pagina",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Altura da Página",
                    ),
                ),
                (
                    "margem_esquerda",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Margem Esquerda",
                    ),
                ),
                (
                    "margem_superior",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Margem Superior",
                    ),
                ),
                (
                    "colunasfolha",
                    models.PositiveSmallIntegerField(verbose_name="Colunas"),
                ),
                (
                    "linhasfolha",
                    models.PositiveSmallIntegerField(verbose_name="Linhas"),
                ),
                (
                    "larguraetiqueta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Largura da Etiqueta",
                    ),
                ),
                (
                    "alturaetiqueta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Altura da Etiquta",
                    ),
                ),
                (
                    "entre_colunas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Distância Entre Colunas",
                    ),
                ),
                (
                    "entre_linhas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em centímetros",
                        max_digits=5,
                        verbose_name="Distância Entre Linhas",
                    ),
                ),
                (
                    "fontsize",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Em Pixels",
                        max_digits=5,
                        verbose_name="Tamanho da Letra",
                    ),
                ),
                (
                    "rotate",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Rotacionar Texto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impresso para Endereçamento",
                "verbose_name_plural": "Impressos para Endereçamento",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Logradouro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=254, unique=True, verbose_name="Logradouro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logradouro",
                "verbose_name_plural": "Logradouros",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=50)),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PR", "Paraná"),
                            ("PB", "Paraíba"),
                            ("PA", "Pará"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SE", "Sergipe"),
                            ("SP", "São Paulo"),
                            ("TO", "Tocantins"),
                            ("EX", "Exterior"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "regiao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CO", "Centro-Oeste"),
                            ("NE", "Nordeste"),
                            ("NO", "Norte"),
                            ("SE", "Sudeste"),
                            ("SL", "Sul"),
                            ("EX", "Exterior"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "read",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Lida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["id"],
                "permissions": (
                    (
                        "popup_notificacao",
                        "Visualização das notificações em Popup no Avatar do Usuário",
                    ),
                ),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OcrMyPDF",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "field",
                    models.CharField(default="", max_length=254, verbose_name="Field"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "concluido",
                    models.DateTimeField(auto_now=True, verbose_name="created"),
                ),
                (
                    "sucesso",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Sucesso",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OperadorAreaTrabalho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
            ],
            options={
                "verbose_name": "Operador",
                "verbose_name_plural": "Operadores",
                "ordering": ["id"],
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RegiaoMunicipal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=254, verbose_name="Região Municipal"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AU", "Área Urbana"),
                            ("AR", "Área Rural"),
                            ("UA", "Área Única"),
                        ],
                        default="AU",
                        max_length=2,
                        verbose_name="Tipo da Região",
                    ),
                ),
            ],
            options={
                "verbose_name": "Região Municipal",
                "verbose_name_plural": "Regiões Municipais",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoLogradouro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=254, unique=True, verbose_name="Tipo de Logradouro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Logradouro",
                "verbose_name_plural": "Tipos de Logradouros",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Trecho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("search", models.TextField(blank=True, default="")),
                (
                    "lado",
                    models.CharField(
                        choices=[
                            ("NA", "Não Aplicável"),
                            ("AL", "Ambos os Lados"),
                            ("LE", "Lado Esquerdo"),
                            ("LD", "Lado Direito"),
                        ],
                        default="AL",
                        max_length=2,
                        verbose_name="Lado do Logradouro",
                    ),
                ),
                (
                    "numero_inicial",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número Inicial"
                    ),
                ),
                (
                    "numero_final",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número Final"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trecho de Logradouro",
                "verbose_name_plural": "Trechos de Logradouro",
                "ordering": [
                    "municipio__nome",
                    "regiao_municipal__nome",
                    "distrito__nome",
                    "bairro__nome",
                    "tipo__nome",
                    "logradouro__nome",
                ],
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar",
                    image_cropping.fields.ImageCropField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        validators=[cmj.core.models.avatar_validation],
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "cropping",
                    image_cropping.fields.ImageRatioField(
                        "avatar",
                        "128x128",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text="A configuração do Avatar é possível após a atualização da fotografia.",
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Seleção (Enquadramento)",
                    ),
                ),
                (
                    "pwd_created",
                    models.BooleanField(
                        default=False,
                        verbose_name="Usuário de Rede Social Customizou Senha?",
                    ),
                ),
                (
                    "be_notified_by_email",
                    models.BooleanField(
                        default=True, verbose_name="Receber Notificações por email?"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ("-is_superuser", "first_name", "last_name"),
                "permissions": (
                    ("menu_dados_auxiliares", "Mostrar Menu Dados Auxiliares"),
                    ("menu_tabelas_auxiliares", "Mostrar Menu de Tabelas Auxiliares"),
                    ("menu_recepcao", "Mostrar Menu de Registro de Entradas"),
                    ("menu_contatos", "Mostrar Menu de Cadastro de Contatos"),
                    (
                        "menu_grupocontatos",
                        "Mostrar Menu de Cadastro de Grupos de Contatos",
                    ),
                    ("menu_processos", "Mostrar Menu de Cadastro de Processos"),
                    ("menu_area_trabalho", "Mostrar Menu de Áreas de Trabalho"),
                    (
                        "menu_impresso_enderecamento",
                        "Mostrar Menu de Impressos de Endereçamento",
                    ),
                    ("menu_relatorios", "Mostrar Menu de Relatórios"),
                    ("menu_administracao", "Mostrar Menu de Administração"),
                    ("menu_agenda", "Mostrar Menu da Agenda de Eventos"),
                    ("generate_analise_genia", "Gerar Análise I.A."),
                ),
                "abstract": False,
            },
            managers=[
                ("objects", cmj.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AreaTrabalho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Nome"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        default="", max_length=254, verbose_name="Descrição"
                    ),
                ),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[
                            (10, "Gabinete Parlamentar"),
                            (20, "Setor Administrativo"),
                            (30, "Institucional"),
                            (40, "Recepção"),
                            (90, "Procuradoria Jurídica"),
                            (99, "Documentos Públicos"),
                        ],
                        default=10,
                        verbose_name="Tipo da Área de Trabalho",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Área de trabalho Ativa",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Trabalho",
                "verbose_name_plural": "Áreas de Trabalho",
                "ordering": ("-ativo", "-tipo", "parlamentar"),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
    ]
