# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0021_merge'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(default='', max_length=254, verbose_name='Descrição')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
            ],
            options={
                'verbose_name_plural': 'Áreas de Trabalho',
                'verbose_name': 'Área de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='OperadorAreaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('areatrabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadorareatrabalho_set', to='core.AreaTrabalho', verbose_name='Área de Trabalho')),
                ('grupos_associados', models.ManyToManyField(related_name='operadorareatrabalho_set', to='auth.Group', verbose_name='Grupos Associados')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadorareatrabalho_set', to=settings.AUTH_USER_MODEL, verbose_name='Operador da Área de Trabalho')),
            ],
            options={
                'verbose_name_plural': 'Operadores',
                'verbose_name': 'Operador',
            },
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='areatrabalho_set', through='core.OperadorAreaTrabalho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areatrabalho_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
