# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_menu_dados_auxiliares', 'Pode ver Dados Auxiliares'),)},
        ),
    ]
