# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160619_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('menu_dados_auxiliares', 'Mostrar Menu Dados Auxiliares'), ('menu_pessoas', 'Mostrar Menu de Cadastro de Pessoas'))},
        ),
    ]
