# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160622_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='numero',
            field=models.CharField(max_length=9, unique=True, verbose_name='CEP'),
        ),
    ]
