# Generated by Django 5.2.16 on 2026-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iaquota",
            name="ativo",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Ativo",
            ),
        ),
    ]
