# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170815_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd_created',
            field=models.BooleanField(default=False, verbose_name='Usuário de Rede Social Customizou Senha?'),
        ),
    ]
