# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160623_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trecho',
            options={'ordering': ['municipio__nome', 'regiao_municipal__nome', 'distrito__nome', 'bairro__nome', 'logradouro__nome'], 'permissions': 'search_trecho', 'verbose_name': 'Trecho de Logradouro', 'verbose_name_plural': 'Trechos de Logradouro'},
        ),
    ]
