# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 19:30
from __future__ import unicode_literals

import cmj.core.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_pwd_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='avatars/', validators=[cmj.core.models.avatar_validation], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '128x128', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='A configuração do Avatar é possível após a atualização da fotografia.', hide_image_field=False, size_warning=True, verbose_name='Seleção (Enquadramento)'),
        ),
    ]
