# Generated by Django 5.2.16 on 2026-09-15 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_iaquota_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="iaquota",
            name="descricao",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descrição do modelo da Quota IA.",
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="iaquota",
            name="servicos_autorizados",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (0, "Nenhuma"),
                        (1, "Todas"),
                        (2, "IA Genai Base"),
                        (3, "IA Classificação Matéria Service"),
                        (4, "IA Análise Similaridade Service"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Serviços Autorizados",
            ),
        ),
    ]
