# Generated by Django 5.2.16 on 2026-09-15 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_iaquota_descricao_iaquota_servicos_autorizados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iaquota",
            name="servicos_autorizados",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    choices=[
                        (2, "IA Genai Base"),
                        (3, "IA Classificação Matéria Service"),
                        (4, "IA Análise Similaridade Service"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Serviços Autorizados",
            ),
        ),
    ]
