# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0018_auto_20180215_1015'),
        ('core', '0004_auto_20180202_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatrabalho',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areatrabalho_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'Gabinete Parlamentar'), (20, 'Setor Administrativo'), (30, 'Institucional')], default=10, verbose_name='Tipo da Área de Trabalho'),
        ),
    ]
