# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160713_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='altura_pagina',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Altura da Página'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='alturaetiqueta',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Altura da Etiquta'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='entre_colunas',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Distância Entre Colunas'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='entre_linhas',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Distância Entre Linhas'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='fontesizebase',
            field=models.DecimalField(decimal_places=2, help_text='Em Pixels', max_digits=5, verbose_name='Tamanho da Letra'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='largura_pagina',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Largura da Página'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='larguraetiqueta',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Largura da Etiqueta'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='margem_esquerda',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Margem Esquerda'),
        ),
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='margem_superior',
            field=models.DecimalField(decimal_places=2, help_text='Em centímetros', max_digits=5, verbose_name='Margem Superior'),
        ),
    ]
