# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160627_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('menu_dados_auxiliares', 'Mostrar Menu Dados Auxiliares'), ('menu_tabelas_auxiliares', 'Mostrar Menu de Tabelas Auxiliares'), ('menu_contatos', 'Mostrar Menu de Cadastro de Contatos'), ('menu_area_trabalho', 'Mostrar Menu de Áreas de Trabalho'))},
        ),
    ]
