# Generated by Django 5.2.16 on 2026-09-15 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_iaquota_servicos_autorizados"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iaquota",
            options={
                "ordering": ("-ativo", "-modelo"),
                "verbose_name": "Quota IA",
                "verbose_name_plural": "Quotas IA",
            },
        ),
        migrations.AlterField(
            model_name="iaquota",
            name="servicos_autorizados",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("cmj.genia.IAGenaiBase", "IA Genai Base"),
                        (
                            "cmj.genia.IAClassificacaoMateriaService",
                            "IA Classificação Matéria Service",
                        ),
                        (
                            "cmj.genia.IAAnaliseSimilaridadeService",
                            "IA Análise Similaridade Service",
                        ),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Serviços Autorizados",
            ),
        ),
    ]
