# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 17:15
from __future__ import unicode_literals

import cmj.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_areatrabalho_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('read', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Lida')),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Notificado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
            bases=(cmj.core.models.CmjCleanMixin, models.Model),
        ),
    ]
