# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='user_origin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacao_origem_set', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
