# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160717_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressoenderecamento',
            name='rotate',
            field=models.CharField(choices=[(True, 'Sim'), (False, 'Não')], default=False, max_length=2, verbose_name='Rotacionar Texto'),
        ),
    ]
