# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_impressoenderecamento_rotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressoenderecamento',
            name='rotate',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Rotacionar Texto'),
        ),
    ]
