# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_impressoenderecamento_rotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trecho',
            name='search',
            field=models.TextField(blank=True, default=''),
        ),
    ]
