# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_trecho_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logradouro',
            options={'ordering': ('nome',), 'verbose_name': 'Logradouro', 'verbose_name_plural': 'Logradouros'},
        ),
        migrations.AlterModelOptions(
            name='tipologradouro',
            options={'ordering': ('nome',), 'verbose_name': 'Tipo de Logradouro', 'verbose_name_plural': 'Tipos de Logradouros'},
        ),
        migrations.AlterModelOptions(
            name='trecho',
            options={'ordering': ['municipio__nome', 'regiao_municipal__nome', 'distrito__nome', 'bairro__nome', 'tipo__nome', 'logradouro__nome'], 'verbose_name': 'Trecho de Logradouro', 'verbose_name_plural': 'Trechos de Logradouro'},
        ),
    ]
