# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_auto_20180516_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrMyPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('field', models.CharField(default='', max_length=254, verbose_name='Field')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
