# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ocrmypdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmypdf',
            name='sucesso',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Sucesso'),
        ),
    ]
