# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160722_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='areatrabalho',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
    ]
