# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ocrmypdf_sucesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmypdf',
            name='concluido',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
    ]
