# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ocrmypdf_concluido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatrabalho',
            options={'ordering': ('-ativo', '-tipo', 'parlamentar'), 'verbose_name': 'Área de Trabalho', 'verbose_name_plural': 'Áreas de Trabalho'},
        ),
    ]
