# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160725_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='areatrabalho',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='modified',
            field=models.DateTimeField(verbose_name='modified'),
        ),
    ]
