# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_certidaopublicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certidaopublicacao',
            name='hash_code',
            field=models.TextField(blank=True, max_length=200, verbose_name='Hash de Publicação'),
        ),
    ]
