# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190920_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='certidaopublicacao',
            name='field_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Field Name'),
        ),
    ]
