# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_certidaopublicacao_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certidaopublicacao',
            options={'ordering': ('-id',), 'verbose_name': 'Certidão de Publicação', 'verbose_name_plural': 'Certidões de Publicação'},
        ),
    ]
