# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200130_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='bi',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
