# Generated by Django 2.2.12 on 2020-05-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bi',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='certidaopublicacao',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='ocrmypdf',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='bairro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trechos_set', to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='distrito',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trechos_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='logradouro',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trechos_set', to='core.Logradouro', verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trechos_set', to='core.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trechos_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal'),
        ),
        migrations.AlterField(
            model_name='trecho',
            name='tipo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trechos_set', to='core.TipoLogradouro', verbose_name='Tipo de Logradouro'),
        ),
    ]
