# Generated by Django 2.2.16 on 2020-10-14 13:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0032_create_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='email')),
                ('operation', models.CharField(db_index=True, max_length=1, verbose_name='operation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('obj', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Object')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('obj_id', models.PositiveIntegerField(db_index=True, verbose_name='object_id')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='model')),
                ('app_name', models.CharField(db_index=True, max_length=100, verbose_name='app')),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'AuditLog',
                'verbose_name_plural': 'AuditLogs',
                'ordering': ('-id',),
            },
        ),
    ]
