# Generated by Django 2.2.24 on 2021-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='visibilidade',
            field=models.IntegerField(blank=True, choices=[(2, 'Restrição por Permissão'), (1, 'Restrição por Usuário'), (99, 'Privado'), (0, 'Público')], default=None, null=True, verbose_name='Visibilidade'),
        ),
    ]
