# Generated by Django 2.2.28 on 2023-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auditlog_visibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'Gabinete Parlamentar'), (20, 'Setor Administrativo'), (30, 'Institucional'), (40, 'Recepção'), (90, 'Procuradoria Jurídica'), (99, 'Documentos Públicos')], default=10, verbose_name='Tipo da Área de Trabalho'),
        ),
    ]
