# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20230522_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['id'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='impressoenderecamento',
            options={'ordering': ['id'], 'verbose_name': 'Impresso para Endereçamento', 'verbose_name_plural': 'Impressos para Endereçamento'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['id'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['id'], 'permissions': (('popup_notificacao', 'Visualização das notificações em Popup no Avatar do Usuário'),), 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='ocrmypdf',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='operadorareatrabalho',
            options={'ordering': ['id'], 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AlterModelOptions(
            name='regiaomunicipal',
            options={'ordering': ['id'], 'verbose_name': 'Região Municipal', 'verbose_name_plural': 'Regiões Municipais'},
        ),
    ]
