# Generated by Django 2.2.28 on 2024-09-20 17:12

import cmj.core.models
from django.db import migrations
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20240325_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='certidaopublicacao',
            name='certificado',
            field=sapl.utils.PortalFileField(blank=True, max_length=512, null=True, upload_to=cmj.core.models.certidao_create_path, verbose_name='Certificado'),
        ),
    ]
