# Generated by Django 2.2.28 on 2024-09-20 18:47

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_certidaopublicacao_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certidaopublicacao',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
