# Generated by Django 4.2.17 on 2024-12-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='operation',
            field=models.CharField(choices=[('U', 'Atualizado'), ('C', 'Criado'), ('D', 'Excluído'), ('P', 'Pesquisa')], db_index=True, max_length=1, verbose_name='operation'),
        ),
    ]
