# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_certidaopublicacao_revogado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='areatrabalho_set', through='core.OperadorAreaTrabalho', through_fields=('areatrabalho', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
