# Generated by Django 5.2.3 on 2025-06-23 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_areatrabalho_operadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAQuotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_diaria', models.PositiveIntegerField(default=0, verbose_name='Quota Diária')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Quota IA',
                'verbose_name_plural': 'Quotas IA',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IAQuotasLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='Data do Log de Quota IA', verbose_name='Data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('peso', models.PositiveIntegerField(default=1, verbose_name='Peso')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaquotaslog_set', to='core.iaquotas', verbose_name='Quota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaquotaslog_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Quota IA',
                'verbose_name_plural': 'Logs de Quota IA',
                'ordering': ('-id',),
            },
        ),
    ]
