# Generated by Django 5.2.3 on 2025-06-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_iaquotas_iaquotaslog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IAQuotas',
            new_name='IAQuota',
        ),
    ]
