# Generated by Django 5.2.3 on 2025-06-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_iaquota_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaquotaslog',
            name='user',
        ),
    ]
