# Generated by Django 5.2.9 on 2025-12-20 22:56

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_extensions_unaccent'),
    ]

    operations = [
        VectorExtension(),
    ]
