# Generated by Django 5.2.9 on 2026-02-03 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaquota',
            name='batch_size',
            field=models.PositiveIntegerField(default=5, help_text='Número de requisições processadas por vez.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tamanho do Lote'),
        ),
        migrations.AddField(
            model_name='iaquota',
            name='get_threads',
            field=models.PositiveIntegerField(default=1, help_text='Número de threads para processamento paralelo.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Número de Batch Create ao mesmo tempo'),
        ),
    ]
