# Generated by Django 5.2.11 on 2026-03-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_iaquota_batch_size_iaquota_get_threads"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iaquota",
            options={
                "ordering": ("-modelo",),
                "verbose_name": "Quota IA",
                "verbose_name_plural": "Quotas IA",
            },
        ),
    ]
