# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20180216_1604'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('titulo', models.CharField(default='', max_length=254, verbose_name='Título')),
                ('descricao', models.CharField(default='', max_length=10000, verbose_name='Descrição')),
                ('visibilidade', models.IntegerField(choices=[(1, 'Restrito'), (0, 'Público')], default=1, verbose_name='Visibilidade')),
                ('tipo', models.IntegerField(choices=[(10, 'Acesso a Informação'), (20, 'Elogio'), (30, 'Sugestão'), (40, 'Manifestação'), (900, 'Denuncia')], default=10, verbose_name='Tipo de Solicitação')),
                ('areatrabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AreaTrabalho', verbose_name='Área de Trablho')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
                'verbose_name': 'Solicitação',
            },
        ),
    ]
