# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.ouvidoria.models
import cmj.utils_files
import django.core.files.storage
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "titulo",
                    models.CharField(default="", max_length=254, verbose_name="Título"),
                ),
                ("descricao", models.TextField(default="", verbose_name="Descrição")),
                (
                    "visibilidade",
                    models.IntegerField(
                        choices=[(1, "Restrito"), (0, "Público")],
                        default=1,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[
                            (10, "Acesso a Informação"),
                            (20, "Elogio"),
                            (30, "Sugestão"),
                            (40, "Reclamação"),
                            (900, "Denúncia"),
                        ],
                        default=10,
                        verbose_name="Tipo de Solicitação",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("00", "A Receber"),
                            ("10", "Recebida"),
                            ("20", "Pendente"),
                            ("30", "Concluída"),
                        ],
                        default="00",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "hash_code",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        verbose_name="Hash de Acesso Anônimo",
                    ),
                ),
                (
                    "areatrabalho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.areatrabalho",
                        verbose_name="Área de Trablho",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MensagemSolicitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                ("descricao", models.TextField(default="", verbose_name="Descrição")),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        help_text="Envie um arquivo em anexo a sua mensagem.",
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="DO_NOT_USE",
                            location="/mnt/volumes/cmj_media/media_protected",
                        ),
                        upload_to=cmj.ouvidoria.models.anexo_ouvidoria_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_midias],
                        verbose_name="Anexo",
                    ),
                ),
                ("content_type", models.CharField(default="", max_length=250)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensagemsolicitacao_set",
                        to="ouvidoria.solicitacao",
                        verbose_name="Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Solicitação",
                "verbose_name_plural": "Mensagens de Solicitação",
                "ordering": ("created",),
            },
        ),
    ]
