# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
