# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ouvidoria', '0002_auto_20180219_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('descricao', models.TextField(default='', verbose_name='Descrição')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvidoria.Solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Mensagem de Solicitação',
                'verbose_name_plural': 'Mensagens de Solicitação',
                'ordering': ('created',),
            },
        ),
    ]
