# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0003_mensagemsolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagemsolicitacao_set', to='ouvidoria.Solicitacao', verbose_name='Solicitação'),
        ),
    ]
