# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 12:44
from __future__ import unicode_literals

import cmj.ouvidoria.models
import cmj.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0005_auto_20180227_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsolicitacao',
            name='anexo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='DO_NOT_USE', location=Path('/home/leandro/desenvolvimento/envs/cmj/media_protected')), upload_to=cmj.ouvidoria.models.anexo_ouvidoria_path, validators=[cmj.utils.restringe_tipos_de_arquivo_midias], verbose_name='Mídia'),
        ),
        migrations.AddField(
            model_name='mensagemsolicitacao',
            name='content_type',
            field=models.CharField(default='', max_length=250),
        ),
    ]
