# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0008_solicitacao_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsolicitacao',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
