# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 12:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
from unipath.path import Path

import cmj.ouvidoria.models
import cmj.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0009_auto_20200221_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemsolicitacao',
            name='anexo',
            field=models.FileField(blank=True, help_text='Envie um arquivo em anexo a sua mensagem.', null=True, storage=django.core.files.storage.FileSystemStorage(
                base_url='DO_NOT_USE',
                location=settings.MEDIA_PROTECTED_ROOT), upload_to=cmj.ouvidoria.models.anexo_ouvidoria_path, validators=[cmj.utils.restringe_tipos_de_arquivo_midias], verbose_name='Anexo'),
        ),
    ]
