# Generated by Django 4.2.16 on 2024-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0014_alter_mensagemsolicitacao_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(blank=True, choices=[('10', 'Recebidas'), ('20', 'Pendentes'), ('30', 'Resolvidas')], default='10', max_length=2, verbose_name='Status'),
        ),
    ]
