# Generated by Django 4.2.16 on 2024-10-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria', '0016_solicitacao_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(blank=True, choices=[('00', 'A Receber'), ('10', 'Recebida'), ('20', 'Pendente'), ('30', 'Concluída')], default='00', max_length=2, verbose_name='Status'),
        ),
    ]
