cmjdb:
  image: postgres:10.6
  restart: always
  environment:
    POSTGRES_PASSWORD: cmj
    POSTGRES_USER: cmj
    POSTGRES_DB: cmj
    PGDATA: /var/cmjatai/cmj/lib/postgresql/data/
  volumes:
    - cmjdb_data:/var/cmjatai/cmj/lib/postgresql/data/
  ports:
    - "5434:5432"
cmj:
  build: .
  restart: always
  environment:
    ADMIN_PASSWORD: admin
    ADMIN_EMAIL: admin@camarajatai.go.gov.br
    DEBUG: 'False'
  volumes:
    - cmj_data:/var/cmjatai/cmj/data
    - cmj_media:/var/cmjatai/cmj/media
    - cmj_media_protected:/var/cmjatai/cmj/media_protected
  links:
    - cmjdb
  ports:
    - "80:80"
