#'reversion.middleware.RevisionMiddleware',
MIDDLEWARE = (
    "cmj.middleware.disabled.DisabledMiddleware",
    "cmj.middleware.request_id.RequestIdMiddleware",
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "cmj.middleware.endpoint_restriction.EndpointRestrictionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "cmj.middleware.breadcrumb.BreadCrumbMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
)
