# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.arq.models
import cmj.mixins
import django.core.serializers.json
import sapl.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArqClasse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "checkcheck",
                    models.BooleanField(default=False, verbose_name="Arquivado"),
                ),
                (
                    "render_tree2",
                    models.BooleanField(
                        default=False, verbose_name="Renderização em Tree2"
                    ),
                ),
                (
                    "can_arqdoc",
                    models.BooleanField(
                        default=False, verbose_name="Permitir Adição de ArqDoc"
                    ),
                ),
                (
                    "codigo",
                    models.PositiveIntegerField(default=0, verbose_name="Código"),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "perfil",
                    models.IntegerField(
                        choices=[
                            (100, "Classe de Localização Física"),
                            (200, "Classe de Organização Lógica"),
                        ],
                        default=100,
                        verbose_name="Perfil da Classe",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
            ],
            options={
                "verbose_name": "ArqClasse",
                "verbose_name_plural": "ArqClasses",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="ArqDoc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "checkcheck",
                    models.BooleanField(default=False, verbose_name="Arquivado?"),
                ),
                (
                    "editado",
                    models.BooleanField(
                        default=False, verbose_name="Editado Manualmente?"
                    ),
                ),
                (
                    "codigo",
                    models.PositiveIntegerField(default=0, verbose_name="Código"),
                ),
                ("titulo", models.CharField(max_length=250, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data", models.DateField(verbose_name="Data do Documento")),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=cmj.arq.models.arqdoc_path,
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "ArqDoc",
                "verbose_name_plural": "ArcDocs",
                "ordering": ("codigo",),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft",
                "verbose_name_plural": "Draft",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="DraftMidia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "sequencia",
                    models.PositiveIntegerField(default=0, verbose_name="Sequência"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=cmj.arq.models.draftmidia_path,
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia",
                "verbose_name_plural": "Mídias",
                "ordering": ("draft", "sequencia"),
            },
        ),
    ]
