# Generated by Django 2.2.28 on 2023-03-28 19:39

import cmj.arq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmidia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=cmj.arq.models.draftmidia_path, verbose_name='Arquivo'),
        ),
    ]
