# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("arq", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="arqclasse",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="arqclasse",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="childs",
                to="arq.arqclasse",
                verbose_name="Filhos",
            ),
        ),
        migrations.AddField(
            model_name="arqclasse",
            name="raiz",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nodes",
                to="arq.arqclasse",
                verbose_name="Raiz",
            ),
        ),
        migrations.AddField(
            model_name="arqdoc",
            name="classe_estrutural",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arqdoc_estrutural_set",
                to="arq.arqclasse",
                verbose_name="Classificação Estrutural",
            ),
        ),
        migrations.AddField(
            model_name="arqdoc",
            name="classe_logica",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arqdoc_logica_set",
                to="arq.arqclasse",
                verbose_name="Classificação Lógica",
            ),
        ),
        migrations.AddField(
            model_name="arqdoc",
            name="modifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modifier",
            ),
        ),
        migrations.AddField(
            model_name="arqdoc",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="arqdoc",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="childs",
                to="arq.arqdoc",
                verbose_name="Filhos",
            ),
        ),
        migrations.AddField(
            model_name="arqdoc",
            name="raiz",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nodes",
                to="arq.arqdoc",
                verbose_name="Raiz",
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="draftmidia",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draftmidia_set",
                to="arq.draft",
                verbose_name="Draft Midia",
            ),
        ),
    ]
