# Generated by Django 2.2.28 on 2023-03-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0002_draftmidia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmidia',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draftmidia_set', to='arq.Draft', verbose_name='Draft Midia'),
        ),
    ]
