# Generated by Django 2.2.28 on 2023-03-31 13:52

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0004_auto_20230331_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmidia',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
