# Generated by Django 2.2.28 on 2023-03-31 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0005_draftmidia_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftmidia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
