# Generated by Django 2.2.28 on 2023-08-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0008_auto_20230824_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmidia',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftmidia_set', to='arq.Draft', verbose_name='Draft Midia'),
        ),
    ]
