# Generated by Django 2.2.28 on 2023-10-24 19:14

import cmj.arq.models
import cmj.mixins
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arq', '0009_auto_20230825_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqclasse',
            name='perfil',
            field=models.IntegerField(choices=[(100, 'Classe de Localização Física'), (200, 'Classe de Organização Lógica')], default=200, verbose_name='Perfil da Classe'),
        ),
        migrations.CreateModel(
            name='ArqDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('codigo', models.PositiveIntegerField(default=0, verbose_name='Código')),
                ('titulo', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('arquivo', sapl.utils.PortalFileField(blank=True, max_length=512, null=True, upload_to=cmj.arq.models.arqdoc_path, verbose_name='Arquivo')),
                ('classe_estrutural', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arqdoc_estrutural_set', to='arq.ArqClasse', verbose_name='Classificação Estrutural')),
                ('classe_logica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqdoc_logica_set', to='arq.ArqClasse', verbose_name='Classificação Lógica')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='arq.ArqDoc', verbose_name='Filhos')),
                ('raiz', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='arq.ArqDoc', verbose_name='Containers')),
            ],
            options={
                'verbose_name': 'ArqDoc',
                'verbose_name_plural': 'ArcDocs',
                'ordering': ('codigo',),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
    ]
