# Generated by Django 2.2.28 on 2023-10-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0010_auto_20231024_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqdoc',
            name='classe_estrutural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arqdoc_estrutural_set', to='arq.ArqClasse', verbose_name='Classificação Estrutural'),
        ),
        migrations.AlterField(
            model_name='arqdoc',
            name='classe_logica',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arqdoc_logica_set', to='arq.ArqClasse', verbose_name='Classificação Lógica'),
        ),
    ]
