# Generated by Django 2.2.28 on 2024-02-02 19:45

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0011_auto_20231024_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqdoc',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 19, 44, 59, 387141, ), verbose_name='Data do Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arqdoc',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arqdoc',
            name='titulo',
            field=models.CharField(default='', max_length=250, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
