# Generated by Django 2.2.28 on 2024-02-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0013_auto_20240219_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqclasse',
            old_name='arquivado',
            new_name='checkcheck',
        ),
        migrations.RenameField(
            model_name='arqdoc',
            old_name='arquivado',
            new_name='checkcheck',
        ),
    ]
