# Generated by Django 2.2.28 on 2024-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0014_auto_20240220_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arqclasse',
            options={'ordering': ('codigo',), 'verbose_name': 'ArqClasse', 'verbose_name_plural': 'ArqClasses'},
        ),
        migrations.AlterField(
            model_name='arqclasse',
            name='perfil',
            field=models.IntegerField(choices=[(100, 'Classe de Localização Física'), (200, 'Classe de Organização Lógica')], default=100, verbose_name='Perfil da Classe'),
        ),
    ]
