# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0015_auto_20240226_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqclasse',
            name='render_tree2',
            field=models.BooleanField(default=False, verbose_name='Renderização em Tree2'),
        ),
    ]
