# Generated by Django 2.2.28 on 2024-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0016_arqclasse_render_tree2'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqclasse',
            name='can_arqdoc',
            field=models.BooleanField(default=False, verbose_name='Permitir Adição de ArqDoc'),
        ),
    ]
