# Generated by Django 2.2.28 on 2024-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0017_arqclasse_can_arqdoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftmidia',
            options={'ordering': ('draft', 'sequencia'), 'verbose_name': 'Mídia', 'verbose_name_plural': 'Mídias'},
        ),
    ]
