# Generated by Django 2.2.28 on 2024-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0018_auto_20240420_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqdoc',
            name='editado',
            field=models.BooleanField(default=False, verbose_name='Editado Manualmente?'),
        ),
        migrations.AlterField(
            model_name='arqdoc',
            name='checkcheck',
            field=models.BooleanField(default=False, verbose_name='Arquivado?'),
        ),
    ]
