# Generated by Django 4.2.16 on 2024-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arq', '0020_alter_arqclasse_metadata_alter_arqdoc_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqdoc',
            name='_paginas',
            field=models.IntegerField(default=0, verbose_name='Número de Páginas'),
        ),
    ]
