# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cmj.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PullYoutube",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_before",
                    models.DateTimeField(verbose_name="published_before"),
                ),
                (
                    "published_after",
                    models.DateTimeField(verbose_name="published_after"),
                ),
                (
                    "last_run",
                    models.DateTimeField(auto_now=True, verbose_name="last_run"),
                ),
                (
                    "execucao",
                    models.PositiveIntegerField(default=0, verbose_name="Execução"),
                ),
            ],
            options={
                "verbose_name": "PullYoutube",
                "verbose_name_plural": "PullYoutube",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PullExec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_exec",
                    models.DateTimeField(auto_now_add=True, verbose_name="data_exec"),
                ),
                ("quota", models.PositiveIntegerField(default=1, verbose_name="Quota")),
                (
                    "pull",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pullyoutube_set",
                        to="videos.pullyoutube",
                        verbose_name="PullYoutube",
                    ),
                ),
            ],
            options={
                "verbose_name": "PullExec",
                "verbose_name_plural": "PullExec",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "vid",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Video Id "
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Object",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "execucao",
                    models.PositiveIntegerField(default=0, verbose_name="Execução"),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vídeo",
                "verbose_name_plural": "Vídeos",
                "ordering": ("-created",),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VideoParte",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("time_start", models.PositiveIntegerField(default=0)),
                (
                    "fieldname",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="videoparte_set",
                        to="videos.video",
                        verbose_name="Vídeo",
                    ),
                ),
            ],
            options={
                "verbose_name": "VideoParte",
                "verbose_name_plural": "Video Partes",
                "ordering": ("id",),
            },
        ),
    ]
