# Generated by Django 2.2.24 on 2021-10-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullYoutube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_before', models.DateTimeField(verbose_name='published_before')),
                ('published_after', models.DateTimeField(verbose_name='published_after')),
                ('execucao', models.PositiveIntegerField(default=0, verbose_name='Execução')),
            ],
        ),
    ]
