# Generated by Django 2.2.24 on 2021-10-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('videos', '0002_pullyoutube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pullyoutube',
            options={'ordering': ('id',), 'verbose_name': 'PullYoutube', 'verbose_name_plural': 'PullYoutube'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created',), 'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.CreateModel(
            name='VideoParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('time_start', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videostartvinculo_set', to='videos.Video', verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'VideoParte',
                'verbose_name_plural': 'Video Partes',
                'ordering': ('id',),
            },
        ),
    ]
