# Generated by Django 2.2.24 on 2021-10-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_pullyoutube_last_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_set', to='videos.PullYoutube', verbose_name='PullYoutube')),
            ],
            options={
                'verbose_name': 'PullExec',
                'verbose_name_plural': 'PullExec',
                'ordering': ('id',),
            },
        ),
    ]
