# Generated by Django 2.2.24 on 2021-10-16 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_pullexec'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullexec',
            name='data_exec',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last_run'),
            preserve_default=False,
        ),
    ]
