# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0001_initial'),
        ('core', '0001_initial'),
        ('parlamentares', '0021_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores_areatrabalho_set', to=settings.AUTH_USER_MODEL, verbose_name='Operador da Área de Trabalho'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_trabalho_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='forma_tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='cerimonial.PronomeTratamento', verbose_name='Forma de Tratamento neste Local'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='parlamentares.Municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='cerimonial.TipoLocalTrabalho', verbose_name='Tipo do Local de Trabalho'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='trecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='core.Trecho', verbose_name='Trecho'),
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacoes_partidarias_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacoes_partidarias_set', to='parlamentares.Partido', verbose_name='Partido'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='parlamentares.Municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='cerimonial.TipoEndereco', verbose_name='Tipo do Endereço'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='trecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='core.Trecho', verbose_name='Trecho'),
        ),
        migrations.AddField(
            model_name='email',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='email',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cerimonial.TipoEmail', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes_set', to='cerimonial.Parentesco', verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='contato',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_set', to='cerimonial.EstadoCivil', verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='contato',
            name='forma_tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_set', to='cerimonial.PronomeTratamento', verbose_name='Forma de Tratamento'),
        ),
        migrations.AddField(
            model_name='contato',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
        migrations.AddField(
            model_name='contato',
            name='perfil_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_set', to=settings.AUTH_USER_MODEL, verbose_name='Perfil do Usuário'),
        ),
        migrations.AddField(
            model_name='contato',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_set', to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='area_trabalho_set', through='cerimonial.OperadorAreaTrabalho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_trabalho_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.CreateModel(
            name='DependentePerfil',
            fields=[
            ],
            options={
                'verbose_name': 'Dependente do Perfil',
                'verbose_name_plural': 'Dependentes do Perfil',
                'proxy': True,
            },
            bases=('cerimonial.dependente',),
        ),
        migrations.CreateModel(
            name='EmailPerfil',
            fields=[
            ],
            options={
                'verbose_name': 'Email do Perfil',
                'verbose_name_plural': "Email's do Perfil",
                'proxy': True,
            },
            bases=('cerimonial.email',),
        ),
        migrations.CreateModel(
            name='EnderecoPerfil',
            fields=[
            ],
            options={
                'verbose_name': 'Endereço do Perfil',
                'verbose_name_plural': 'Endereços do Perfil',
                'proxy': True,
            },
            bases=('cerimonial.endereco',),
        ),
        migrations.CreateModel(
            name='LocalTrabalhoPerfil',
            fields=[
            ],
            options={
                'verbose_name': 'Local de Trabalho do Perfil',
                'verbose_name_plural': 'Locais de Trabalho do Perfil',
                'proxy': True,
            },
            bases=('cerimonial.localtrabalho',),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.contato',),
        ),
        migrations.CreateModel(
            name='TelefonePerfil',
            fields=[
            ],
            options={
                'verbose_name': 'Telefone do Perfil',
                'verbose_name_plural': 'Telefones do Perfil',
                'proxy': True,
            },
            bases=('cerimonial.telefone',),
        ),
    ]
