# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='quantos_filhos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Quantos Filhos?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg_data_expedicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
