# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cerimonial', '0001_initial'),
        ('core', '0001_initial'),
        ('parlamentares', '0021_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtrabalho',
            name='trecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='core.Trecho', verbose_name='Trecho'),
        ),
        migrations.AddField(
            model_name='email',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='email',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cerimonial.TipoEmail', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes_set', to='cerimonial.Parentesco', verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='contato',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_set', to='cerimonial.EstadoCivil', verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='contato',
            name='forma_tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_set', to='cerimonial.PronomeTratamento', verbose_name='Forma de Tratamento'),
        ),
        migrations.AddField(
            model_name='contato',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
        migrations.AddField(
            model_name='contato',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar Associado'),
        ),
    ]
