# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0002_auto_20160619_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadoraTelefonia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Operadora')),
            ],
            options={
                'verbose_name': 'Operadora de Telefonia',
                'verbose_name_plural': 'Operadoras de Telefonia',
            },
        ),
        migrations.AddField(
            model_name='telefone',
            name='operadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefones_set', to='cerimonial.Pessoa', verbose_name='Operadora de Telefonia'),
        ),
    ]
