# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0002_auto_20160630_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='forma_tratamento',
        ),
        migrations.RemoveField(
            model_name='localtrabalho',
            name='forma_tratamento',
        ),
        migrations.RemoveField(
            model_name='pronometratamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pronometratamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='nome_por_extenso',
            field=models.CharField(default='', max_length=254, verbose_name='Nome Por Extenso'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='identidade_genero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Como se reconhece?'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo Biológico'),
        ),
    ]
