# Generated by Django 2.2.12 on 2020-05-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0003_auto_20170329_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiacaopartidaria',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiacaopartidaria_set', to='parlamentares.Partido', verbose_name='Partido'),
        ),
    ]
