# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0003_auto_20160801_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeContatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('contatos', models.ManyToManyField(blank=True, related_name='grupo_set', to='cerimonial.Contato', verbose_name='Contatos do Grupo')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'Grupos de Contatos',
                'verbose_name': 'Grupo de Contatos',
                'ordering': ('nome',),
            },
        ),
    ]
