# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0003_auto_20160619_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='de_quem_e',
            field=models.CharField(blank=True, help_text='Se não é próprio, de quem é?', max_length=40, verbose_name='De quem é?'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='proprio',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Próprio?'),
        ),
    ]
