# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0003_auto_20160622_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtrabalho',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='nome',
            field=models.CharField(max_length=254, verbose_name='Nome / Razão Social'),
        ),
    ]
