# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0003_auto_20160703_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronometratamento',
            name='abreviatura',
        ),
        migrations.RemoveField(
            model_name='tipoautoridade',
            name='pronome_tratamento',
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Cargo/Função'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='preferencial',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Preferencial?'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='pronome_tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='cerimonial.PronomeTratamento', verbose_name='Pronome de Tratamento'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='tipo_autoridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='cerimonial.TipoAutoridade', verbose_name='Tipo de Autoridade'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='abreviatura_plural_f',
            field=models.CharField(default='', max_length=254, verbose_name='Abreviatura Plural Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='abreviatura_plural_m',
            field=models.CharField(default='', max_length=254, verbose_name='Abreviatura Plural Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='abreviatura_singular_f',
            field=models.CharField(default='', max_length=254, verbose_name='Abreviatura Singular Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='abreviatura_singular_m',
            field=models.CharField(default='', max_length=254, verbose_name='Abreviatura Singular Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='enderecamento_plural_f',
            field=models.CharField(default='', max_length=254, verbose_name='Endereçamento Plural Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='enderecamento_plural_m',
            field=models.CharField(default='', max_length=254, verbose_name='Endereçamento Plural Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='enderecamento_singular_f',
            field=models.CharField(default='', max_length=254, verbose_name='Endereçamento Singular Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='enderecamento_singular_m',
            field=models.CharField(default='', max_length=254, verbose_name='Endereçamento Singular Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='tipo_autoridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronometratamento_set', to='cerimonial.TipoAutoridade', verbose_name='Tipo de Autoridade'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_direto_plural_f',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Direto Plural Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_direto_plural_m',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Direto Plural Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_direto_singular_f',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Direto Singular Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_direto_singular_m',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Direto Singular Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_indireto_plural_f',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Indireto Plural Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_indireto_plural_m',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Indireto Plural Masculino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_indireto_singular_f',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Indireto Singular Feminino'),
        ),
        migrations.AddField(
            model_name='pronometratamento',
            name='vocativo_indireto_singular_m',
            field=models.CharField(default='', max_length=254, verbose_name='Vocativo Indireto Singular Masculino'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localtrabalho_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='parlamentares.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='cerimonial.TipoLocalTrabalho', verbose_name='Tipo do Local de Trabalho'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='trecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='core.Trecho', verbose_name='Trecho'),
        ),
    ]
