# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160623_1608'),
        ('parlamentares', '0021_merge'),
        ('cerimonial', '0004_auto_20160624_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, default='', max_length=254, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, default='', max_length=50, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, default='', max_length=254, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, default='', max_length=30, verbose_name='Complemento')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_set', to='cerimonial.Contato', verbose_name='Contato')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='core.Distrito', verbose_name='Distrito')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='parlamentares.Municipio', verbose_name='Município')),
                ('regiao_municipal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='cerimonial.TipoEndereco', verbose_name='Tipo do Local de Trabalho')),
                ('trecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='core.Trecho', verbose_name='Trecho')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
                'verbose_name': 'Endereço',
            },
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='forma_tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais_trabalho_set', to='cerimonial.PronomeTratamento', verbose_name='Forma de Tratamento neste Local'),
        ),
    ]
