# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0004_auto_20160703_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='area_trabalho',
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='areatrabalho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operadorareatrabalho_set', to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='areatrabalho_set', through='cerimonial.OperadorAreaTrabalho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areatrabalho',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areatrabalho_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.EstadoCivil', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='perfil_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to=settings.AUTH_USER_MODEL, verbose_name='Perfil do Usuário'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependente_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependente_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependente_set', to='cerimonial.Parentesco', verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='parlamentares.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='core.RegiaoMunicipal', verbose_name='Região Municipal'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='cerimonial.TipoEndereco', verbose_name='Tipo do Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='trecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='core.Trecho', verbose_name='Trecho'),
        ),
        migrations.AlterField(
            model_name='filiacaopartidaria',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacaopartidaria_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='filiacaopartidaria',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacaopartidaria_set', to='parlamentares.Partido', verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='grupos_associados',
            field=models.ManyToManyField(related_name='operadorareatrabalho_set', to='auth.Group', verbose_name='Grupos Associados'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadorareatrabalho_set', to=settings.AUTH_USER_MODEL, verbose_name='Operador da Área de Trabalho'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefone_set', to='cerimonial.OperadoraTelefonia', verbose_name='Operadora de Telefonia'),
        ),
    ]
