# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0005_auto_20160619_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, verbose_name='Número')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerimonial.Pessoa', verbose_name='Pessoa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cerimonial.TipoEmail', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': "Email's",
                'verbose_name': 'Email',
            },
        ),
    ]
