# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0005_auto_20160703_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronometratamento',
            name='tipo_autoridade',
        ),
        migrations.AddField(
            model_name='tipoautoridade',
            name='pronomes',
            field=models.ManyToManyField(related_name='tipoautoridade_set', to='cerimonial.PronomeTratamento'),
        ),
    ]
