# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parlamentares', '0021_merge'),
        ('cerimonial', '0005_auto_20160624_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiliacaoPartidaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de Filiação')),
                ('data_desfiliacao', models.DateField(blank=True, null=True, verbose_name='Data de Desfiliação')),
            ],
            options={
                'verbose_name_plural': 'Filiações Partidárias',
                'verbose_name': 'Filiação Partidária',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.contato',),
        ),
        migrations.AlterModelOptions(
            name='nivelinstrucao',
            options={'verbose_name': 'Nível de Instrução', 'verbose_name_plural': 'Níveis de Instrução'},
        ),
        migrations.AddField(
            model_name='contato',
            name='perfil_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_set', to=settings.AUTH_USER_MODEL, verbose_name='Perfil do Usuário'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(blank=True, default='', help_text='O campo endereço também é um campo de busca, nele você pode digitar qualquer informação, inclusive digitar o cep para localizar o endereço, e vice-versa!', max_length=254, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_set', to='cerimonial.TipoEndereco', verbose_name='Tipo do Endereço'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='endereco',
            field=models.CharField(blank=True, default='', help_text='O campo endereço também é um campo de busca, nele você pode digitar qualquer informação, inclusive digitar o cep para localizar o endereço, e vice-versa!', max_length=254, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacoes_partidarias_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacoes_partidarias_set', to='parlamentares.Partido', verbose_name='Partido'),
        ),
    ]
