# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0005_auto_20160801_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrabalho',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='core.Bairro', verbose_name='Bairro'),
        ),
    ]
