# Generated by Django 2.2.28 on 2023-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0005_visita_visitante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ('-created',), 'verbose_name': 'Registro de Entrada', 'verbose_name_plural': 'Registros de Entrada'},
        ),
        migrations.AlterField(
            model_name='visitante',
            name='documento',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='RG/CPF/CNH'),
        ),
    ]
