# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0006_auto_20160703_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='permissao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Permite que nossa instituição envie informações         através deste email?', verbose_name='Permissão:'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='permissao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Permite que nossa instituição entre em contato         através deste telefone?', verbose_name='Permissão:'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='pronome_tratamento',
            field=models.ForeignKey(blank=True, help_text='O pronome de tratamento é opcional, mas será         obrigatório caso seja selecionado um tipo de autoridade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='cerimonial.PronomeTratamento', verbose_name='Pronome de Tratamento'),
        ),
    ]
