# Generated by Django 2.2.28 on 2023-05-25 17:47

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0006_auto_20230525_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fotografia',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=sapl.utils.texto_upload_path, verbose_name='Fotografia'),
        ),
    ]
