# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0006_auto_20160803_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrabalho',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Ao definir um cargo e função aqui, o Cargo/Função preenchido na aba "Dados Básicos", será desconsiderado ao gerar impressos!', max_length=254, verbose_name='Cargo/Função'),
        ),
    ]
