# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='preferencial',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Preferêncial?'),
        ),
    ]
