# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0021_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0006_auto_20160625_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(default='', max_length=254, verbose_name='Descrição')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_set', to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('parlamentar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar')),
            ],
            options={
                'verbose_name_plural': 'Áreas de Trabalho',
                'verbose_name': 'Área de Trabalho',
            },
        ),
        migrations.RemoveField(
            model_name='contato',
            name='parlamentar',
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='nivelinstrucao',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='operadoratelefonia',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='statusvisita',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoautoridade',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoemail',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoendereco',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='tipolocaltrabalho',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AlterField(
            model_name='tipotelefone',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Descrição'),
        ),
        migrations.AddField(
            model_name='contato',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_set', to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
    ]
