# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0007_auto_20160803_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contato',
            unique_together=set([('nome', 'data_nascimento', 'workspace', 'perfil_user')]),
        ),
    ]
