# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0007_auto_20160703_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='search',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='permissao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Permite que nossa instituição envie informações         para este email?', verbose_name='Permissão:'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='permissao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Permite que nossa instituição entre em contato         com você neste telefone?', verbose_name='Permissão:'),
        ),
    ]
