# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0007_email_preferencial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operadoratelefonia',
            name='nome',
        ),
        migrations.AddField(
            model_name='operadoratelefonia',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='nivelinstrucao',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='parentesco',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='statusvisita',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='tipoautoridade',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='tipoemail',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='tipoendereco',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='tipolocaltrabalho',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
        migrations.AlterField(
            model_name='tipotelefone',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Nome / Discrição'),
        ),
    ]
