# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0008_auto_20160804_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['nome'], 'permissions': (('print_impressoenderecamento', 'Pode Imprimir Impressos de Endereçamento'), ('print_rel_contato_agrupado_por_processo', 'Pode Imprimir Relatório de Contatos Agrupados por Processo')), 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
