# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0008_auto_20160626_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorAreaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('administrador', models.BooleanField(choices=[(None, '---------'), (True, 'Sim'), (False, 'Não')], default=None, verbose_name='Administrador da Área?')),
            ],
            options={
                'verbose_name': 'Operador da Área de Trabalho',
                'verbose_name_plural': 'Operadores da Área de Trabalho',
            },
        ),
        migrations.AlterModelOptions(
            name='areatrabalho',
            options={'verbose_name': 'Área de Trabalho', 'verbose_name_plural': 'Áreas de Trabalho'},
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='area_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador da Área de Trabalho'),
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='operadores', through='cerimonial.OperadorAreaTrabalho', to=settings.AUTH_USER_MODEL),
        ),
    ]
