# Generated by Django 2.2.28 on 2023-05-25 19:17

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0008_auto_20230525_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fotografia',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=sapl.utils.texto_upload_path, verbose_name='Fotografia'),
        ),
    ]
