# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0008_auto_20160704_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtrabalho',
            name='pronome_tratamento',
        ),
        migrations.RemoveField(
            model_name='localtrabalho',
            name='tipo_autoridade',
        ),
        migrations.AddField(
            model_name='contato',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Cargo/Função'),
        ),
        migrations.AddField(
            model_name='contato',
            name='pronome_tratamento',
            field=models.ForeignKey(blank=True, help_text='O pronome de tratamento é opcional, mas será         obrigatório caso seja selecionado um tipo de autoridade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.PronomeTratamento', verbose_name='Pronome de Tratamento'),
        ),
        migrations.AddField(
            model_name='contato',
            name='tipo_autoridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.TipoAutoridade', verbose_name='Tipo de Autoridade'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contato_set', to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
    ]
