# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0009_auto_20160704_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areatrabalho',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='areatrabalho',
            name='operadores',
        ),
        migrations.RemoveField(
            model_name='areatrabalho',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='areatrabalho',
            name='parlamentar',
        ),
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='areatrabalho',
        ),
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='grupos_associados',
        ),
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='user',
        ),
        migrations.AlterField(
            model_name='contato',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contato_set', to='core.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
        migrations.DeleteModel(
            name='AreaTrabalho',
        ),
        migrations.DeleteModel(
            name='OperadorAreaTrabalho',
        ),
    ]
