# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0009_auto_20160627_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='area_trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areastrabalho_set', to='cerimonial.AreaTrabalho', verbose_name='Área de Trabalho'),
        ),
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores_set', to=settings.AUTH_USER_MODEL, verbose_name='Operador da Área de Trabalho'),
        ),
    ]
