# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0009_auto_20160619_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_set', to='cerimonial.EstadoCivil', verbose_name='Estado Civil'),
        ),
    ]
