# Generated by Django 2.2.28 on 2023-05-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0009_auto_20230525_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ('nome', 'documento'), 'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
    ]
