# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20160705_1011'),
        ('cerimonial', '0010_auto_20160705_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
    ]
