# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0010_auto_20160619_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadoratelefonia',
            options={'permissions': (('view_dados_auxiliares', 'Pode ser Visto em Dados Auxiliares'),), 'verbose_name': 'Operadora de Telefonia', 'verbose_name_plural': 'Operadoras de Telefonia'},
        ),
    ]
