# Generated by Django 2.2.28 on 2024-02-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0010_auto_20230529_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações Gerais'),
        ),
    ]
