# Generated by Django 2.2.28 on 2024-02-07 19:23

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0011_visita_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fotografia',
            field=sapl.utils.PortalImageField(blank=True, max_length=512, null=True, upload_to=sapl.utils.texto_upload_path, verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='documento',
            field=models.CharField(max_length=30, verbose_name='RG/CPF/CNH'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='fotografia',
            field=sapl.utils.PortalImageField(blank=True, max_length=512, null=True, upload_to=sapl.utils.texto_upload_path, verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Telefone'),
        ),
    ]
