# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0011_auto_20160627_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='area_trabalho_set', through='cerimonial.OperadorAreaTrabalho', to=settings.AUTH_USER_MODEL),
        ),
    ]
