# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0011_auto_20160705_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='ddd',
        ),
        migrations.AlterField(
            model_name='email',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_set', to='cerimonial.TipoEmail', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefone_set', to='cerimonial.Contato', verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=100, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefone_set', to='cerimonial.TipoTelefone', verbose_name='Tipo'),
        ),
    ]
