# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0011_auto_20160619_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadoratelefonia',
            options={'permissions': (('view_operadora_telefonia', 'Pode visualizar operadoras de telefonia.'),), 'verbose_name': 'Operadora de Telefonia', 'verbose_name_plural': 'Operadoras de Telefonia'},
        ),
    ]
