# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0012_auto_20240207_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependente',
            options={'ordering': ['id'], 'verbose_name': 'Dependente', 'verbose_name_plural': 'Dependentes'},
        ),
        migrations.AlterModelOptions(
            name='dependenteperfil',
            options={'ordering': ['id'], 'verbose_name': 'Dependente do Perfil', 'verbose_name_plural': 'Dependentes do Perfil'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['id'], 'verbose_name': 'Email', 'verbose_name_plural': "Email's"},
        ),
        migrations.AlterModelOptions(
            name='emailperfil',
            options={'ordering': ['id'], 'verbose_name': 'Email do Perfil', 'verbose_name_plural': "Email's do Perfil"},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['id'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='enderecoperfil',
            options={'ordering': ['id'], 'verbose_name': 'Endereço do Perfil', 'verbose_name_plural': 'Endereços do Perfil'},
        ),
        migrations.AlterModelOptions(
            name='filiacaopartidaria',
            options={'ordering': ['id'], 'verbose_name': 'Filiação Partidária', 'verbose_name_plural': 'Filiações Partidárias'},
        ),
        migrations.AlterModelOptions(
            name='localtrabalho',
            options={'ordering': ['id'], 'verbose_name': 'Local de Trabalho', 'verbose_name_plural': 'Locais de Trabalho'},
        ),
        migrations.AlterModelOptions(
            name='localtrabalhoperfil',
            options={'ordering': ['id'], 'verbose_name': 'Local de Trabalho do Perfil', 'verbose_name_plural': 'Locais de Trabalho do Perfil'},
        ),
        migrations.AlterModelOptions(
            name='processocontato',
            options={'ordering': ['id'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='pronometratamento',
            options={'ordering': ['id'], 'verbose_name': 'Pronome de Tratamento', 'verbose_name_plural': 'Pronomes de tratamento'},
        ),
        migrations.AlterModelOptions(
            name='telefone',
            options={'ordering': ['id'], 'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
    ]
