# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0012_auto_20160619_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadoratelefonia',
            options={'permissions': (('list_operadoratelefonia', 'Pode visualizar lista das operadoras de telefonia.'), ('detail_operadoratelefonia', 'Pode visualizar detalhes das operadoras de telefonia.')), 'verbose_name': 'Operadora de Telefonia', 'verbose_name_plural': 'Operadoras de Telefonia'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de Instrução'),
        ),
    ]
