# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0012_auto_20160705_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='telefone',
        ),
    ]
