# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0012_auto_20160627_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='administrador',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Administrador da Área?'),
        ),
    ]
