# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0013_auto_20160619_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'permissions': (('list_pessoa', 'Pode visualizar lista de Pessas.'), ('detail_pessoa', 'Pode visualizar detalhes do Cadastro de Pessoas.')), 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
