# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0013_auto_20160627_0845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operadorareatrabalho',
            unique_together=set([('operador', 'area_trabalho')]),
        ),
    ]
