# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0014_auto_20160619_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefone',
            options={'permissions': (('list_telefone', 'Pode visualizar lista de Telefones.'), ('detail_telefone', 'Pode visualizar detalhes do Cadastro de Telefones.')), 'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
    ]
