# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0014_auto_20160707_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='endereco',
            field=models.CharField(blank=True, default='', help_text='O campo endereço também é um campo de busca. Nele você pode digitar qualquer informação, inclusive digitar o cep para localizar o endereço, e vice-versa!', max_length=254, verbose_name='Endereço'),
        ),
    ]
