# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0014_auto_20160627_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operadorareatrabalho',
            unique_together=set([]),
        ),
    ]
