# Generated by Django 2.2.28 on 2024-06-03 19:29

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0014_visitante_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
