# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0015_auto_20160620_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'permissions': (('list_email', 'Pode visualizar lista de Emails.'), ('detail_email', 'Pode visualizar detalhes do Cadastro de Emails.')), 'verbose_name': 'Email', 'verbose_name_plural': "Email's"},
        ),
    ]
