# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0015_auto_20160627_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentePerfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.dependente',),
        ),
        migrations.CreateModel(
            name='EmailPerfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.email',),
        ),
        migrations.CreateModel(
            name='EnderecoPerfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.endereco',),
        ),
        migrations.CreateModel(
            name='LocalTrabalhoPerfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.localtrabalho',),
        ),
        migrations.CreateModel(
            name='TelefonePerfil',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.telefone',),
        ),
    ]
