# Generated by Django 4.2.16 on 2024-10-03 20:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0015_visita_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tem_filhos',
            field=models.BooleanField(choices=[(None, '---------'), (True, 'Sim'), (False, 'Não')], default=None, null=True, verbose_name='Tem Filhos?'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='proprio',
            field=models.BooleanField(blank=True, choices=[(None, '---------'), (True, 'Sim'), (False, 'Não')], null=True, verbose_name='Próprio?'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
