# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0015_auto_20160710_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Outros observações sobre o Endereço'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='ponto_referencia',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='preferencial',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Preferencial?'),
        ),
    ]
