# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0016_auto_20160710_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Outros observações sobre o Contato'),
        ),
    ]
