# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0016_dependenteperfil_emailperfil_enderecoperfil_localtrabalhoperfil_telefoneperfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependenteperfil',
            options={'verbose_name': 'Dependente do Perfil', 'verbose_name_plural': 'Dependentes do Perfil'},
        ),
        migrations.AlterModelOptions(
            name='emailperfil',
            options={'verbose_name': 'Email do Perfil', 'verbose_name_plural': "Email's do Perfil"},
        ),
        migrations.AlterModelOptions(
            name='enderecoperfil',
            options={'verbose_name': 'Endereço do Perfil', 'verbose_name_plural': 'Endereços do Perfil'},
        ),
        migrations.AlterModelOptions(
            name='localtrabalhoperfil',
            options={'verbose_name': 'Local de Trabalho do Perfil', 'verbose_name_plural': 'Locais de Trabalho do Perfil'},
        ),
        migrations.AlterModelOptions(
            name='telefoneperfil',
            options={'verbose_name': 'Telefone do Perfil', 'verbose_name_plural': 'Telefones do Perfil'},
        ),
    ]
