# Generated by Django 4.2.17 on 2025-01-09 19:24

import cmj.cerimonial.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import sapl.utils
import cmj.utils

class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0016_alter_contato_tem_filhos_alter_telefone_proprio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_paginas', models.IntegerField(default=0, verbose_name='Número de Páginas')),
                ('metadata', models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('arquivo', sapl.utils.PortalFileField(
                    blank=True,
                    null=True,
                    upload_to=cmj.cerimonial.models.anexoprocesso_upload_path,
                    verbose_name='Arquivo Anexo',
                    validators=[cmj.utils.restringe_tipos_de_arquivo_midias],
                    )),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexoprocesso_set', to='cerimonial.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Anexo do Processo',
                'verbose_name_plural': 'Anexos do Processo',
            },
        ),
    ]
