# Generated by Django 4.2.17 on 2025-01-09 19:55

import cmj.cerimonial.models
from django.db import migrations
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0017_anexoprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoprocesso',
            name='arquivo',
            field=sapl.utils.PortalFileField(blank=True, null=True, upload_to=cmj.cerimonial.models.anexoprocesso_upload_path, verbose_name='Arquivo Anexo'),
        ),
    ]
