# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0017_auto_20160627_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='administrador',
        ),
    ]
