# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160707_1527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0017_contato_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuntoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=254, verbose_name='Nome / Descrição')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assuntoprocesso_set', to='core.AreaTrabalho', verbose_name='Área de Trabalho')),
            ],
            options={
                'verbose_name': 'Assunto de Processo',
                'verbose_name_plural': 'Assuntos de Processos',
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=254, verbose_name='Nome / Descrição')),
            ],
            options={
                'verbose_name': 'Classificacao de Processo',
                'verbose_name_plural': 'Classificações de Processos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('titulo', models.CharField(max_length=254, verbose_name='Nome')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição do Processo')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Outros observações sobre o Processo')),
                ('solucao', models.TextField(blank=True, default='', verbose_name='Solução do Processo')),
                ('importancia', models.CharField(blank=True, choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta'), ('C', 'Crítica')], max_length=1, verbose_name='Importância')),
                ('assuntos', models.ManyToManyField(related_name='processo_set', to='cerimonial.AssuntoProcesso', verbose_name='Assuntos')),
                ('classificacoes', models.ManyToManyField(related_name='processo_set', to='cerimonial.ClassificacaoProcesso', verbose_name='Classificações')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processo_set', to='cerimonial.Contato', verbose_name='Contato')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('responsavel', models.ManyToManyField(related_name='processo_set', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='StatusProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=254, verbose_name='Nome / Descrição')),
            ],
            options={
                'verbose_name': 'Status de Processo',
                'verbose_name_plural': 'Status de Processos',
            },
        ),
        migrations.CreateModel(
            name='TopicoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=254, verbose_name='Nome / Descrição')),
            ],
            options={
                'verbose_name': 'Tópico de Processo',
                'verbose_name_plural': 'Tópicos de Processos',
            },
        ),
        migrations.DeleteModel(
            name='StatusVisita',
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_set', to='cerimonial.StatusProcesso', verbose_name='Status do Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='topicos',
            field=models.ManyToManyField(related_name='processo_set', to='cerimonial.TopicoProcesso', verbose_name='Tópicos'),
        ),
    ]
