# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('cerimonial', '0018_remove_operadorareatrabalho_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='grupos_associados',
            field=models.ManyToManyField(related_name='operadores_areatrabalho_set', to='auth.Group', verbose_name='Grupos Associados'),
        ),
    ]
