# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0020_auto_20160710_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='responsaveis',
        ),
        migrations.AlterField(
            model_name='processo',
            name='classificacoes',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.ClassificacaoProcesso', verbose_name='Classificações'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data',
            field=models.DateField(verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_set', to='cerimonial.StatusProcesso', verbose_name='Status do Processo'),
        ),
    ]
