# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0021_auto_20160711_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.Contato', verbose_name='Contato do Processo'),
        ),
    ]
