# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0022_processo_contatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoContato',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cerimonial.processo',),
        ),
        migrations.AlterField(
            model_name='processo',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.Contato', verbose_name='Contatos Interessados do Processo'),
        ),
    ]
