# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0023_auto_20160711_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processocontato',
            options={'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AddField(
            model_name='telefone',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ponto_referencia',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Pontos de Referência'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Ao definir um cargo e função aqui, o Cargo/Função será desconsiderado ao gerar impressos!', max_length=254, verbose_name='Cargo/Função'),
        ),
    ]
