# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0024_auto_20160712_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='assuntoprocesso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 12, 21, 38, 4, 509663, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assuntoprocesso',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 12, 21, 38, 9, 485734, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assuntoprocesso',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assuntoprocesso',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependente',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependente',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 12, 21, 38, 52, 190207, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 12, 21, 38, 56, 526410, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filiacaopartidaria',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cerimonial.Parentesco', verbose_name='Parentesco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Ao definir um cargo e função aqui, oCargo/Função preenchido na aba "Dados Básicos", será desconsiderado ao gerar impressos!', max_length=254, verbose_name='Cargo/Função'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.Contato', verbose_name='Contatos Interessados no Processo'),
        ),
    ]
