# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0025_auto_20160712_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='assuntos',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.AssuntoProcesso', verbose_name='Assuntos'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='topicos',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.TopicoProcesso', verbose_name='Tópicos'),
        ),
    ]
