# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0027_auto_20160713_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['nome'], 'permissions': (('print_impressoenderecamento', 'Pode Imprimir Impressos de Endereçamento'),), 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
