# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_impressoenderecamento_rotate'),
        ('cerimonial', '0029_remove_endereco_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='core.Bairro', verbose_name='Bairro'),
        ),
    ]
