# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models

import cmj.utils_files
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloco",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome do Bloco")),
                (
                    "data_criacao",
                    models.DateField(null=True, verbose_name="Data Criação"),
                ),
                (
                    "data_extincao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Dissolução"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Bloco Parlamentar",
                "verbose_name_plural": "Blocos Parlamentares",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CargoBancada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_cargo",
                    models.CharField(max_length=80, verbose_name="Cargo de Bancada"),
                ),
                (
                    "cargo_unico",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Cargo Único ?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo de Bancada",
                "verbose_name_plural": "Cargos de Bancada",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CargoBloco",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome do Cargo")),
                (
                    "unico",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Cargo Único",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Cargo de Bloco",
                "verbose_name_plural": "Cargos de Bloco",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CargoMesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Cargo na Mesa"),
                ),
                (
                    "unico",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Cargo Único",
                    ),
                ),
                (
                    "presidente",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Cargo de Presidente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo na Mesa",
                "verbose_name_plural": "Cargos na Mesa",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Legislatura",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                ("data_fim", models.DateField(verbose_name="Data Fim")),
                ("data_eleicao", models.DateField(verbose_name="Data Eleição")),
            ],
            options={
                "verbose_name": "Legislatura",
                "verbose_name_plural": "Legislaturas",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="NivelInstrucao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Nível de Instrução"),
                ),
            ],
            options={
                "verbose_name": "Nível Instrução",
                "verbose_name_plural": "Níveis Instrução",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("sigla", models.CharField(max_length=100, verbose_name="Sigla")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "data_criacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Criação"
                    ),
                ),
                (
                    "data_extincao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Extinção"
                    ),
                ),
                (
                    "logo_partido",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=sapl.parlamentares.models.logo_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_img],
                        verbose_name="Logo Partido",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ["sigla", "nome"],
            },
        ),
        migrations.CreateModel(
            name="SituacaoMilitar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Situação Militar"),
                ),
            ],
            options={
                "verbose_name": "Tipo Situação Militar",
                "verbose_name_plural": "Tipos Situações Militares",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="TipoAfastamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[("A", "Afastamento"), ("F", "Fim de Mandato")],
                        default="F",
                        max_length=1,
                        verbose_name="Indicador",
                    ),
                ),
                (
                    "dispositivo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Dispositivo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Afastamento",
                "verbose_name_plural": "Tipos de Afastamento",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="TipoDependente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Dependente",
                "verbose_name_plural": "Tipos de Dependente",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Coligacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "numero_votos",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Nº Votos Recebidos (Coligação)",
                    ),
                ),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coligação",
                "verbose_name_plural": "Coligações",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Parlamentar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=50, verbose_name="Nome Completo"),
                ),
                (
                    "nome_parlamentar",
                    models.CharField(max_length=50, verbose_name="Nome Parlamentar"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Nascimento"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="C.P.F"),
                ),
                (
                    "rg",
                    models.CharField(blank=True, max_length=15, verbose_name="R.G."),
                ),
                (
                    "titulo_eleitor",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Título de Eleitor"
                    ),
                ),
                (
                    "numero_gab_parlamentar",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Nº Gabinete"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=50, verbose_name="Fax"),
                ),
                (
                    "endereco_residencia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Endereço Residencial"
                    ),
                ),
                (
                    "municipio_residencia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Município"
                    ),
                ),
                (
                    "uf_residencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PR", "Paraná"),
                            ("PB", "Paraíba"),
                            ("PA", "Pará"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SE", "Sergipe"),
                            ("SP", "São Paulo"),
                            ("TO", "Tocantins"),
                            ("EX", "Exterior"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "cep_residencia",
                    models.CharField(blank=True, max_length=9, verbose_name="CEP"),
                ),
                (
                    "telefone_residencia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone Residencial"
                    ),
                ),
                (
                    "fax_residencia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Fax Residencial"
                    ),
                ),
                (
                    "endereco_web",
                    models.URLField(
                        blank=True, max_length=100, verbose_name="HomePage"
                    ),
                ),
                (
                    "profissao",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Profissão"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, verbose_name="E-mail"
                    ),
                ),
                (
                    "locais_atuacao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Locais de Atuação"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        db_index=True,
                        default=False,
                        verbose_name="Ativo na Casa?",
                    ),
                ),
                (
                    "equipe",
                    models.TextField(
                        blank=True, default="", verbose_name="Equipe do Parlamentar"
                    ),
                ),
                ("biografia", models.TextField(blank=True, verbose_name="Biografia")),
                (
                    "fotografia",
                    sapl.utils.PortalImageCropField(
                        blank=True,
                        null=True,
                        upload_to=sapl.parlamentares.models.foto_upload_path,
                        verbose_name="Fotografia",
                    ),
                ),
                (
                    "fotografia_cropping",
                    image_cropping.fields.ImageRatioField(
                        "fotografia",
                        "128x128",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text="A configuração do Avatar é possível após a atualização da fotografia.",
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "capa",
                    image_cropping.fields.ImageCropField(
                        blank=True,
                        null=True,
                        upload_to=sapl.parlamentares.models.capa_upload_path,
                        verbose_name="Imagem de Capa",
                    ),
                ),
                (
                    "capa_cropping",
                    image_cropping.fields.ImageRatioField(
                        "capa",
                        "280x105",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text="A configuração da capa é possível após a atualização.",
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Capa",
                    ),
                ),
                (
                    "nivel_instrucao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.nivelinstrucao",
                        verbose_name="Nível Instrução",
                    ),
                ),
                (
                    "situacao_militar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.situacaomilitar",
                        verbose_name="Situação Militar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parlamentar",
                "verbose_name_plural": "Parlamentares",
                "ordering": ["nome_parlamentar"],
            },
        ),
        migrations.CreateModel(
            name="Mandato",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_causa_fim_mandato",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "data_inicio_mandato",
                    models.DateField(null=True, verbose_name="Início do Mandato"),
                ),
                (
                    "data_fim_mandato",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do Mandato"
                    ),
                ),
                (
                    "votos_recebidos",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Votos Recebidos (Mandato)"
                    ),
                ),
                (
                    "data_expedicao_diploma",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expedição do Diploma"
                    ),
                ),
                (
                    "titular",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        db_index=True,
                        default=True,
                        verbose_name="Parlamentar Titular",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "coligacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.coligacao",
                        verbose_name="Coligação",
                    ),
                ),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "tipo_afastamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.tipoafastamento",
                        verbose_name="Tipo de Afastamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandato",
                "verbose_name_plural": "Mandatos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Frente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=80, verbose_name="Nome da Frente"),
                ),
                ("data_criacao", models.DateField(verbose_name="Data Criação")),
                (
                    "data_extincao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Dissolução"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "parlamentares",
                    models.ManyToManyField(
                        blank=True,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentares",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frente Parlamentar",
                "verbose_name_plural": "Frentes Parlamentares",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CargoBlocoPartido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                (
                    "bloco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargoblocopartido_set",
                        to="parlamentares.bloco",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.cargobloco",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculo bloco parlamentar",
                "verbose_name_plural": "Vinculos bloco parlamentar",
                "ordering": ["data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoPartido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("sigla", models.CharField(max_length=9, verbose_name="Sigla")),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("inicio_historico", models.DateField(verbose_name="Data Alteração")),
                ("fim_historico", models.DateField(verbose_name="Data Alteração")),
                (
                    "logo_partido",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=sapl.parlamentares.models.logo_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_img],
                        verbose_name="Logo Partido",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.partido",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Filiacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data Filiação")),
                (
                    "data_desfiliacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Desfiliação"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filiacao_set",
                        to="base.autor",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filiacao_set",
                        to="parlamentares.partido",
                        verbose_name="Partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filiação",
                "verbose_name_plural": "Filiações",
                "ordering": ("parlamentar", "-data", "-data_desfiliacao"),
            },
        ),
        migrations.CreateModel(
            name="ComposicaoColigacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coligacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.coligacao",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.partido",
                        verbose_name="Partidos da Coligação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composição Coligação",
                "verbose_name_plural": "Composição Coligações",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="bloco",
            name="partidos",
            field=models.ManyToManyField(
                blank=True, to="parlamentares.partido", verbose_name="Partidos"
            ),
        ),
        migrations.CreateModel(
            name="Bancada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=80, verbose_name="Nome da Bancada"),
                ),
                (
                    "data_criacao",
                    models.DateField(null=True, verbose_name="Data Criação"),
                ),
                (
                    "data_extincao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Extinção"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.partido",
                        verbose_name="Partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bancada Partidária",
                "verbose_name_plural": "Bancadas Partidárias",
                "db_table": "parlamentares_bancada",
                "ordering": (
                    "-legislatura__numero",
                    "-data_extincao",
                    "data_criacao",
                    "partido__nome",
                ),
            },
        ),
        migrations.CreateModel(
            name="SessaoLegislativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("O", "Ordinária"), ("E", "Extraordinária")],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                ("data_fim", models.DateField(verbose_name="Data Fim")),
                (
                    "data_inicio_intervalo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Início Intervalo"
                    ),
                ),
                (
                    "data_fim_intervalo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim Intervalo"
                    ),
                ),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão Legislativa",
                "verbose_name_plural": "Sessões Legislativas",
                "ordering": ["-data_inicio", "-data_fim"],
            },
        ),
        migrations.CreateModel(
            name="ComposicaoMesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.cargomesa",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "sessao_legislativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.sessaolegislativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocupação de cargo na Mesa",
                "verbose_name_plural": "Ocupações de cargo na Mesa",
                "ordering": ["sessao_legislativa__data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AfastamentoParlamentar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(null=True, verbose_name="Início do Afastamento"),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do Afastamento"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "mandato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.mandato",
                        verbose_name="Mandato",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "tipo_afastamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.tipoafastamento",
                        verbose_name="Tipo de Afastamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Afastamento",
                "verbose_name_plural": "Afastamentos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Dependente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Nascimento"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, max_length=15, verbose_name="RG")),
                (
                    "titulo_eleitor",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Nº Título Eleitor"
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.tipodependente",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependente",
                "verbose_name_plural": "Dependentes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Votante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True, max_length=30, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parlamentar",
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votante",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário Votante",
                "verbose_name_plural": "Usuários Votantes",
                "ordering": ["id"],
                "permissions": (("can_vote", "Can Vote"),),
            },
        ),
    ]
