# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-23 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0035_merge_20190802_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlamentar',
            old_name='cropping',
            new_name='fotografia_cropping',
        ),
    ]
