# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-23 13:27
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0036_auto_20191023_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlamentar',
            name='capa',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=sapl.parlamentares.models.capa_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_img], verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='parlamentar',
            name='capa_cropping',
            field=image_cropping.fields.ImageRatioField('fotografia', '283x105', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='A configuração da capa é possível após a atualização.', hide_image_field=False, size_warning=True, verbose_name='Capa'),
        ),
    ]
