# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-23 13:43
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0037_auto_20191023_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='capa_cropping',
            field=image_cropping.fields.ImageRatioField('capa', '283x105', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='A configuração da capa é possível após a atualização.', hide_image_field=False, size_warning=True, verbose_name='Capa'),
        ),
    ]
