# Generated by Django 2.2.12 on 2020-06-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0040_auto_20200505_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancada',
            options={'ordering': ('-legislatura__numero',), 'verbose_name': 'Bancada Partidária', 'verbose_name_plural': 'Bancadas Partidárias'},
        ),
        migrations.AlterField(
            model_name='cargoblocopartido',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargoblocopartido_set', to='parlamentares.Bloco'),
        ),
        migrations.AlterModelTable(
            name='cargobancada',
            table=None,
        ),
    ]
