# Generated by Django 2.2.15 on 2020-08-19 12:36

from django.db import migrations
import image_cropping.fields
import sapl.parlamentares.models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0041_auto_20200602_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='capa',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=sapl.parlamentares.models.capa_upload_path, verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='fotografia',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=sapl.parlamentares.models.foto_upload_path, verbose_name='Fotografia'),
        ),
    ]
