# Generated by Django 2.2.16 on 2020-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0042_auto_20200819_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='sigla',
            field=models.CharField(max_length=100, verbose_name='Sigla'),
        ),
    ]
