# Generated by Django 2.2.28 on 2024-04-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0044_auto_20240325_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancada',
            options={'ordering': ('-legislatura__numero', '-data_extincao', 'data_criacao', 'partido__nome'), 'verbose_name': 'Bancada Partidária', 'verbose_name_plural': 'Bancadas Partidárias'},
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiacao_set', to='parlamentares.Partido', verbose_name='Partido'),
        ),
    ]
