# Generated by Django 4.2.16 on 2024-10-19 00:01

from django.db import migrations
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0046_alter_historicopartido_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='fotografia',
            field=sapl.utils.PortalImageCropField(blank=True, null=True, upload_to=sapl.parlamentares.models.foto_upload_path, verbose_name='Fotografia'),
        ),
    ]
