# Generated by Django 4.2.16 on 2024-11-05 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parlamentares', '0047_alter_parlamentar_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votante', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
