# Generated by Django 4.2.19 on 2025-03-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0048_alter_votante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlamentar',
            name='equipe',
            field=models.TextField(blank=True, default='', verbose_name='Equipe do Parlamentar'),
        ),
    ]
