# Generated by Django 4.2.19 on 2025-04-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0049_parlamentar_equipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composicaomesa',
            options={'ordering': ['sessao_legislativa__data_inicio'], 'verbose_name': 'Ocupação de cargo na Mesa', 'verbose_name_plural': 'Ocupações de cargo na Mesa'},
        ),
    ]
