# Generated by Django 5.2.1 on 2025-06-12 11:53

import django.db.models.deletion
from django.db import migrations, models


def vincula_autor_parlamentar(apps, schema_editor):
    Filiacao = apps.get_model('parlamentares', 'Filiacao')
    for filiacao in Filiacao.objects.all():
        if filiacao.parlamentar and filiacao.parlamentar.autor.exists():
            filiacao.autor = filiacao.parlamentar.autor.first()
        filiacao.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_autor_operadores'),
        ('parlamentares', '0050_alter_composicaomesa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiacao',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filiacao_set', to='base.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parlamentares.parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.RunPython(vincula_autor_parlamentar)
    ]

