# Generated by Django 5.2.3 on 2025-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0051_filiacao_autor_alter_filiacao_parlamentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargomesa',
            name='presidente',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Cargo de Presidente'),
        ),
    ]
