# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.mixins
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estatisticas_acesso_normas",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")],
                        default="N",
                        max_length=1,
                        verbose_name="Estatísticas de acesso a normas",
                    ),
                ),
                (
                    "sequencia_numeracao_proposicao",
                    models.CharField(
                        choices=[
                            ("A", "Sequencial por ano para cada autor"),
                            ("B", "Sequencial por ano indepententemente do autor"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Sequência de numeração de proposições",
                    ),
                ),
                (
                    "sequencia_numeracao_protocolo",
                    models.CharField(
                        choices=[
                            ("A", "Sequencial por ano"),
                            ("L", "Sequencial por legislatura"),
                            ("U", "Sequencial único"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Sequência de numeração de protocolos",
                    ),
                ),
                (
                    "esfera_federacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Municipal"),
                            ("E", "Estadual"),
                            ("F", "Federal"),
                        ],
                        default="",
                        max_length=1,
                        verbose_name="Esfera Federação",
                    ),
                ),
                (
                    "texto_articulado_proposicao",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Usar Textos Articulados para Proposições",
                    ),
                ),
                (
                    "texto_articulado_materia",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Usar Textos Articulados para Matérias",
                    ),
                ),
                (
                    "texto_articulado_norma",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Usar Textos Articulados para Normas",
                    ),
                ),
                (
                    "proposicao_incorporacao_obrigatoria",
                    models.CharField(
                        choices=[
                            ("O", "Sempre Gerar Protocolo"),
                            ("C", "Perguntar se é pra gerar protocolo ao incorporar"),
                            ("N", "Nunca Protocolar ao incorporar uma proposição"),
                        ],
                        default="O",
                        max_length=1,
                        verbose_name="Regra de incorporação de proposições e protocolo",
                    ),
                ),
                (
                    "assinatura_ata",
                    models.CharField(
                        choices=[
                            ("M", "Mesa Diretora da Sessão"),
                            ("P", "Apenas o Presidente da Sessão"),
                            ("T", "Todos os Parlamentares Presentes na Sessão"),
                        ],
                        default="T",
                        max_length=1,
                        verbose_name="Quem deve assina a ata",
                    ),
                ),
                (
                    "receber_recibo_proposicao",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Protocolar proposição somente com recibo?",
                    ),
                ),
                (
                    "protocolo_manual",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Informar data e hora de protocolo?",
                    ),
                ),
                (
                    "escolher_numero_materia_proposicao",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Indicar número da matéria a ser gerada na proposição?",
                    ),
                ),
                (
                    "tramitacao_materia",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Tramitar matérias anexadas junto com as matérias principais?",
                    ),
                ),
                (
                    "tramitacao_documento",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Tramitar documentos anexados junto com os documentos principais?",
                    ),
                ),
                (
                    "mostrar_brasao_painel",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar brasão da Casa no painel?"
                    ),
                ),
                (
                    "mostrar_voto",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Exibir voto do Parlamentar antes de encerrar a votação?",
                    ),
                ),
                (
                    "cronometro_discurso",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Cronômetro do Discurso"
                    ),
                ),
                (
                    "cronometro_aparte",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Cronômetro do Aparte"
                    ),
                ),
                (
                    "cronometro_ordem",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Cronômetro da Ordem"
                    ),
                ),
                (
                    "cronometro_consideracoes",
                    models.DurationField(
                        blank=True,
                        null=True,
                        verbose_name="Cronômetro de Considerações Finais",
                    ),
                ),
                (
                    "disabled",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="URLs Desativadas (urls completas / relativas / regex ignorecase ) - YAML Format",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurações da Aplicação",
                "verbose_name_plural": "Configurações da Aplicação",
                "ordering": ("-id",),
                "permissions": (
                    ("menu_sistemas", "Renderizar Menu Sistemas"),
                    ("view_tabelas_auxiliares", "Visualizar Tabelas Auxiliares"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CasaLegislativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=100, verbose_name="Codigo"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("sigla", models.CharField(max_length=100, verbose_name="Sigla")),
                ("endereco", models.CharField(max_length=100, verbose_name="Endereço")),
                ("cep", models.CharField(max_length=100, verbose_name="CEP")),
                (
                    "municipio",
                    models.CharField(max_length=50, verbose_name="Município"),
                ),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PR", "Paraná"),
                            ("PB", "Paraíba"),
                            ("PA", "Pará"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SE", "Sergipe"),
                            ("SP", "São Paulo"),
                            ("TO", "Tocantins"),
                            ("EX", "Exterior"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telefone"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=100, verbose_name="Fax"),
                ),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True,
                        upload_to="sapl/public/casa/logotipo/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "endereco_web",
                    models.URLField(
                        blank=True, max_length=100, verbose_name="HomePage"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, verbose_name="E-mail"
                    ),
                ),
                (
                    "informacao_geral",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="Informação Geral"
                    ),
                ),
            ],
            options={
                "verbose_name": "Casa Legislativa",
                "verbose_name_plural": "Casa Legislativa",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoAutor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Obs: Não crie tipos de autores semelhante aos tipos fixos. ",
                        max_length=50,
                        verbose_name="Descrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Autor",
                "verbose_name_plural": "Tipos de Autor",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nome do Autor"
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=50)),
                (
                    "sign_compression",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Assinatura com compressão",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadado",
                "verbose_name_plural": "Metadados",
                "ordering": ["id"],
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OperadorAutor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "operador_principal",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Operador Principal do Autor",
                    ),
                ),
                (
                    "enviar_email",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Enviar emails de notificação a este usuário",
                    ),
                ),
                (
                    "visibilidade_restrita",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Ver apenas proposições criadas por este usuário",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operadorautor_set",
                        to="base.autor",
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operador do Autor",
                "verbose_name_plural": "Operadores do Autor",
                "ordering": ["id"],
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
    ]
