# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operadorautor",
            name="modifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modifier",
            ),
        ),
        migrations.AddField(
            model_name="operadorautor",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="operadorautor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operadorautor_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operador do Autor",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="operadores",
            field=models.ManyToManyField(
                related_name="autor_set",
                through="base.OperadorAutor",
                through_fields=("autor", "user"),
                to=settings.AUTH_USER_MODEL,
                verbose_name="Operadores",
            ),
        ),
        migrations.AddField(
            model_name="tipoautor",
            name="content_type",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
                verbose_name="Modelagem no SAPL",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="base.tipoautor",
                verbose_name="Tipo do Autor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metadata",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="operadorautor",
            unique_together={("user", "autor")},
        ),
        migrations.AlterUniqueTogether(
            name="autor",
            unique_together={("content_type", "object_id")},
        ),
    ]
