# Generated by Django 5.2.14 on 2026-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="certificado_cn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Common Name (CN) do certificado X.509 utilizado para assinar documentos.",
                max_length=200,
                verbose_name="CN do certificado digital",
            ),
        ),
    ]
