# Generated by Django 5.2.15 on 2026-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfig",
            name="tramitacao_origem_fixa",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=True,
                help_text="Ao utilizar a opção NÂO, você compreende que os controles de origem e destino das tramitações são anulados, podendo seu operador registrar quaisquer origem e destino para as tramitações. Se você colocar Não, fizer tramitações aleatórias e voltar para SIM, o destino da tramitação mais recente será utilizado para a origem de uma nova inserção!",
                verbose_name="Fixar origem de novas tramitações como sendo a tramitação de destino da última tramitação?",
            ),
        ),
    ]
