# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_appconfig_documentos_administrativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
