# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-07 03:52
from __future__ import unicode_literals

import cmj.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0041_remove_autor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadorautor_set', to='base.Autor', verbose_name='Autor')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadorautor_set', to=settings.AUTH_USER_MODEL, verbose_name='Operador do Autor')),
            ],
            options={
                'verbose_name': 'Operador do Autor',
                'verbose_name_plural': 'Operadores do Autor',
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.AddField(
            model_name='autor',
            name='operadores',
            field=models.ManyToManyField(related_name='autor_set', through='base.OperadorAutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='operadorautor',
            unique_together=set([('user', 'autor')]),
        ),
    ]
