# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-07 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200407_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadorautor',
            name='enviar_email',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Enviar emails de notificação a este usuário'),
        ),
        migrations.AddField(
            model_name='operadorautor',
            name='operador_principal',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Operador Principal do Autor'),
        ),
    ]
