# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20200407_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='operadores',
            field=models.ManyToManyField(related_name='autor_set', through='base.OperadorAutor', to=settings.AUTH_USER_MODEL, verbose_name='Operadores'),
        ),
    ]
