# Generated by Django 2.2.28 on 2023-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_aparte',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro do Aparte'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_consideracoes',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro de Considerações Finais'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_discurso',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro do Discurso'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_ordem',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro da Ordem'),
        ),
    ]
