# Generated by Django 2.2.28 on 2023-12-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20231214_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='mostrar_voto',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Exibir voto do Parlamentar antes de encerrar a votação?'),
        ),
    ]
