# Generated by Django 2.2.28 on 2024-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20240325_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='disabled',
            field=models.TextField(blank=True, default='', verbose_name='URLs Desativadas (urls completas / relativas / regex )'),
        ),
    ]
