# Generated by Django 2.2.28 on 2024-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_appconfig_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='disabled',
            field=models.TextField(blank=True, default='', verbose_name='URLs Desativadas (urls completas / relativas / regex ignorecase ) - YAML Format'),
        ),
    ]
