# Generated by Django 4.2.16 on 2024-10-03 20:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20240423_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
