# Generated by Django 4.2.20 on 2025-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_metadata_created_metadata_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='sign_compression',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Assinatura com compressão'),
        ),
    ]
