# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_autor_sign_compression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='operadores',
            field=models.ManyToManyField(related_name='autor_set', through='base.OperadorAutor', through_fields=('autor', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Operadores'),
        ),
    ]
