# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import cmj.utils_files
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0002_initial"),
        ("comissoes", "0002_initial"),
        ("compilacao", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("parlamentares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaEmTramitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "em_tramitacao",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Em Tramitação ?",
                    ),
                ),
            ],
            options={
                "db_table": "materia_materiaemtramitacao",
                "ordering": ("-id",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnaliseSimilaridade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analise",
                    models.TextField(
                        blank=True, default="", verbose_name="Análise de Similaridade"
                    ),
                ),
                (
                    "data_analise",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Análise"
                    ),
                ),
                (
                    "ia_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Nome do Algoritmo de IA",
                    ),
                ),
                (
                    "qtd_assuntos_comuns",
                    models.SmallIntegerField(
                        default=0, verbose_name="Qtd de Assuntos Comuns"
                    ),
                ),
                (
                    "similaridade",
                    models.SmallIntegerField(default=-1, verbose_name="Similaridade"),
                ),
            ],
            options={
                "verbose_name": "Análise de Similaridade",
                "verbose_name_plural": "Análises de Similaridade",
                "ordering": ["-data_analise", "-qtd_assuntos_comuns"],
            },
        ),
        migrations.CreateModel(
            name="Anexada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_anexacao", models.DateField(verbose_name="Data Anexação")),
                (
                    "data_desanexacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Desanexação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexada",
                "verbose_name_plural": "Anexadas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AssuntoMateria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=50, verbose_name="Assunto")),
                (
                    "dispositivo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Descrição do Dispositivo Legal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assunto de Matéria",
                "verbose_name_plural": "Assuntos de Matéria",
                "ordering": ["assunto"],
            },
        ),
        migrations.CreateModel(
            name="Orgao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60, verbose_name="Nome")),
                ("sigla", models.CharField(max_length=10, verbose_name="Sigla")),
                (
                    "unidade_deliberativa",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Unidade Deliberativa",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Endereço"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Órgão",
                "verbose_name_plural": "Órgãos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=10, verbose_name="Sigla")),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Origem",
                "verbose_name_plural": "Origens",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RegimeTramitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                (
                    "sequencia_regimental",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="A sequência regimental diz respeito ao que define o regimento da Casa Legislativa sobre qual a ordem de entrada das proposições nas Sessões Plenárias.",
                        verbose_name="Sequência Regimental",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regime de Tramitação",
                "verbose_name_plural": "Regimes de Tramitação",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StatusTramitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=10, verbose_name="Sigla")),
                (
                    "descricao",
                    models.CharField(max_length=60, verbose_name="Descrição"),
                ),
                (
                    "indicador",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Fim"), ("R", "Retorno")],
                        max_length=1,
                        verbose_name="Indicador da Tramitação",
                    ),
                ),
                (
                    "css_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Classe CSS para estilização do status na listagem. Exemplo: "badge badge-success"',
                        max_length=40,
                        verbose_name="Classe CSS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status de Tramitação",
                "verbose_name_plural": "Status de Tramitação",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Tipo Documento"),
                ),
                (
                    "limite_por_autor_tramitando",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Limitar Protocolo por Autor",
                    ),
                ),
                (
                    "limite_minimo_coletivo",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Não Impõe Limites de Protocolo acima deste valor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="TipoFimRelatoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Tipo Fim Relatoria"),
                ),
            ],
            options={
                "verbose_name": "Tipo Fim de Relatoria",
                "verbose_name_plural": "Tipos Fim de Relatoria",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoMateriaLegislativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=5, verbose_name="Sigla")),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição "),
                ),
                ("num_automatica", models.BooleanField(default=False)),
                (
                    "quorum_minimo_votacao",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "limite_por_autor_tramitando",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Limitar Protocolo por Autor",
                    ),
                ),
                (
                    "limite_minimo_coletivo",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Não Impõe Limites de Protocolo acima deste valor",
                    ),
                ),
                (
                    "nivel_agrupamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Nível 1"),
                            ("2", "Nível 2"),
                            ("3", "Nível 3"),
                            ("4", "Nível 4"),
                            ("5", "Nível 5"),
                            ("6", "Nível 6"),
                            ("7", "Nível 7"),
                            ("8", "Nível 8"),
                            ("9", "Nível 9"),
                        ],
                        max_length=1,
                        verbose_name="Nível de Agrupamento",
                    ),
                ),
                (
                    "sequencia_numeracao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Sequencial por ano"),
                            ("L", "Sequencial por legislatura"),
                            ("U", "Sequencial único"),
                        ],
                        max_length=1,
                        verbose_name="Sequência de numeração",
                    ),
                ),
                (
                    "sequencia_regimental",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="A sequência regimental diz respeito ao que define o regimento da Casa Legislativa sobre qual a ordem de entrada das proposições nas Sessões Plenárias.",
                        verbose_name="Sequência Regimental",
                    ),
                ),
                (
                    "turnos_aprovacao",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Turnos para aprovação."
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, verbose_name="Prompt para Análise de IA."
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Matéria Legislativa",
                "verbose_name_plural": "Tipos de Matérias Legislativas",
                "ordering": ["sequencia_regimental", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="Autoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primeiro_autor",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Primeiro Autor",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.autor",
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autoria",
                "verbose_name_plural": "Autorias",
                "ordering": ("-primeiro_autor", "autor__nome"),
            },
        ),
        migrations.CreateModel(
            name="MateriaAssunto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.assuntomateria",
                        verbose_name="Assunto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relação Matéria - Assunto",
                "verbose_name_plural": "Relações Matéria - Assunto",
                "ordering": ["assunto__assunto"],
            },
        ),
        migrations.CreateModel(
            name="MateriaLegislativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "ano",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2027, 2027),
                            (2026, 2026),
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                            (1959, 1959),
                            (1958, 1958),
                            (1957, 1957),
                            (1956, 1956),
                            (1955, 1955),
                            (1954, 1954),
                            (1953, 1953),
                            (1952, 1952),
                            (1951, 1951),
                            (1950, 1950),
                            (1949, 1949),
                            (1948, 1948),
                            (1947, 1947),
                            (1946, 1946),
                            (1945, 1945),
                            (1944, 1944),
                            (1943, 1943),
                            (1942, 1942),
                            (1941, 1941),
                            (1940, 1940),
                            (1939, 1939),
                            (1938, 1938),
                            (1937, 1937),
                            (1936, 1936),
                            (1935, 1935),
                            (1934, 1934),
                            (1933, 1933),
                            (1932, 1932),
                            (1931, 1931),
                            (1930, 1930),
                            (1929, 1929),
                            (1928, 1928),
                            (1927, 1927),
                            (1926, 1926),
                            (1925, 1925),
                            (1924, 1924),
                            (1923, 1923),
                            (1922, 1922),
                            (1921, 1921),
                            (1920, 1920),
                            (1919, 1919),
                            (1918, 1918),
                            (1917, 1917),
                            (1916, 1916),
                            (1915, 1915),
                            (1914, 1914),
                            (1913, 1913),
                            (1912, 1912),
                            (1911, 1911),
                            (1910, 1910),
                            (1909, 1909),
                            (1908, 1908),
                            (1907, 1907),
                            (1906, 1906),
                            (1905, 1905),
                            (1904, 1904),
                            (1903, 1903),
                            (1902, 1902),
                            (1901, 1901),
                            (1900, 1900),
                            (1899, 1899),
                            (1898, 1898),
                            (1897, 1897),
                            (1896, 1896),
                            (1895, 1895),
                            (1894, 1894),
                            (1893, 1893),
                            (1892, 1892),
                            (1891, 1891),
                            (1890, 1890),
                        ],
                        verbose_name="Ano",
                    ),
                ),
                (
                    "numero_protocolo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número do Protocolo"
                    ),
                ),
                (
                    "data_apresentacao",
                    models.DateField(verbose_name="Data de Apresentação"),
                ),
                (
                    "tipo_apresentacao",
                    models.CharField(
                        blank=True,
                        choices=[("O", "Oral"), ("E", "Escrita")],
                        max_length=1,
                        verbose_name="Tipo de Apresentação",
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "numero_origem_externa",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "ano_origem_externa",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (2027, 2027),
                            (2026, 2026),
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                            (1959, 1959),
                            (1958, 1958),
                            (1957, 1957),
                            (1956, 1956),
                            (1955, 1955),
                            (1954, 1954),
                            (1953, 1953),
                            (1952, 1952),
                            (1951, 1951),
                            (1950, 1950),
                            (1949, 1949),
                            (1948, 1948),
                            (1947, 1947),
                            (1946, 1946),
                            (1945, 1945),
                            (1944, 1944),
                            (1943, 1943),
                            (1942, 1942),
                            (1941, 1941),
                            (1940, 1940),
                            (1939, 1939),
                            (1938, 1938),
                            (1937, 1937),
                            (1936, 1936),
                            (1935, 1935),
                            (1934, 1934),
                            (1933, 1933),
                            (1932, 1932),
                            (1931, 1931),
                            (1930, 1930),
                            (1929, 1929),
                            (1928, 1928),
                            (1927, 1927),
                            (1926, 1926),
                            (1925, 1925),
                            (1924, 1924),
                            (1923, 1923),
                            (1922, 1922),
                            (1921, 1921),
                            (1920, 1920),
                            (1919, 1919),
                            (1918, 1918),
                            (1917, 1917),
                            (1916, 1916),
                            (1915, 1915),
                            (1914, 1914),
                            (1913, 1913),
                            (1912, 1912),
                            (1911, 1911),
                            (1910, 1910),
                            (1909, 1909),
                            (1908, 1908),
                            (1907, 1907),
                            (1906, 1906),
                            (1905, 1905),
                            (1904, 1904),
                            (1903, 1903),
                            (1902, 1902),
                            (1901, 1901),
                            (1900, 1900),
                            (1899, 1899),
                            (1898, 1898),
                            (1897, 1897),
                            (1896, 1896),
                            (1895, 1895),
                            (1894, 1894),
                            (1893, 1893),
                            (1892, 1892),
                            (1891, 1891),
                            (1890, 1890),
                        ],
                        null=True,
                        verbose_name="Ano",
                    ),
                ),
                (
                    "data_origem_externa",
                    models.DateField(blank=True, null=True, verbose_name="Data"),
                ),
                (
                    "apelido",
                    models.CharField(blank=True, max_length=50, verbose_name="Apelido"),
                ),
                (
                    "dias_prazo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dias Prazo"
                    ),
                ),
                (
                    "data_fim_prazo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim Prazo"
                    ),
                ),
                (
                    "em_tramitacao",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Em Tramitação?",
                    ),
                ),
                (
                    "polemica",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Matéria Polêmica?"
                    ),
                ),
                (
                    "objeto",
                    models.CharField(blank=True, max_length=150, verbose_name="Objeto"),
                ),
                (
                    "complementar",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="É Complementar?"
                    ),
                ),
                ("ementa", models.TextField(verbose_name="Ementa")),
                ("indexacao", models.TextField(blank=True, verbose_name="Indexação")),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("resultado", models.TextField(blank=True)),
                (
                    "texto_original",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.materia.models.materia_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Texto Original",
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Data"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="IP"
                    ),
                ),
                (
                    "arquivado",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Arquivamento completo?",
                    ),
                ),
                (
                    "checkcheck",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Processo Legislativo Auditado?",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)",
                    ),
                ),
                (
                    "anexadas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="anexo_de",
                        through="materia.Anexada",
                        through_fields=("materia_principal", "materia_anexada"),
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "assuntos",
                    models.ManyToManyField(
                        blank=True,
                        through="materia.MateriaAssunto",
                        through_fields=("materia", "assunto"),
                        to="materia.assuntomateria",
                    ),
                ),
                (
                    "autores",
                    models.ManyToManyField(
                        through="materia.Autoria",
                        through_fields=("materia", "autor"),
                        to="base.autor",
                    ),
                ),
                (
                    "similaridades",
                    models.ManyToManyField(
                        blank=True,
                        related_name="similaridade_set",
                        through="materia.AnaliseSimilaridade",
                        through_fields=("materia_1", "materia_2"),
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "local_origem_externa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.origem",
                        verbose_name="Local de Origem",
                    ),
                ),
                (
                    "regime_tramitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.regimetramitacao",
                        verbose_name="Regime Tramitação",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tipomaterialegislativa",
                        verbose_name="Tipo de Matéria Legislativa",
                    ),
                ),
                (
                    "tipo_origem_externa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipo_origem_externa_set",
                        to="materia.tipomaterialegislativa",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria Legislativa",
                "verbose_name_plural": "Matérias Legislativas",
                "ordering": ["-id"],
                "permissions": (
                    ("can_access_impressos", "Can access impressos"),
                    ("can_check_complete", "Pode checar conclusão de processo"),
                ),
            },
        ),
        migrations.AddField(
            model_name="materiaassunto",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="materia.materialegislativa",
                verbose_name="Matéria",
            ),
        ),
        migrations.CreateModel(
            name="DespachoInicial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comissoes.comissao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despachoinicial_set",
                        to="materia.materialegislativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despacho Inicial",
                "verbose_name_plural": "Despachos Iniciais",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="autoria",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="materia.materialegislativa",
                verbose_name="Matéria Legislativa",
            ),
        ),
        migrations.AddField(
            model_name="anexada",
            name="materia_anexada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materia_anexada_set",
                to="materia.materialegislativa",
                verbose_name="Matéria Anexada",
            ),
        ),
        migrations.AddField(
            model_name="anexada",
            name="materia_principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materia_principal_set",
                to="materia.materialegislativa",
                verbose_name="Matéria Principal",
            ),
        ),
        migrations.AddField(
            model_name="analisesimilaridade",
            name="materia_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materia_1_set",
                to="materia.materialegislativa",
                verbose_name="Matéria 1",
            ),
        ),
        migrations.AddField(
            model_name="analisesimilaridade",
            name="materia_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materia_2_set",
                to="materia.materialegislativa",
                verbose_name="Matéria 2",
            ),
        ),
        migrations.CreateModel(
            name="AcompanhamentoMateria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                ("data_cadastro", models.DateField(auto_now_add=True)),
                ("hash", models.CharField(max_length=8)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acompanhamento de Matéria",
                "verbose_name_plural": "Acompanhamentos de Matéria",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PautaReuniao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materia_set",
                        to="materia.materialegislativa",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "reuniao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reuniao_set",
                        to="comissoes.reuniao",
                        verbose_name="Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria da Pauta",
                "verbose_name_plural": "Matérias da Pauta",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Relatoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_designacao_relator",
                    models.DateField(verbose_name="Data Designação"),
                ),
                (
                    "data_destituicao_relator",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Destituição"
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comissoes.comissao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "tipo_fim_relatoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tipofimrelatoria",
                        verbose_name="Motivo Fim Relatoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatoria",
                "verbose_name_plural": "Relatorias",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Parecer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_conclusao", models.CharField(blank=True, max_length=3)),
                (
                    "tipo_apresentacao",
                    models.CharField(
                        choices=[("O", "Oral"), ("E", "Escrita")], max_length=1
                    ),
                ),
                ("parecer", models.TextField(blank=True)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "relatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.relatoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parecer",
                "verbose_name_plural": "Pareceres",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoAcessorio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, verbose_name="Título do Documento"),
                ),
                (
                    "data",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "autor",
                    models.CharField(blank=True, max_length=200, verbose_name="Autor"),
                ),
                ("ementa", models.TextField(blank=True, verbose_name="Ementa")),
                ("indexacao", models.TextField(blank=True)),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.materia.models.anexo_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Texto Integral",
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Data"),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tipodocumento",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Acessório",
                "verbose_name_plural": "Documentos Acessórios",
                "ordering": ("data", "id"),
            },
        ),
        migrations.CreateModel(
            name="Numeracao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_materia",
                    models.CharField(max_length=5, verbose_name="Número"),
                ),
                (
                    "ano_materia",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2027, 2027),
                            (2026, 2026),
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                            (1959, 1959),
                            (1958, 1958),
                            (1957, 1957),
                            (1956, 1956),
                            (1955, 1955),
                            (1954, 1954),
                            (1953, 1953),
                            (1952, 1952),
                            (1951, 1951),
                            (1950, 1950),
                            (1949, 1949),
                            (1948, 1948),
                            (1947, 1947),
                            (1946, 1946),
                            (1945, 1945),
                            (1944, 1944),
                            (1943, 1943),
                            (1942, 1942),
                            (1941, 1941),
                            (1940, 1940),
                            (1939, 1939),
                            (1938, 1938),
                            (1937, 1937),
                            (1936, 1936),
                            (1935, 1935),
                            (1934, 1934),
                            (1933, 1933),
                            (1932, 1932),
                            (1931, 1931),
                            (1930, 1930),
                            (1929, 1929),
                            (1928, 1928),
                            (1927, 1927),
                            (1926, 1926),
                            (1925, 1925),
                            (1924, 1924),
                            (1923, 1923),
                            (1922, 1922),
                            (1921, 1921),
                            (1920, 1920),
                            (1919, 1919),
                            (1918, 1918),
                            (1917, 1917),
                            (1916, 1916),
                            (1915, 1915),
                            (1914, 1914),
                            (1913, 1913),
                            (1912, 1912),
                            (1911, 1911),
                            (1910, 1910),
                            (1909, 1909),
                            (1908, 1908),
                            (1907, 1907),
                            (1906, 1906),
                            (1905, 1905),
                            (1904, 1904),
                            (1903, 1903),
                            (1902, 1902),
                            (1901, 1901),
                            (1900, 1900),
                            (1899, 1899),
                            (1898, 1898),
                            (1897, 1897),
                            (1896, 1896),
                            (1895, 1895),
                            (1894, 1894),
                            (1893, 1893),
                            (1892, 1892),
                            (1891, 1891),
                            (1890, 1890),
                        ],
                        verbose_name="Ano",
                    ),
                ),
                ("data_materia", models.DateField(null=True, verbose_name="Data")),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "tipo_materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tipomaterialegislativa",
                        verbose_name="Tipo de Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numeração",
                "verbose_name_plural": "Numerações",
                "ordering": (
                    "materia",
                    "tipo_materia",
                    "numero_materia",
                    "ano_materia",
                    "data_materia",
                ),
            },
        ),
        migrations.CreateModel(
            name="TipoProposicao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        error_messages={
                            "unique": "Já existe um Tipo de Proposição com esta descrição."
                        },
                        max_length=50,
                        unique=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "exige_assinatura_digital",
                    models.BooleanField(
                        default=True, verbose_name="Exigir Assinatura Digital"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        default=None,
                        help_text="\n        Quando uma proposição é incorporada, ela é convertida de proposição\n        para outro elemento dentro do Sapl. Existem alguns elementos que\n        uma proposição pode se tornar. Defina este meta-tipo e em seguida\n        escolha um Tipo Correspondente!\n        ",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="Conversão de Meta-Tipos",
                    ),
                ),
                (
                    "perfis",
                    models.ManyToManyField(
                        blank=True,
                        help_text="\n                    Mesmo que em Configurações da Aplicação nas\n                    Tabelas Auxiliares esteja definido que Proposições possam\n                    utilizar Textos Articulados, ao gerar uma proposição,\n                    a solução de Textos Articulados será disponibilizada se\n                    o Tipo escolhido para a Proposição estiver associado a ao\n                    menos um Perfil Estrutural de Texto Articulado.\n                    ",
                        to="compilacao.perfilestruturaltextoarticulado",
                        verbose_name="Perfis Estruturais de Textos Articulados",
                    ),
                ),
                (
                    "tipo_autores",
                    models.ManyToManyField(
                        blank=True,
                        help_text="\n                    Tipo de Autores que pode enviar este tipo de Proposição.\n                    ",
                        to="base.tipoautor",
                        verbose_name="Tipos de Autores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Proposição",
                "verbose_name_plural": "Tipos de Proposições",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Proposicao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(null=True, verbose_name="Data de Envio"),
                ),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Devolução"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "justificativa_devolucao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Justificativa da Devolução",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (2027, 2027),
                            (2026, 2026),
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                            (1959, 1959),
                            (1958, 1958),
                            (1957, 1957),
                            (1956, 1956),
                            (1955, 1955),
                            (1954, 1954),
                            (1953, 1953),
                            (1952, 1952),
                            (1951, 1951),
                            (1950, 1950),
                            (1949, 1949),
                            (1948, 1948),
                            (1947, 1947),
                            (1946, 1946),
                            (1945, 1945),
                            (1944, 1944),
                            (1943, 1943),
                            (1942, 1942),
                            (1941, 1941),
                            (1940, 1940),
                            (1939, 1939),
                            (1938, 1938),
                            (1937, 1937),
                            (1936, 1936),
                            (1935, 1935),
                            (1934, 1934),
                            (1933, 1933),
                            (1932, 1932),
                            (1931, 1931),
                            (1930, 1930),
                            (1929, 1929),
                            (1928, 1928),
                            (1927, 1927),
                            (1926, 1926),
                            (1925, 1925),
                            (1924, 1924),
                            (1923, 1923),
                            (1922, 1922),
                            (1921, 1921),
                            (1920, 1920),
                            (1919, 1919),
                            (1918, 1918),
                            (1917, 1917),
                            (1916, 1916),
                            (1915, 1915),
                            (1914, 1914),
                            (1913, 1913),
                            (1912, 1912),
                            (1911, 1911),
                            (1910, 1910),
                            (1909, 1909),
                            (1908, 1908),
                            (1907, 1907),
                            (1906, 1906),
                            (1905, 1905),
                            (1904, 1904),
                            (1903, 1903),
                            (1902, 1902),
                            (1901, 1901),
                            (1900, 1900),
                            (1899, 1899),
                            (1898, 1898),
                            (1897, 1897),
                            (1896, 1896),
                            (1895, 1895),
                            (1894, 1894),
                            (1893, 1893),
                            (1892, 1892),
                            (1891, 1891),
                            (1890, 1890),
                        ],
                        default=None,
                        null=True,
                        verbose_name="Ano",
                    ),
                ),
                (
                    "numero_proposicao",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "numero_materia_futuro",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número Matéria"
                    ),
                ),
                (
                    "hash_code",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Código do Documento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("E", "Enviada"),
                            ("R", "Recebida"),
                            ("I", "Incorporada"),
                        ],
                        max_length=1,
                        verbose_name="Status Proposição",
                    ),
                ),
                (
                    "texto_original",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.materia.models.materia_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Texto Original",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "cancelado",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Cancelada ?",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="IP"
                    ),
                ),
                (
                    "ultima_edicao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Hora da Edição"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.autor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Material Gerado",
                    ),
                ),
                (
                    "materia_de_vinculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposicao_set",
                        to="materia.materialegislativa",
                        verbose_name="Matéria anexadora",
                    ),
                ),
                (
                    "proposicao_vinculada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposicao_vinculada_set",
                        to="materia.proposicao",
                        verbose_name="Proposição Vinculada",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tipoproposicao",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposição",
                "verbose_name_plural": "Proposições",
                "ordering": ["-data_recebimento"],
                "permissions": (
                    (
                        "detail_proposicao_enviada",
                        "Pode acessar detalhes de uma proposição enviada.",
                    ),
                    (
                        "detail_proposicao_devolvida",
                        "Pode acessar detalhes de uma proposição devolvida.",
                    ),
                    (
                        "detail_proposicao_incorporada",
                        "Pode acessar detalhes de uma proposição incorporada.",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="UnidadeTramitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Ativo ?",
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comissoes.comissao",
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Tramitação",
                "verbose_name_plural": "Unidades de Tramitação",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Tramitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("data_tramitacao", models.DateField(verbose_name="Data Tramitação")),
                (
                    "data_encaminhamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Encaminhamento"
                    ),
                ),
                (
                    "urgente",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Urgente ?",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Primeiro"), ("S", "Segundo"), ("U", "Único")],
                        max_length=1,
                        verbose_name="Turno",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto da Ação")),
                (
                    "data_fim_prazo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim Prazo"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="IP"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.statustramitacao",
                        verbose_name="Status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "unidade_tramitacao_destino",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramitacoes_destino",
                        to="materia.unidadetramitacao",
                        verbose_name="Unidade Destino",
                    ),
                ),
                (
                    "unidade_tramitacao_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramitacoes_origem",
                        to="materia.unidadetramitacao",
                        verbose_name="Unidade Local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tramitação",
                "verbose_name_plural": "Tramitações",
                "ordering": ("-data_tramitacao", "-id"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="autoria",
            unique_together={("autor", "materia")},
        ),
        migrations.AddIndex(
            model_name="analisesimilaridade",
            index=models.Index(
                fields=["-data_analise", "-qtd_assuntos_comuns"],
                name="materia_ana_data_an_c17e6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisesimilaridade",
            index=models.Index(
                fields=["materia_1", "-similaridade"],
                name="materia_ana_materia_8c30d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisesimilaridade",
            index=models.Index(
                fields=["materia_2", "-similaridade"],
                name="materia_ana_materia_7118ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisesimilaridade",
            index=models.Index(
                fields=["similaridade"], name="materia_ana_similar_d8a98b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialegislativa",
            index=models.Index(
                fields=["-em_tramitacao"], name="materia_mat_em_tram_825dd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialegislativa",
            index=models.Index(
                fields=["-data_apresentacao"], name="materia_mat_data_ap_85b915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialegislativa",
            index=models.Index(
                fields=["-data_apresentacao", "-id"],
                name="materia_mat_data_ap_0d5f6d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proposicao",
            unique_together={("content_type", "object_id")},
        ),
    ]
