# Generated by Django 5.2.14 on 2026-05-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_assinantes_proposicao"),
        ("materia", "0002_viewdb_materiaemtramitacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposicaoAssinante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pendente"),
                            ("A", "Em Assinatura"),
                            ("S", "Assinado"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_captura",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento em que o autor capturou o lock para assinar.",
                        null=True,
                        verbose_name="Data de Captura",
                    ),
                ),
                (
                    "data_assinatura",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento confirmado pela extração de assinatura digital.",
                        null=True,
                        verbose_name="Data de Assinatura",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposicao_assinantes",
                        to="base.autor",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "proposicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinantes",
                        to="materia.proposicao",
                        verbose_name="Proposição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinante de Proposição",
                "verbose_name_plural": "Assinantes de Proposição",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "A")),
                        fields=("proposicao",),
                        name="unique_em_assinatura_per_proposicao",
                    )
                ],
                "unique_together": {("proposicao", "autor")},
            },
        ),
    ]
