# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0057_auto_20190917_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='autor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Autor'),
        ),
    ]
