# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0058_auto_20191015_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoacessorio',
            options={'ordering': ('data', 'id'), 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
        migrations.AddField(
            model_name='materialegislativa',
            name='arquivado',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Arquivamento completo?'),
        ),
    ]
