# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0059_auto_20191028_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialegislativa',
            name='checkcheck',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Processo Legislativo Auditado?'),
        ),
    ]
