# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0061_auto_20200128_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='_paginas',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Páginas'),
        ),
    ]
