# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 13:36
from __future__ import unicode_literals

from django.db import migrations
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0063_auto_20200129_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='texto_original',
            field=sapl.utils.PortalFileField(blank=True, max_length=512, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.materia.models.materia_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original'),
        ),
    ]
