# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 03:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0066_auto_20200130_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialegislativa',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
