# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20200409_1257'),
        ('materia', '0068_proposicao_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproposicao',
            name='tipo_autores',
            field=models.ManyToManyField(blank=True, help_text='\n                    Tipo de Autores que pode enviar este tipo de Proposição.\n                    ', to='base.TipoAutor', verbose_name='Tipos de Autores'),
        ),
    ]
