# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0070_proposicao_proposicao_vinculada'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='_paginas',
            field=models.IntegerField(default=0, verbose_name='Número de Páginas'),
        ),
    ]
