# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-27 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0071_proposicao__paginas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialegislativa',
            options={'ordering': ['-id'], 'permissions': (('can_access_impressos', 'Can access impressos'), ('can_check_complete', 'Pode checar conclusão de processo')), 'verbose_name': 'Matéria Legislativa', 'verbose_name_plural': 'Matérias Legislativas'},
        ),
    ]
