# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-05 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0072_auto_20200427_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='documentoacessorio',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Título do Documento'),
        ),
    ]
