# Generated by Django 2.2.12 on 2020-05-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0073_auto_20200505_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pautareuniao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_set', to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
    ]
