# Generated by Django 2.2.13 on 2020-08-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0074_auto_20200520_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'ordering': ('-data_tramitacao', '-id'), 'verbose_name': 'Tramitação', 'verbose_name_plural': 'Tramitações'},
        ),
    ]
