# Generated by Django 2.2.15 on 2020-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0075_auto_20200814_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproposicao',
            name='exige_assinatura_digital',
            field=models.BooleanField(default=True, verbose_name='Exigir Assinatura Digital'),
        ),
    ]
