# Generated by Django 2.2.16 on 2020-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0076_tipoproposicao_exige_assinatura_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialegislativa',
            name='url_video',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'),
        ),
    ]
