# Generated by Django 2.2.20 on 2021-05-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0078_auto_20210302_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterialegislativa',
            name='turnos_aprovacao',
            field=models.PositiveIntegerField(default=1, verbose_name='Turnos para aprovação.'),
        ),
    ]
