# Generated by Django 2.2.28 on 2022-07-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0081_auto_20220128_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialegislativa',
            unique_together=set(),
        ),
    ]
