# Generated by Django 2.2.28 on 2023-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0083_auto_20230205_1438'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialegislativa',
            index=models.Index(fields=['-em_tramitacao'], name='materia_mat_em_tram_825dd6_idx'),
        ),
    ]
