# Generated by Django 2.2.28 on 2023-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0084_auto_20230504_0844'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialegislativa',
            index=models.Index(fields=['-data_apresentacao'], name='materia_mat_data_ap_85b915_idx'),
        ),
    ]
