# Generated by Django 2.2.28 on 2023-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0085_auto_20230505_1648'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialegislativa',
            index=models.Index(fields=['-data_apresentacao', '-id'], name='materia_mat_data_ap_0d5f6d_idx'),
        ),
    ]
