# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0087_auto_20240103_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamentomateria',
            options={'ordering': ['id'], 'verbose_name': 'Acompanhamento de Matéria', 'verbose_name_plural': 'Acompanhamentos de Matéria'},
        ),
        migrations.AlterModelOptions(
            name='anexada',
            options={'ordering': ['id'], 'verbose_name': 'Anexada', 'verbose_name_plural': 'Anexadas'},
        ),
        migrations.AlterModelOptions(
            name='assuntomateria',
            options={'ordering': ['id'], 'verbose_name': 'Assunto de Matéria', 'verbose_name_plural': 'Assuntos de Matéria'},
        ),
        migrations.AlterModelOptions(
            name='despachoinicial',
            options={'ordering': ['id'], 'verbose_name': 'Despacho Inicial', 'verbose_name_plural': 'Despachos Iniciais'},
        ),
        migrations.AlterModelOptions(
            name='materiaassunto',
            options={'ordering': ['id'], 'verbose_name': 'Relação Matéria - Assunto', 'verbose_name_plural': 'Relações Matéria - Assunto'},
        ),
        migrations.AlterModelOptions(
            name='origem',
            options={'ordering': ['id'], 'verbose_name': 'Origem', 'verbose_name_plural': 'Origens'},
        ),
        migrations.AlterModelOptions(
            name='parecer',
            options={'ordering': ['id'], 'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'},
        ),
        migrations.AlterModelOptions(
            name='pautareuniao',
            options={'ordering': ['id'], 'verbose_name': 'Matéria da Pauta', 'verbose_name_plural': 'Matérias da Pauta'},
        ),
        migrations.AlterModelOptions(
            name='regimetramitacao',
            options={'ordering': ['id'], 'verbose_name': 'Regime de Tramitação', 'verbose_name_plural': 'Regimes de Tramitação'},
        ),
        migrations.AlterModelOptions(
            name='relatoria',
            options={'ordering': ['id'], 'verbose_name': 'Relatoria', 'verbose_name_plural': 'Relatorias'},
        ),
        migrations.AlterModelOptions(
            name='tipofimrelatoria',
            options={'ordering': ['id'], 'verbose_name': 'Tipo Fim de Relatoria', 'verbose_name_plural': 'Tipos Fim de Relatoria'},
        ),
        migrations.AlterModelOptions(
            name='tipoproposicao',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Proposição', 'verbose_name_plural': 'Tipos de Proposições'},
        ),
        migrations.AlterModelOptions(
            name='unidadetramitacao',
            options={'ordering': ['id'], 'verbose_name': 'Unidade de Tramitação', 'verbose_name_plural': 'Unidades de Tramitação'},
        ),
    ]
