# Generated by Django 2.2.28 on 2024-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0089_regimetramitacao_sequencia_regimental'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterialegislativa',
            name='nivel_agrupamento',
            field=models.CharField(blank=True, choices=[('1', 'Nível 1'), ('2', 'Nível 2'), ('3', 'Nível 3'), ('4', 'Nível 4'), ('5', 'Nível 5'), ('6', 'Nível 6'), ('7', 'Nível 7'), ('8', 'Nível 8'), ('9', 'Nível 9')], max_length=1, verbose_name='Nível de Agrupamento'),
        ),
    ]
