# Generated by Django 4.2.16 on 2024-10-03 20:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0090_tipomaterialegislativa_nivel_agrupamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='complementar',
            field=models.BooleanField(blank=True, null=True, verbose_name='É Complementar?'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='polemica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Matéria Polêmica?'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
