# Generated by Django 4.2.17 on 2025-01-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0092_alter_materialegislativa_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterialegislativa',
            name='prompt',
            field=models.TextField(blank=True, verbose_name='Prompt para Análise de IA.'),
        ),
    ]
