# Generated by Django 4.2.18 on 2025-01-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0095_unidadetramitacao_ativo'),
    ]

    operations = [
        migrations.RunSQL("""
            create or replace view materia_materiaemtramitacao as
            select m.id as id,
                   m.id as materia_id,
                   t.id as tramitacao_id,
                   t.unidade_tramitacao_destino_id as unidade_tramitacao_atual_id
            from materia_materialegislativa m
            inner join materia_tramitacao t on (m.id = t.materia_id)
            where t.id = (select max(id) from materia_tramitacao where materia_id = m.id)
            order by m.id DESC
        """),
    ]
