# Generated by Django 5.2.1 on 2025-05-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0100_alter_materialegislativa_anexadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisesimilaridade',
            name='qtd_assuntos_comuns',
            field=models.SmallIntegerField(default=0, verbose_name='Qtd de Assuntos Comuns'),
        ),
        migrations.AlterField(
            model_name='analisesimilaridade',
            name='similaridade',
            field=models.SmallIntegerField(default=-1, verbose_name='Similaridade'),
        ),
    ]
