# Generated by Django 5.2.1 on 2025-05-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0101_analisesimilaridade_qtd_assuntos_comuns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisesimilaridade',
            options={'ordering': ['-data_analise', '-qtd_assuntos_comuns'], 'verbose_name': 'Análise de Similaridade', 'verbose_name_plural': 'Análises de Similaridade'},
        ),
    ]
