# Generated by Django 5.2.3 on 2025-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0102_alter_analisesimilaridade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustramitacao',
            name='css_class',
            field=models.CharField(blank=True, default='', help_text='Classe CSS para estilização do status na listagem. Exemplo: "badge badge-success"', max_length=40, verbose_name='Classe CSS'),
        ),
    ]
