# Generated by Django 5.2.9 on 2025-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0105_materiaemtramitacao_replace'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analisesimilaridade',
            index=models.Index(fields=['-data_analise', '-qtd_assuntos_comuns'], name='materia_ana_data_an_c17e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='analisesimilaridade',
            index=models.Index(fields=['materia_1', '-similaridade'], name='materia_ana_materia_8c30d1_idx'),
        ),
        migrations.AddIndex(
            model_name='analisesimilaridade',
            index=models.Index(fields=['materia_2', '-similaridade'], name='materia_ana_materia_7118ba_idx'),
        ),
        migrations.AddIndex(
            model_name='analisesimilaridade',
            index=models.Index(fields=['similaridade'], name='materia_ana_similar_d8a98b_idx'),
        ),
    ]
