# Generated by Django 5.2.11 on 2026-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materia", "0107_alter_materialegislativa_ano_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisesimilaridade",
            name="analise",
            field=models.TextField(
                blank=True, default="", verbose_name="Análise de Similaridade"
            ),
        ),
        migrations.AlterField(
            model_name="analisesimilaridade",
            name="ia_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Nome do Algoritmo de IA",
            ),
        ),
    ]
