# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.files.storage
import django.core.serializers.json
import django.db.models.deletion
import django_extensions.db.fields.json
from django.conf import settings
from django.db import migrations, models

import cmj.sigad.models
import cmj.utils_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0002_initial"),
        ("materia", "0001_initial"),
        ("parlamentares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaixaPublicacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="", max_length=250)),
                ("nome", models.CharField(default="", max_length=250)),
            ],
            options={
                "verbose_name": "Caixa de Publicação",
                "verbose_name_plural": "Caixas de Publicação",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CaixaPublicacaoClasse",
            fields=[],
            options={
                "verbose_name": "Caixa de Publicação",
                "verbose_name_plural": "Caixas de Publicação",
                "ordering": ["id"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sigad.caixapublicacao",),
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "public_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Início de Publicação",
                    ),
                ),
                (
                    "public_end_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Fim de Publicação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "autor",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Autor"
                    ),
                ),
                (
                    "visibilidade",
                    models.IntegerField(
                        choices=[(1, "Restrito"), (0, "Público"), (99, "Privado")],
                        default=99,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "listar",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Aparecer nas Listagens",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Apelido",
                    ),
                ),
                ("slug", models.SlugField(max_length=2000)),
                (
                    "codigo",
                    models.PositiveIntegerField(default=0, verbose_name="Código"),
                ),
                (
                    "atricon",
                    models.CharField(default="", max_length=10, verbose_name="Atricon"),
                ),
                (
                    "perfil",
                    models.IntegerField(
                        choices=[
                            (0, "Classe Estrutural"),
                            (1, "Classe de Conteúdo"),
                            (2, "Classe Mista"),
                            (98, "Classe de Redirecionamento via URL"),
                            (99, "Classe de Redirecionamento via Views"),
                        ],
                        default=0,
                        verbose_name="Perfil da Classe",
                    ),
                ),
                (
                    "template_doc_padrao",
                    models.IntegerField(
                        choices=[
                            (1, "Notícia Pública"),
                            (2, "Galeria de Imagens"),
                            (501, "Capa de Subsite"),
                        ],
                        default=1,
                        verbose_name="Template para o Documento",
                    ),
                ),
                (
                    "tipo_doc_padrao",
                    models.IntegerField(
                        choices=[
                            (0, "Notícias"),
                            (5, "Documento"),
                            (10, "Banco de Imagem"),
                            (20, "Galeria Pública"),
                            (30, "Áudio Notícia"),
                            (40, "Vídeo Notícia"),
                        ],
                        default=5,
                        verbose_name="Tipo Padrão para Docs da Classe",
                    ),
                ),
                (
                    "template_classe",
                    models.IntegerField(
                        choices=[
                            (1, "Listagem em Linha"),
                            (2, "Galeria Albuns"),
                            (3, "Página dos Parlamentares"),
                            (4, "Página individual de Parlamentar"),
                            (5, "Banco de Imagens"),
                            (6, "Galeria de Áudios"),
                            (7, "Galeria de Vídeos"),
                            (99, "Documento Específico"),
                            (500, "Subsites"),
                            (999, "Mapa do Site"),
                        ],
                        default=1,
                        verbose_name="Template para a Classe",
                    ),
                ),
                (
                    "list_in_mapa",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Listar no mapa do site",
                    ),
                ),
                (
                    "list_in_inf",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Listar no Acesso à Informação",
                    ),
                ),
                (
                    "list_in_menu",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Listar no Menu Geral",
                    ),
                ),
                (
                    "menu_lateral",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Montar Menu Lateral",
                    ),
                ),
                (
                    "url_redirect",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=1024,
                        verbose_name="URL de redirecionamento",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="childs",
                        to="sigad.classe",
                        verbose_name="Filhos",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classe_set",
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "raiz",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="sigad.classe",
                        verbose_name="Containers",
                    ),
                ),
                (
                    "related_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="sigad.classe",
                        verbose_name="Classes Relacionadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ("codigo", "-public_date"),
                "permissions": (
                    ("view_subclasse", "Visualização de Subclasses"),
                    ("view_pathclasse", "Visualização de Classe via Path"),
                ),
            },
        ),
        migrations.AddField(
            model_name="caixapublicacao",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="caixapublicacao_set",
                to="sigad.classe",
                verbose_name="Classes",
            ),
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "public_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Início de Publicação",
                    ),
                ),
                (
                    "public_end_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Fim de Publicação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "autor",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Autor"
                    ),
                ),
                (
                    "visibilidade",
                    models.IntegerField(
                        choices=[(1, "Restrito"), (0, "Público"), (99, "Privado")],
                        default=99,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "listar",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Aparecer nas Listagens",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Apelido",
                    ),
                ),
                ("slug", models.SlugField(max_length=2000)),
                (
                    "texto",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Texto"
                    ),
                ),
                (
                    "old_path",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Path no Portal Modelo 1.0",
                    ),
                ),
                (
                    "old_json",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Json no Portal Modelo 1.0",
                    ),
                ),
                (
                    "extra_data",
                    django_extensions.db.fields.json.JSONField(
                        blank=True, default=None, null=True, verbose_name="Dados Extras"
                    ),
                ),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[
                            (0, "Notícias"),
                            (5, "Documento"),
                            (10, "Banco de Imagem"),
                            (20, "Galeria Pública"),
                            (30, "Áudio Notícia"),
                            (40, "Vídeo Notícia"),
                            (700, "Container Simples"),
                            (701, "Container Extendido"),
                            (750, "Container de Imagens para Arquivo PDF"),
                            (100, "Texto"),
                            (200, "Arquivo"),
                            (800, "Vídeo"),
                            (850, "Áudio"),
                            (900, "Imagem"),
                            (901, "Galeria de Imagens"),
                        ],
                        default=5,
                        verbose_name="Tipo da Parte do Documento",
                    ),
                ),
                (
                    "template_doc",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Notícia Pública"),
                            (2, "Galeria de Imagens"),
                            (501, "Capa de Subsite"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="Template para o Documento",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0, verbose_name="Ordem de Renderização"
                    ),
                ),
                (
                    "alinhamento",
                    models.IntegerField(
                        choices=[
                            (0, "Alinhamento Esquerdo"),
                            (1, "Alinhamento Completo"),
                            (2, "Alinhamento Direito"),
                            (3, "Alinhamento Centralizado"),
                            (4, "Alinhamento Completo - Render Large"),
                        ],
                        default=0,
                        verbose_name="Alinhamento",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documento_set",
                        to="sigad.classe",
                        verbose_name="Classes",
                    ),
                ),
                (
                    "classes_relacionadas",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="documentos_relacionados_set",
                        to="sigad.classe",
                        verbose_name="Classes Relacionadas",
                    ),
                ),
                (
                    "materias",
                    models.ManyToManyField(
                        related_name="documento_set",
                        to="materia.materialegislativa",
                        verbose_name="Matérias Relacionadas",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="childs",
                        to="sigad.documento",
                        verbose_name="Filhos",
                    ),
                ),
                (
                    "parlamentares",
                    models.ManyToManyField(
                        related_name="documento_set",
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentares",
                    ),
                ),
                (
                    "raiz",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="sigad.documento",
                        verbose_name="Containers",
                    ),
                ),
                (
                    "related_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="sigad.documento",
                        verbose_name="Classes Relacionadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ("public_date",),
                "permissions": (
                    ("view_documento_show", "Visualização dos Metadados do Documento."),
                    ("view_documento_media", "Visualização das mídias do Documento"),
                ),
            },
        ),
        migrations.AddField(
            model_name="classe",
            name="capa",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capa",
                to="sigad.documento",
                verbose_name="Capa da Classe",
            ),
        ),
        migrations.CreateModel(
            name="CaixaPublicacaoRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "caixapublicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sigad.caixapublicacao",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sigad.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documentos da Caixa de Publicação",
                "verbose_name_plural": "Documentos da Caixa de Publicação",
                "ordering": ("ordem", "-documento"),
                "unique_together": {("caixapublicacao", "documento")},
            },
        ),
        migrations.AddField(
            model_name="caixapublicacao",
            name="documentos",
            field=models.ManyToManyField(
                blank=True,
                related_query_name="caixapublicacao_set",
                through="sigad.CaixaPublicacaoRelationship",
                through_fields=("caixapublicacao", "documento"),
                to="sigad.documento",
                verbose_name="Documentos da Caixa de Públicação",
            ),
        ),
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auditlog",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="midia",
                        to="core.auditlog",
                        verbose_name="AuditLog",
                    ),
                ),
                (
                    "documento",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="midia",
                        to="sigad.documento",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia Versionada",
                "verbose_name_plural": "Mídias Versionadas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReferenciaEntreDocumentos",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Título",
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "apelido",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        null=True,
                        verbose_name="Apelido",
                    ),
                ),
                ("slug", models.SlugField(max_length=2000)),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "autor",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Autor"
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(
                        default=0, verbose_name="Ordem de Renderização"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="childs",
                        to="sigad.referenciaentredocumentos",
                        verbose_name="Filhos",
                    ),
                ),
                (
                    "raiz",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="sigad.referenciaentredocumentos",
                        verbose_name="Containers",
                    ),
                ),
                (
                    "referenciado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citado_em",
                        to="sigad.documento",
                        verbose_name="Documento Referenciado",
                    ),
                ),
                (
                    "referente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cita",
                        to="sigad.documento",
                        verbose_name="Documento Referente",
                    ),
                ),
                (
                    "related_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="sigad.referenciaentredocumentos",
                        verbose_name="Classes Relacionadas",
                    ),
                ),
            ],
            options={
                "ordering": ("referente", "ordem"),
            },
        ),
        migrations.AddField(
            model_name="documento",
            name="documentos_citados",
            field=models.ManyToManyField(
                through="sigad.ReferenciaEntreDocumentos",
                through_fields=("referente", "referenciado"),
                to="sigad.documento",
            ),
        ),
        migrations.CreateModel(
            name="UrlShortener",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_short",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Link Curto",
                    ),
                ),
                (
                    "url_long",
                    models.TextField(db_index=True, verbose_name="Link Longo"),
                ),
                (
                    "link_absoluto",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Link Absoluto",
                    ),
                ),
                (
                    "automatico",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Link Automático",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "UrlShortener",
                "verbose_name_plural": "UrlShortener",
                "ordering": ("url_short",),
                "unique_together": {("url_short", "url_long")},
            },
        ),
        migrations.CreateModel(
            name="ShortRedirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos_set",
                        to="sigad.urlshortener",
                        verbose_name="UrlShortner",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="VersaoDeMidia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="DO_NOT_USE",
                            location="/mnt/volumes/cmj_media/media_protected",
                        ),
                        upload_to=cmj.sigad.models.media_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_midias],
                        verbose_name="Mídia",
                    ),
                ),
                ("content_type", models.CharField(default="", max_length=250)),
                (
                    "midia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="sigad.midia",
                        verbose_name="Mídia Versionada",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia",
                "verbose_name_plural": "Mídias",
                "ordering": ("-created",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="classe",
            unique_together={("slug", "parent")},
        ),
        migrations.CreateModel(
            name="PermissionsUserClasse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "public_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Início de Publicação",
                    ),
                ),
                (
                    "public_end_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Fim de Publicação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "autor",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Autor"
                    ),
                ),
                (
                    "visibilidade",
                    models.IntegerField(
                        choices=[(1, "Restrito"), (0, "Público"), (99, "Privado")],
                        default=99,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "listar",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Aparecer nas Listagens",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissions_user_set",
                        to="sigad.classe",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.permission",
                        verbose_name="Permissão",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Usuário para Classe",
                "verbose_name_plural": "Permissões de Usuários para Classes",
                "ordering": ["id"],
                "unique_together": {("user", "classe", "permission")},
            },
        ),
        migrations.CreateModel(
            name="PermissionsUserDocumento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "public_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Início de Publicação",
                    ),
                ),
                (
                    "public_end_date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Data de Fim de Publicação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "autor",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Autor"
                    ),
                ),
                (
                    "visibilidade",
                    models.IntegerField(
                        choices=[(1, "Restrito"), (0, "Público"), (99, "Privado")],
                        default=99,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "listar",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Aparecer nas Listagens",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissions_user_set",
                        to="sigad.documento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.permission",
                        verbose_name="Permissão",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Usuário para Documento",
                "verbose_name_plural": "Permissões de Usuários para Documentos",
                "ordering": ["id"],
                "unique_together": {("user", "documento", "permission")},
            },
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["-public_date"], name="sigad_docum_public__c8f0ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["-public_date", "-created"],
                name="sigad_docum_public__f09b07_idx",
            ),
        ),
    ]
