# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('public_date', models.DateTimeField(default=None, null=True, verbose_name='Data de Início de Publicação')),
                ('public_end_date', models.DateTimeField(default=None, null=True, verbose_name='Data de Fim de Publicação')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição')),
                ('visibilidade', models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=2000)),
                ('codigo', models.PositiveIntegerField(default=0, verbose_name='Código')),
                ('perfil', models.IntegerField(choices=[(0, 'Classe Estrutural'), (1, 'Classe de Conteúdo'), (2, 'Classe Mista')], default=0, verbose_name='Perfil da Classe')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='sigad.Classe', verbose_name='Filhos')),
                ('related_classes', models.ManyToManyField(blank=True, related_name='_classe_related_classes_+', to='sigad.Classe', verbose_name='Classes Relacionadas')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'verbose_name': 'Classe',
                'ordering': ('codigo', '-public_date'),
                'permissions': (('view_subclasse', 'Visualização de Subclasses'),),
            },
        ),
        migrations.CreateModel(
            name='PermissionsUserClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('public_date', models.DateTimeField(default=None, null=True, verbose_name='Data de Início de Publicação')),
                ('public_end_date', models.DateTimeField(default=None, null=True, verbose_name='Data de Fim de Publicação')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição')),
                ('visibilidade', models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigad.Classe', verbose_name='Classe')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Permissão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Permissões de Usuários para Classes',
                'verbose_name': 'Permissão de Usuário para Classe',
            },
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('json', django_extensions.db.fields.json.JSONField(verbose_name='Json')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Revisões',
                'ordering': ('-data',),
                'verbose_name': 'Revisão',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permissionsuserclasse',
            unique_together=set([('user', 'classe', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
