# Generated by Django 5.2.12 on 2026-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="list_in_menu_sapl",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Listar no Menu SAPL",
            ),
        ),
    ]
