# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 12:05
from __future__ import unicode_literals

import cmj.sigad.models
import django.core.files.storage
from django.db import migrations, models
from unipath import Path
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisao',
            name='visibilidade',
            field=models.IntegerField(blank=True, choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=None, null=True, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='versaodemidia',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='DO_NOT_USE', location=Path(settings.MEDIA_PROTECTED_ROOT)), upload_to=cmj.sigad.models.media_path, verbose_name='Mídia'),
        ),
    ]
