# Generated by Django 5.2.12 on 2026-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0002_classe_list_in_menu_sapl"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="list_buscador_classes",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Listar no Buscador de Classes",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="template_classe",
            field=models.IntegerField(
                choices=[
                    (1, "Listagem em Linha"),
                    (2, "Galeria Albuns"),
                    (3, "Página dos Parlamentares"),
                    (4, "Página individual de Parlamentar"),
                    (5, "Banco de Imagens"),
                    (6, "Galeria de Áudios"),
                    (7, "Galeria de Vídeos"),
                    (99, "Documento Específico"),
                    (500, "Subsites"),
                    (998, "Buscador de Classes"),
                    (999, "Mapa do Site"),
                ],
                default=1,
                verbose_name="Template para a Classe",
            ),
        ),
    ]
