# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0002_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
    ]
