# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-15 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('sigad', '0002_auto_20170524_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsUserDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('public_date', models.DateTimeField(default=None, null=True, verbose_name='Data de Início de Publicação')),
                ('public_end_date', models.DateTimeField(default=None, null=True, verbose_name='Data de Fim de Publicação')),
                ('descricao', models.TextField(blank=True, default=None, null=True, verbose_name='Descrição')),
                ('autor', models.TextField(blank=True, default=None, null=True, verbose_name='Autor')),
                ('visibilidade', models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigad.Documento', verbose_name='Documento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Permissão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Permissões de Usuários para Documentos',
                'verbose_name': 'Permissão de Usuário para Documento',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permissionsuserdocumento',
            unique_together=set([('user', 'documento', 'permission')]),
        ),
    ]
