# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0074_auto_20170102_0951'),
        ('sigad', '0003_auto_20170207_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='old_id',
        ),
        migrations.AddField(
            model_name='documento',
            name='materias',
            field=models.ManyToManyField(related_name='documentos', to='materia.MateriaLegislativa', verbose_name='Matérias Relacionadas'),
        ),
        migrations.AddField(
            model_name='documento',
            name='old_path',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Path no Portal Modelo 1.0'),
        ),
    ]
