# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0003_auto_20170815_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='revisao',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='sigad.Revisao', verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='documento',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='sigad.Documento', verbose_name='Documento'),
        ),
    ]
