# Generated by Django 5.2.12 on 2026-04-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0003_classe_list_buscador_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="list_buscador_classes",
        ),
    ]
