# Generated by Django 5.2.12 on 2026-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0004_remove_classe_list_buscador_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="buscador_classes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Não Pertence ao Buscador de Classes"),
                    (10, "Pertence ao Buscador de Classes"),
                    (20, "Pertence e mostra SubClasses imediatas"),
                    (30, "Pertence e mostra toda a hierarquia de SubClasses"),
                    (99, "Buscador Global de Classes"),
                ],
                default=0,
                verbose_name="Buscador de Classes",
            ),
        ),
    ]
