# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-31 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0005_auto_20170817_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='referencias',
            new_name='documentos_citados',
        ),
        migrations.AddField(
            model_name='classe',
            name='template_doc_padrao',
            field=models.IntegerField(choices=[(1, 'Notícia Pública'), (2, 'Galeria de Imagens')], default=1, verbose_name='Template para o Documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='template_doc',
            field=models.IntegerField(choices=[(1, 'Notícia Pública'), (2, 'Galeria de Imagens')], default=1, verbose_name='Template para o Documento'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='referenciado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citado_em', to='sigad.Documento', verbose_name='Documento Referenciado'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='referente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cita', to='sigad.Documento', verbose_name='Documento Referente'),
        ),
    ]
