# Generated by Django 5.2.12 on 2026-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0005_classe_buscador_classes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="buscador_classes",
        ),
        migrations.AddField(
            model_name="classe",
            name="ptnp",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Classe do PNTP",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="template_classe",
            field=models.IntegerField(
                choices=[
                    (1, "Listagem em Linha"),
                    (2, "Galeria Albuns"),
                    (3, "Página dos Parlamentares"),
                    (4, "Página individual de Parlamentar"),
                    (5, "Banco de Imagens"),
                    (6, "Galeria de Áudios"),
                    (7, "Galeria de Vídeos"),
                    (99, "Documento Específico"),
                    (500, "Subsites"),
                    (998, "Classe do PTNP "),
                    (999, "Mapa do Site"),
                ],
                default=1,
                verbose_name="Template para a Classe",
            ),
        ),
    ]
