# Generated by Django 5.2.12 on 2026-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0006_remove_classe_buscador_classes_classe_ptnp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classe",
            old_name="ptnp",
            new_name="pntp",
        ),
        migrations.AlterField(
            model_name="classe",
            name="template_classe",
            field=models.IntegerField(
                choices=[
                    (1, "Listagem em Linha"),
                    (2, "Galeria Albuns"),
                    (3, "Página dos Parlamentares"),
                    (4, "Página individual de Parlamentar"),
                    (5, "Banco de Imagens"),
                    (6, "Galeria de Áudios"),
                    (7, "Galeria de Vídeos"),
                    (99, "Documento Específico"),
                    (500, "Subsites"),
                    (998, "Classe do pntp "),
                    (999, "Mapa do Site"),
                ],
                default=1,
                verbose_name="Template para a Classe",
            ),
        ),
    ]
