# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0006_auto_20170210_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_set', to='sigad.Classe', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
