# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0007_auto_20170904_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versaodemidia',
            name='alinhamento',
        ),
        migrations.AddField(
            model_name='documento',
            name='alinhamento',
            field=models.IntegerField(choices=[(0, 'Alinhamento Esquerdo'), (1, 'Alinhamento Completo'), (2, 'Alinhamento Direito'), (3, 'Alinhamento Fluído')], default=0, verbose_name='Alinhamento'),
        ),
    ]
