# Generated by Django 5.2.12 on 2026-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0007_rename_ptnp_classe_pntp_alter_classe_template_classe"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="pntp",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Listar no PNTP",
            ),
        ),
    ]
