# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0007_auto_20170220_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ('public_date',), 'permissions': (('view_documento', 'Visualização dos Metadados do Documento.'), ('view_documento_media', 'Visualização das mídias do Documento')), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
