# Generated by Django 5.2.12 on 2026-04-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0008_documento_pntp"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="icon_classe",
            field=models.CharField(
                default="", max_length=50, verbose_name="Ícone da Classe"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="icon_doc",
            field=models.CharField(
                default="", max_length=100, verbose_name="Ícone do Documento"
            ),
        ),
    ]
