# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from unipath import Path
import django.core.files.storage
import django.db.models.deletion

import cmj.sigad.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sigad', '0008_auto_20170306_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Mídias Versionadas',
                'verbose_name': 'Mídia Versionada',
            },
        ),
        migrations.CreateModel(
            name='VersaoDeMidia',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(
                    base_url='DO_NOT_USE', location=Path('/sistemas/envs/cmj/media_protected')), upload_to=cmj.sigad.models.media_path, verbose_name='Mídia')),
                ('content_type', models.CharField(default='', max_length=250)),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='versions', to='sigad.Midia', verbose_name='Mídia Versionada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'Mídias',
                'verbose_name': 'Mídia',
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='autor',
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='autor',
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(100, 'Texto'), (800, 'Vídeo'), (
                900, 'Imagem')], default=100, verbose_name='Tipo da Parte do Documento'),
        ),
        migrations.AddField(
            model_name='permissionsuserclasse',
            name='autor',
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='materias',
            field=models.ManyToManyField(
                related_name='documento_set', to='materia.MateriaLegislativa', verbose_name='Matérias Relacionadas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='parlamentares',
            field=models.ManyToManyField(
                related_name='documento_set', to='parlamentares.Parlamentar', verbose_name='Parlamentares'),
        ),
        migrations.AddField(
            model_name='midia',
            name='documento',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='sigad.Documento', verbose_name='Mídia'),
        ),
    ]
