# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0008_auto_20170906_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='alinhamento',
            field=models.IntegerField(choices=[(0, 'Alinhamento Esquerdo'), (1, 'Alinhamento Completo'), (2, 'Alinhamento Direito')], default=0, verbose_name='Alinhamento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(100, 'Texto'), (800, 'Vídeo'), (700, 'Container Simples'), (701, 'Container Extendido'), (900, 'Imagem'), (901, 'Galeria de Imagens')], default=0, verbose_name='Tipo da Parte do Documento'),
        ),
    ]
