# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0009_auto_20170913_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ('codigo', '-public_date'), 'permissions': (('view_subclasse', 'Visualização de Subclasses'), ('view_pathclasse', 'Visualização de Classe via Path')), 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='referenciaentredocumentos',
            options={'ordering': ('referenciado', 'ordem')},
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_user_set', to='sigad.Classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='referente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='sigad.Documento', verbose_name='Documento Referente'),
        ),
    ]
