# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0009_auto_20170324_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem de Renderização'),
        ),
        migrations.AddField(
            model_name='versaodemidia',
            name='alinhamento',
            field=models.IntegerField(choices=[(0, 'Alinhamento Esquerdo'), (1, 'Alinhamento Completo'), (2, 'Alinhamento Direito')], default=0, verbose_name='Alinhamento'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='titulo',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(100, 'Texto'), (800, 'Vídeo'), (900, 'Imagem')], default=0, verbose_name='Tipo da Parte do Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Título'),
        ),
    ]
