# Generated by Django 5.2.12 on 2026-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0009_classe_icon_classe_documento_icon_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="icon_doc",
            field=models.CharField(
                default="", max_length=50, verbose_name="Ícone do Documento"
            ),
        ),
    ]
