# Generated by Django 5.2.13 on 2026-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0010_alter_documento_icon_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="col_in_inf",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Coluna no Acesso à Informação"
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="icon_classe",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Ícone da Classe"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="icon_doc",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Ícone do Documento"
            ),
        ),
    ]
