# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0010_auto_20170919_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (99, 'Privado'), (0, 'Público')], default=99, verbose_name='Visibilidade'),
        ),
    ]
