# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0010_auto_20170324_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_set', to='sigad.Classe', verbose_name='Classes'),
        ),
    ]
