# Generated by Django 5.2.13 on 2026-05-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0011_classe_col_in_inf_alter_classe_icon_classe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classe",
            name="related_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_classes_rel",
                to="sigad.classe",
                verbose_name="Classes Relacionadas",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="related_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_classes_rel",
                to="sigad.documento",
                verbose_name="Classes Relacionadas",
            ),
        ),
        migrations.AlterField(
            model_name="referenciaentredocumentos",
            name="related_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_classes_rel",
                to="sigad.referenciaentredocumentos",
                verbose_name="Classes Relacionadas",
            ),
        ),
    ]
