# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0011_auto_20170919_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_user_set', to='sigad.Documento', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
