# Generated by Django 5.2.13 on 2026-05-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0012_alter_classe_related_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="related_classes",
        ),
        migrations.RemoveField(
            model_name="documento",
            name="related_classes",
        ),
        migrations.RemoveField(
            model_name="referenciaentredocumentos",
            name="related_classes",
        ),
    ]
