# Generated by Django 5.2.13 on 2026-05-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0013_remove_classe_related_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="classes_referenciadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="classes_referenciadoras",
                to="sigad.classe",
                verbose_name="Classes Referenciadas",
            ),
        ),
        migrations.CreateModel(
            name="RelacionamentoEntreClasses",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "referenciada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referenciada_set",
                        to="sigad.classe",
                        verbose_name="Classe Referenciada",
                    ),
                ),
                (
                    "referente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referente_set",
                        to="sigad.classe",
                        verbose_name="Classe Referente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relação entre Classes",
                "verbose_name_plural": "Relações entre Classes",
                "ordering": ("ordem",),
            },
        ),
    ]
