# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-05 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0013_auto_20170921_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='short_url',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Link Curto'),
        ),
        migrations.AddField(
            model_name='documento',
            name='short_url',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Link Curto'),
        ),
    ]
