# Generated by Django 5.2.13 on 2026-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0014_classe_classes_referenciadas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="classes_referenciadas",
        ),
    ]
