# Generated by Django 5.2.13 on 2026-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0015_remove_classe_classes_referenciadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="classes_referenciadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="classes_referenciadoras",
                through="sigad.RelacionamentoEntreClasses",
                through_fields=("referente", "referenciada"),
                to="sigad.classe",
                verbose_name="Classes Referenciadas",
            ),
        ),
    ]
