# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0016_auto_20171004_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciaentredocumentos',
            name='url_short',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Link Curto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Documento'), (10, 'Banco de Imagem'), (20, 'Galeria Pública'), (100, 'Texto'), (800, 'Vídeo'), (700, 'Container Simples'), (701, 'Container Extendido'), (900, 'Imagem'), (901, 'Galeria de Imagens')], default=0, verbose_name='Tipo da Parte do Documento'),
        ),
    ]
