# Generated by Django 5.2.13 on 2026-05-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0016_classe_classes_referenciadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relacionamentoentreclasses",
            name="ordem",
            field=models.PositiveIntegerField(default=999, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="relacionamentoentreclasses",
            name="referenciada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referente_set",
                to="sigad.classe",
                verbose_name="Classe Referenciada",
            ),
        ),
        migrations.AlterField(
            model_name="relacionamentoentreclasses",
            name="referente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referenciada_set",
                to="sigad.classe",
                verbose_name="Classe Referente",
            ),
        ),
    ]
