# Generated by Django 5.2.14 on 2026-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0017_alter_relacionamentoentreclasses_ordem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="pntp_servico",
            field=models.BooleanField(
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                verbose_name="Classe do PNTP Serviço",
            ),
        ),
    ]
