# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0018_auto_20171010_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Permissão'),
        ),
    ]
