# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0019_auto_20171203_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='sigad.Classe', verbose_name='Containers'),
        ),
        migrations.AddField(
            model_name='documento',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='sigad.Documento', verbose_name='Containers'),
        ),
        migrations.AddField(
            model_name='referenciaentredocumentos',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='sigad.ReferenciaEntreDocumentos', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='template_classe',
            field=models.IntegerField(choices=[(1, 'Listagem Simples em Linha'), (2, 'Galeria Pública de Albuns'), (3, 'Página dos Parlamentares'), (4, 'Página individual de Parlamentar'), (5, 'Banco de Imagens')], default=1, verbose_name='Template para a Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (0, 'Público'), (99, 'Privado')], default=99, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Documento'), (10, 'Banco de Imagem'), (20, 'Galeria Pública'), (700, 'Container Simples'), (701, 'Container Extendido'), (100, 'Texto'), (800, 'Vídeo'), (850, 'Áudio'), (900, 'Imagem'), (901, 'Galeria de Imagens')], default=0, verbose_name='Tipo da Parte do Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (0, 'Público'), (99, 'Privado')], default=99, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (0, 'Público'), (99, 'Privado')], default=99, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='visibilidade',
            field=models.IntegerField(choices=[(1, 'Restrito'), (0, 'Público'), (99, 'Privado')], default=99, verbose_name='Visibilidade'),
        ),
    ]
