# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models
from unipath import Path
import django.core.files.storage
import django.db.models.deletion

import cmj.sigad.models
import cmj.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0020_auto_20171208_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='nodes', to='sigad.Classe', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='alinhamento',
            field=models.IntegerField(choices=[(0, 'Alinhamento Esquerdo'), (1, 'Alinhamento Completo'), (
                2, 'Alinhamento Direito'), (3, 'Alinhamento Centralizado')], default=0, verbose_name='Alinhamento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='nodes', to='sigad.Documento', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='nodes', to='sigad.ReferenciaEntreDocumentos', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='versaodemidia',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='DO_NOT_USE', location=Path(
                '/sistemas/envs/cmj/media_protected')), upload_to=cmj.sigad.models.media_path, validators=[cmj.utils.restringe_tipos_de_arquivo_midias], verbose_name='Mídia'),
        ),
    ]
