# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0021_auto_20171217_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='Permissão'),
        ),
    ]
