# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0022_auto_20171217_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='referenciado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citado_em', to='sigad.Documento', verbose_name='Documento Referenciado'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='referente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cita', to='sigad.Documento', verbose_name='Documento Referente'),
        ),
    ]
