# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0025_auto_20171219_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciaentredocumentos',
            name='autor',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='referenciaentredocumentos',
            name='descricao',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição'),
        ),
    ]
