# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0027_auto_20171226_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciaentredocumentos',
            options={'ordering': ('referente', 'ordem')},
        ),
    ]
