# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0028_auto_20180122_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='extra_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=None, null=True, verbose_name='Dados Extras'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='template_classe',
            field=models.IntegerField(choices=[(1, 'Listagem em Linha'), (2, 'Galeria Albuns'), (3, 'Página dos Parlamentares'), (4, 'Página individual de Parlamentar'), (5, 'Banco de Imagens'), (6, 'Galeria de Áudios'), (7, 'Galeria de Vídeos')], default=1, verbose_name='Template para a Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='tipo_doc_padrao',
            field=models.IntegerField(choices=[(0, 'Notícia'), (5, 'Documento'), (10, 'Banco de Imagem'), (20, 'Galeria Pública'), (30, 'Áudio Notícia'), (40, 'Vídeo Notícia')], default=5, verbose_name='Tipo Padrão para Documentos desta Classe'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Notícia'), (5, 'Documento'), (10, 'Banco de Imagem'), (20, 'Galeria Pública'), (30, 'Áudio Notícia'), (40, 'Vídeo Notícia'), (700, 'Container Simples'), (701, 'Container Extendido'), (100, 'Texto'), (800, 'Vídeo'), (850, 'Áudio'), (900, 'Imagem'), (901, 'Galeria de Imagens')], default=5, verbose_name='Tipo da Parte do Documento'),
        ),
    ]
