# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0029_auto_20180201_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='listar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Aparecer nas Listagens'),
        ),
        migrations.AddField(
            model_name='documento',
            name='listar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Aparecer nas Listagens'),
        ),
        migrations.AddField(
            model_name='permissionsuserclasse',
            name='listar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Aparecer nas Listagens'),
        ),
        migrations.AddField(
            model_name='permissionsuserdocumento',
            name='listar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Aparecer nas Listagens'),
        ),
    ]
