# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0030_auto_20180205_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaPublicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=250)),
                ('nome', models.CharField(default='', max_length=250)),
                ('documentos', models.ManyToManyField(blank=True, related_name='caixapublicacao_set', to='sigad.Documento', verbose_name='Documentos da Caixa de Públicação')),
            ],
            options={
                'verbose_name': 'Caixa de Publicação',
                'verbose_name_plural': 'Caixas de Publicação',
            },
        ),
    ]
