# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0031_caixapublicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixapublicacao',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_query_name='caixapublicacao_set', to='sigad.Documento', verbose_name='Documentos da Caixa de Públicação'),
        ),
    ]
