# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0032_auto_20180206_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaPublicacaoClasse',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'Caixas de Publicação',
                'verbose_name': 'Caixa de Publicação',
                'proxy': True,
            },
            bases=('sigad.caixapublicacao',),
        ),
        migrations.AddField(
            model_name='caixapublicacao',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caixapublicacao_set', to='sigad.Classe', verbose_name='Classes'),
        ),
    ]
