# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0035_auto_20180215_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='capa',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='sigad.Documento', verbose_name='Capa da Classe'),
        ),
    ]
