# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0041_remove_caixapublicacao_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixapublicacao',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_query_name='caixapublicacao_set', to='sigad.Documento', verbose_name='Documentos da Caixa de Públicação'),
        ),
    ]
