# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0043_remove_caixapublicacao_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaPublicacaoRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('caixapublicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigad.CaixaPublicacao')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigad.Documento')),
            ],
            options={
                'verbose_name_plural': 'Documentos da Caixa de Publicação',
                'verbose_name': 'Documentos da Caixa de Publicação',
                'ordering': ('ordem', '-documento'),
            },
        ),
        migrations.AddField(
            model_name='caixapublicacao',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_query_name='caixapublicacao_set', through='sigad.CaixaPublicacaoRelationship', to='sigad.Documento', verbose_name='Documentos da Caixa de Públicação'),
        ),
        migrations.AlterUniqueTogether(
            name='caixapublicacaorelationship',
            unique_together=set([('caixapublicacao', 'documento')]),
        ),
    ]
