# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 13:53
from __future__ import unicode_literals

import cmj.sigad.models
import cmj.utils
import django.core.files.storage
from django.db import migrations, models

from unipath import Path

class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0044_auto_20180516_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versaodemidia',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='DO_NOT_USE', location=Path('/home/leandro/desenvolvimento/envs/cmj/media_protected')), upload_to=cmj.sigad.models.media_path, validators=[cmj.utils.restringe_tipos_de_arquivo_midias], verbose_name='Mídia'),
        ),
    ]
