# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0045_auto_20180914_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Notícia'), (5, 'Documento'), (10, 'Banco de Imagem'), (20, 'Galeria Pública'), (30, 'Áudio Notícia'), (40, 'Vídeo Notícia'), (700, 'Container Simples'), (701, 'Container Extendido'), (750, 'Container de Imagens para Arquivo PDF'), (100, 'Texto'), (200, 'Arquivo'), (800, 'Vídeo'), (850, 'Áudio'), (900, 'Imagem'), (901, 'Galeria de Imagens')], default=5, verbose_name='Tipo da Parte do Documento'),
        ),
    ]
