# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0047_auto_20190322_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_short', models.TextField(blank=True, db_index=True, default=None, null=True, verbose_name='Link Curto')),
                ('url_long', models.TextField(db_index=True, verbose_name='Link Longo')),
            ],
            options={
                'verbose_name': 'UrlShortener',
                'verbose_name_plural': 'UrlShortener',
                'ordering': ('url_short',),
            },
        ),
        migrations.RemoveField(
            model_name='classe',
            name='url_short',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='url_short',
        ),
        migrations.RemoveField(
            model_name='referenciaentredocumentos',
            name='url_short',
        ),
        migrations.AlterUniqueTogether(
            name='urlshortener',
            unique_together=set([('url_short', 'url_long')]),
        ),
    ]
