# Generated by Django 2.2.12 on 2020-05-20 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0050_versaodemidia_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ('public_date',), 'permissions': (('view_documento_show', 'Visualização dos Metadados do Documento.'), ('view_documento_media', 'Visualização das mídias do Documento')), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='caixapublicacao',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixapublicacao_set', to='sigad.Classe', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='capa',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa', to='sigad.Documento', verbose_name='Capa da Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='sigad.Classe', verbose_name='Filhos'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='parlamentar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classe_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='sigad.Classe', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='classe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_set', to='sigad.Classe', verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='sigad.Documento', verbose_name='Filhos'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='sigad.Documento', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='documento',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midia', to='sigad.Documento', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='revisao',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midia', to='sigad.Revisao', verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions_user_set', to='sigad.Classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Permission', verbose_name='Permissão'),
        ),
        migrations.AlterField(
            model_name='permissionsuserclasse',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions_user_set', to='sigad.Documento', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Permission', verbose_name='Permissão'),
        ),
        migrations.AlterField(
            model_name='permissionsuserdocumento',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='sigad.ReferenciaEntreDocumentos', verbose_name='Filhos'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='sigad.ReferenciaEntreDocumentos', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='versaodemidia',
            name='midia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sigad.Midia', verbose_name='Mídia Versionada'),
        ),
        migrations.AlterField(
            model_name='versaodemidia',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
