# Generated by Django 2.2.13 on 2020-06-22 14:01

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0051_auto_20200520_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='link_absoluto',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Link Absoluto'),
        ),
        migrations.CreateModel(
            name='ShortRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_set', to='sigad.UrlShortener', verbose_name='UrlShortner')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
