# Generated by Django 2.2.13 on 2020-06-23 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0052_auto_20200622_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
