# Generated by Django 2.2.13 on 2020-06-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0053_urlshortener_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='automatico',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Link Automático'),
        ),
        migrations.AlterField(
            model_name='shortredirect',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_set', to='sigad.UrlShortener', verbose_name='UrlShortner'),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
