# Generated by Django 2.2.24 on 2021-08-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auditlog_visibilidade'),
        ('sigad', '0055_remove_midia_revisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='auditlog',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='midia', to='core.AuditLog', verbose_name='AuditLog'),
        ),
    ]
