# Generated by Django 2.2.24 on 2021-08-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0056_midia_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revisao',
        ),
    ]
