# Generated by Django 2.2.24 on 2021-09-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0057_delete_revisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='documento',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='referenciaentredocumentos',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Apelido'),
        ),
    ]
