# Generated by Django 2.2.27 on 2022-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0058_auto_20210927_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='list_in_inf',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Listar no Acesso à Informação'),
        ),
        migrations.AddField(
            model_name='classe',
            name='list_in_mapa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Listar no mapa do site'),
        ),
        migrations.AddField(
            model_name='classe',
            name='list_in_menu',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Listar no Menu Geral'),
        ),
        migrations.AddField(
            model_name='classe',
            name='url_redirect',
            field=models.CharField(default='', max_length=1024, verbose_name='URL de redirecionamento'),
        ),
    ]
