# Generated by Django 2.2.28 on 2023-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0061_auto_20230327_1308'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['-public_date', '-created'], name='sigad_docum_public__f09b07_idx'),
        ),
    ]
