# Generated by Django 2.2.28 on 2023-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0062_auto_20230508_0942'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['-public_date'], name='sigad_docum_public__c8f0ef_idx'),
        ),
    ]
