# Generated by Django 2.2.28 on 2023-11-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0063_auto_20230508_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='menu_lateral',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Montar Menu Lateral'),
        ),
    ]
