# Generated by Django 2.2.28 on 2023-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0064_classe_menu_lateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='alinhamento',
            field=models.IntegerField(choices=[(0, 'Alinhamento Esquerdo'), (1, 'Alinhamento Completo'), (2, 'Alinhamento Direito'), (3, 'Alinhamento Centralizado'), (4, 'Alinhamento Completo - Render Large')], default=0, verbose_name='Alinhamento'),
        ),
    ]
