# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0065_auto_20231214_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixapublicacao',
            options={'ordering': ['id'], 'verbose_name': 'Caixa de Publicação', 'verbose_name_plural': 'Caixas de Publicação'},
        ),
        migrations.AlterModelOptions(
            name='caixapublicacaoclasse',
            options={'ordering': ['id'], 'verbose_name': 'Caixa de Publicação', 'verbose_name_plural': 'Caixas de Publicação'},
        ),
        migrations.AlterModelOptions(
            name='midia',
            options={'ordering': ['id'], 'verbose_name': 'Mídia Versionada', 'verbose_name_plural': 'Mídias Versionadas'},
        ),
        migrations.AlterModelOptions(
            name='permissionsuserclasse',
            options={'ordering': ['id'], 'verbose_name': 'Permissão de Usuário para Classe', 'verbose_name_plural': 'Permissões de Usuários para Classes'},
        ),
        migrations.AlterModelOptions(
            name='permissionsuserdocumento',
            options={'ordering': ['id'], 'verbose_name': 'Permissão de Usuário para Documento', 'verbose_name_plural': 'Permissões de Usuários para Documentos'},
        ),
    ]
