# Generated by Django 4.2.16 on 2024-10-03 20:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0066_auto_20240325_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='related_classes',
            field=models.ManyToManyField(blank=True, to='sigad.classe', verbose_name='Classes Relacionadas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='related_classes',
            field=models.ManyToManyField(blank=True, to='sigad.documento', verbose_name='Classes Relacionadas'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='referenciaentredocumentos',
            name='related_classes',
            field=models.ManyToManyField(blank=True, to='sigad.referenciaentredocumentos', verbose_name='Classes Relacionadas'),
        ),
        migrations.AlterField(
            model_name='shortredirect',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='versaodemidia',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
