# Generated by Django 4.2.18 on 2025-02-01 17:49

from django.db import migrations
from django.utils import timezone
from cmj.sigad.models import CLASSE_REDIRECT


def change_config_classes(apps, schema_editor):
    Classe = apps.get_model('sigad', 'Classe')

    now = timezone.localtime()
    for classe in Classe.objects.all():
        classe.list_in_menu = False
        classe.list_in_mapa = False
        if classe.slug.startswith('informacao'):
            classe.list_in_mapa = True

        if classe.slug == 'parlamentar':
            classe.list_in_mapa = True

        if classe.slug.startswith('parlamentar/'):
            if classe.parlamentar.mandato_set.filter(
                legislatura__data_inicio__lte=now,
                legislatura__data_fim__gte=now
            ).exists():
                classe.list_in_mapa = True

        if classe.url_redirect:
            classe.perfil = CLASSE_REDIRECT
        classe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0067_alter_classe_metadata_alter_classe_related_classes_and_more'),
    ]

    operations = [
        migrations.RunPython(change_config_classes),

    ]
