# Generated by Django 4.2.18 on 2025-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0068_auto_20250201_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='perfil',
            field=models.IntegerField(choices=[(0, 'Classe Estrutural'), (1, 'Classe de Conteúdo'), (2, 'Classe Mista'), (98, 'Classe de Redirecionamento via URL'), (99, 'Classe de Redirecionamento via Views')], default=0, verbose_name='Perfil da Classe'),
        ),
    ]
