# Generated by Django 4.2.18 on 2025-02-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0069_alter_classe_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='url_redirect',
            field=models.CharField(db_index=True, default='', max_length=1024, verbose_name='URL de redirecionamento'),
        ),
    ]
