# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0070_alter_classe_url_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixapublicacao',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_query_name='caixapublicacao_set', through='sigad.CaixaPublicacaoRelationship', through_fields=('caixapublicacao', 'documento'), to='sigad.documento', verbose_name='Documentos da Caixa de Públicação'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documentos_citados',
            field=models.ManyToManyField(through='sigad.ReferenciaEntreDocumentos', through_fields=('referente', 'referenciado'), to='sigad.documento'),
        ),
    ]
