# Generated by Django 5.2.1 on 2025-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0071_alter_caixapublicacao_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='subtitle',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='subtitle',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='referenciaentredocumentos',
            name='subtitle',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Subtítulo'),
        ),
    ]
