# Generated by Django 5.2.1 on 2025-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0072_classe_subtitle_documento_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='atricon',
            field=models.CharField(default='', max_length=10, verbose_name='Código Atricon'),
        ),
    ]
