# Generated by Django 5.2.1 on 2025-05-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigad', '0073_classe_atricon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='atricon',
            field=models.CharField(default='', max_length=10, verbose_name='Atricon'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='tipo_doc_padrao',
            field=models.IntegerField(choices=[(0, 'Notícias'), (5, 'Documento'), (10, 'Banco de Imagem'), (20, 'Galeria Pública'), (30, 'Áudio Notícia'), (40, 'Vídeo Notícia')], default=5, verbose_name='Tipo Padrão para Docs da Classe'),
        ),
    ]
