# Generated by Django 5.2.11 on 2026-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0074_alter_classe_atricon_alter_classe_tipo_doc_padrao"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="classes_relacionadas",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="documentos_relacionados_set",
                to="sigad.classe",
                verbose_name="Classes Relacionadas",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="template_classe",
            field=models.IntegerField(
                choices=[
                    (1, "Listagem em Linha"),
                    (2, "Galeria Albuns"),
                    (3, "Página dos Parlamentares"),
                    (4, "Página individual de Parlamentar"),
                    (5, "Banco de Imagens"),
                    (6, "Galeria de Áudios"),
                    (7, "Galeria de Vídeos"),
                    (99, "Documento Específico"),
                    (500, "Subsites"),
                    (999, "Mapa do Site"),
                ],
                default=1,
                verbose_name="Template para a Classe",
            ),
        ),
        migrations.AlterField(
            model_name="classe",
            name="template_doc_padrao",
            field=models.IntegerField(
                choices=[
                    (1, "Notícia Pública"),
                    (2, "Galeria de Imagens"),
                    (501, "Capa de Subsite"),
                ],
                default=1,
                verbose_name="Template para o Documento",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="template_doc",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Notícia Pública"),
                    (2, "Galeria de Imagens"),
                    (501, "Capa de Subsite"),
                ],
                default=None,
                null=True,
                verbose_name="Template para o Documento",
            ),
        ),
    ]
