# Generated by Django 5.2.11 on 2026-03-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigad", "0075_documento_classes_relacionadas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="classes_relacionadas",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="documentos_relacionados_set",
                to="sigad.classe",
                verbose_name="Classes Relacionadas",
            ),
        ),
    ]
