FROM leandrojatai/portalcmj:base.0002

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

#COPY requirements/* $HOME
#RUN pip install -r dev-requirements.txt

#RUN pip install pgvector
#RUN pip install sentence-transformers

RUN adduser --home=/var/cmjatai/cmj --disabled-password --comment "" --shell=/bin/bash cmj
RUN mkdir -p /var/cmjatai/cmj
RUN mkdir -p /var/cmjatai/cmj_media
USER cmj
WORKDIR /var/cmjatai/cmj/

ENV DEBIAN_FRONTEND=teletype

EXPOSE 9000/tcp

VOLUME ["/var/cmjatai/cmj_media", "/var/cmjatai/cmj"]

CMD ["/var/cmjatai/cmj/docker/start-dev.sh"]
