FROM leandrojatai/portalcmj:base.0006

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir setuptools

COPY requirements/requirements.txt $HOME
RUN pip install -r requirements.txt

COPY requirements/ia-requirements.txt $HOME
RUN pip install -r ia-requirements.txt


ENV HOME=/var/cmjatai/cmj
RUN mkdir -p /var/cmjatai/cmj
RUN mkdir -p /var/cmjatai/cmj_media

RUN addgroup --gid 1001 cmj
RUN adduser --home=/var/cmjatai/cmj --uid 1001 --gid 1001 --disabled-password --comment "" --shell=/bin/bash cmj
RUN chown -R cmj:cmj /var/cmjatai
USER cmj

WORKDIR ${HOME}

ENV DEBIAN_FRONTEND=teletype

EXPOSE 9000/tcp

VOLUME ["/var/cmjatai/cmj_media", "/var/cmjatai/cmj"]

CMD ["/var/cmjatai/cmj/docker/start-dev.sh"]
