name: portalcmj
services:
  cmjredis:
    image: redis:alpine
    container_name: cmjredis
    restart: no
    labels:
       NAME: "cmjredis"
    volumes:
      - credis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - cmj-net
  cmjsolr:
    image: solr:9.5
    restart: no
    command: bin/solr start -c -f
    container_name: cmjsolr
    labels:
        NAME: "cmjsolr"
    volumes:
      - csolr_data:/var/solr
      - csolr_configsets:/opt/solr/server/solr/configsets
    ports:
      - "127.0.0.1:8983:8983"
      - "127.0.0.1:9983:9983"
    networks:
      - cmj-net
  cmjfront:
    build:
      context: ../_frontend/v1/
      dockerfile: ../../docker/DockerfileFrontDev
    #command: yarn build
    restart: no
    container_name: cmjfront
    labels:
       NAME: "cmjfront"
    volumes:
      - ../:/var/cmjatai/cmj
    networks:
      - cmj-net
    ports:
      - "8080:8080"
      #- "10.3.163.200:8080:8080"
      #- "192.168.15.8:8080:8080"
      #- "127.0.0.1:8080:8080"
  cmjdb:
    image: pgvector/pgvector:0.8.0-pg15
    restart: always
    container_name: cmjpostgres
    labels:
        NAME: "cmjpostgres"
    environment:
      POSTGRES_PASSWORD: cmj
      POSTGRES_USER: cmj
      POSTGRES_DB: cmj
      PGDATA : /var/lib/postgresql/data/
    volumes:
      - cmjdb_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - cmj-net
  cmj:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.Dev
    container_name: cmj
    user: "root:root"
    labels:
      NAME: "cmj"
    restart: no
    environment:
      DEBUG: 'True'
      USE_SOLR: 'True'
      SOLR_COLLECTIONS: portalcmj_cmj,portalcmj_arq
      SOLR_URL: http://solr:solr@cmjsolr:8983
      IS_ZK_EMBEDDED: 'True'
      TZ: America/Sao_Paulo
    volumes:
      - /mnt/volumes/cmj_media:/var/cmjatai/cmj_media
      - ../:/var/cmjatai/cmj
    depends_on:
      - cmjredis
      - cmjfront
      - cmjsolr
    ports:
      - "9000:9000"
    networks:
      - cmj-net
networks:
  cmj-net:
    name: cmj-net
    driver: bridge
volumes:
  cmjdb_data:
  csolr_data:
  csolr_configsets:
  credis_data:
