# Generated by Django 5.2.12 on 2026-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cronometro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("I", "Start"), ("R", "Reset"), ("S", "Stop")],
                        default="S",
                        max_length=1,
                        verbose_name="Status do cronômetro",
                    ),
                ),
                (
                    "data_cronometro",
                    models.DateField(verbose_name="Data do cronômetro"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("A", "Aparte"),
                            ("D", "Discurso"),
                            ("O", "Ordem do dia"),
                            ("C", "Considerações finais"),
                        ],
                        max_length=1,
                        verbose_name="Tipo Cronômetro",
                    ),
                ),
            ],
            options={
                "ordering": ("-data_cronometro",),
            },
        ),
        migrations.CreateModel(
            name="Painel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aberto",
                    models.BooleanField(default=False, verbose_name="Abrir painel"),
                ),
                ("data_painel", models.DateField(verbose_name="Data painel")),
                (
                    "mostrar",
                    models.CharField(
                        choices=[
                            ("C", "Completo"),
                            ("P", "Parlamentares"),
                            ("V", "Votação"),
                            ("M", "Mensagem"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ("-data_painel",),
            },
        ),
    ]
