# Generated by Django 2.2.28 on 2023-12-14 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_cronometro_last_stop_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PainelConfig',
        ),
        migrations.AlterModelOptions(
            name='cronometro',
            options={'ordering': ('-data_cronometro',)},
        ),
        migrations.AlterModelOptions(
            name='painel',
            options={'ordering': ('-data_painel',)},
        ),
        migrations.RemoveField(
            model_name='cronometro',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='cronometro',
            name='duracao_cronometro',
        ),
        migrations.RemoveField(
            model_name='cronometro',
            name='last_stop_duration',
        ),
        migrations.RemoveField(
            model_name='cronometro',
            name='ordenacao',
        ),
        migrations.RemoveField(
            model_name='cronometro',
            name='ultima_alteracao_status',
        ),
        migrations.AddField(
            model_name='cronometro',
            name='data_cronometro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do cronômetro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='status',
            field=models.CharField(choices=[('I', 'Start'), ('R', 'Reset'), ('S', 'Stop')], default='S', max_length=1, verbose_name='Status do cronômetro'),
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='tipo',
            field=models.CharField(choices=[('A', 'Aparte'), ('D', 'Discurso'), ('O', 'Ordem do dia'), ('C', 'Considerações finais')], max_length=1, verbose_name='Tipo Cronômetro'),
        ),
    ]
