# Generated by Django 5.2.3 on 2025-09-29 01:22

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField(help_text='Duração planejada do cronômetro')),
                ('state', models.CharField(choices=[('stopped', 'Parado'), ('running', 'Executando'), ('paused', 'Pausado'), ('finished', 'Finalizado')], default='stopped', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stop_parent_on_finish', models.BooleanField(default=False, help_text='Se True, para o cronômetro pai quando este terminar')),
                ('reduce_parent_time', models.BooleanField(default=False, help_text='Se True, reduz simultaneamente o tempo do cronômetro pai')),
                ('accumulated_time', models.DurationField(default=datetime.timedelta(0))),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='panelset.timer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Iniciado'), ('paused', 'Pausado'), ('resumed', 'Retomado'), ('stopped', 'Parado'), ('finished', 'Finalizado'), ('reset', 'Resetado')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='panelset.timer')),
                ('triggered_by_child', models.ForeignKey(blank=True, help_text='Cronômetro filho que causou este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to='panelset.timer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
