# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0029_auto_20200128_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexonormajuridica',
            name='_paginas',
            field=models.IntegerField(default=0, verbose_name='Número de Páginas'),
        ),
        migrations.AddField(
            model_name='normajuridica',
            name='_paginas',
            field=models.IntegerField(default=0, verbose_name='Número de Páginas'),
        ),
        migrations.AlterField(
            model_name='anexonormajuridica',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_set', to='norma.NormaJuridica', verbose_name='Norma Juridica'),
        ),
    ]
