# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 19:38
from __future__ import unicode_literals

from django.db import migrations
import sapl.norma.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0030_auto_20200131_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='texto_integral',
            field=sapl.utils.PortalFileField(blank=True, max_length=512, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.norma.models.norma_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
    ]
