# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-30 01:46
from __future__ import unicode_literals

import cmj.utils
from django.db import migrations
import sapl.norma.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0032_normajuridica_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexonormajuridica',
            name='anexo_arquivo',
            field=sapl.utils.PortalFileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.norma.models.norma_upload_path, validators=[cmj.utils.restringe_tipos_de_arquivo_midias], verbose_name='Arquivo Anexo'),
        ),
    ]
