# Generated by Django 2.2.16 on 2020-09-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0034_anexonormajuridica_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexonormajuridica',
            options={'verbose_name': 'Anexo da Norma Jurídica', 'verbose_name_plural': 'Anexos da Norma Jurídica'},
        ),
        migrations.AlterField(
            model_name='anexonormajuridica',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_set', to='norma.NormaJuridica', verbose_name='Norma Jurídica'),
        ),
    ]
