# Generated by Django 2.2.16 on 2020-10-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0035_auto_20200916_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorianorma',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.NormaJuridica', verbose_name='Norma Jurídica'),
        ),
    ]
