# Generated by Django 2.2.20 on 2021-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0038_auto_20210302_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponormajuridica',
            name='origem_processo_legislativo',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Possui Origem no Processo Legislativo?'),
        ),
    ]
