# Generated by Django 2.2.28 on 2024-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0044_auto_20240103_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='mostrar_deliberacao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Mostrar Deliberacao?'),
        ),
    ]
