# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0045_normajuridica_mostrar_deliberacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislacaocitada',
            options={'ordering': ['id'], 'verbose_name': 'Legislação', 'verbose_name_plural': 'Legislações'},
        ),
        migrations.AlterModelOptions(
            name='normaestatisticas',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tipovinculonormajuridica',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Vínculo entre Normas Jurídicas', 'verbose_name_plural': 'Tipos de Vínculos entre Normas Jurídicas'},
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='mostrar_deliberacao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Mostrar Deliberação?'),
        ),
    ]
