# Generated by Django 4.2.16 on 2024-10-03 20:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0047_auto_20240508_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexonormajuridica',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='complemento',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Complementar ?'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='tiponormajuridica',
            name='origem_processo_legislativo',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=True, null=True, verbose_name='Possui Origem no Processo Legislativo?'),
        ),
    ]
