# Generated by Django 4.2.19 on 2025-04-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0049_alter_anexonormajuridica_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normajuridica_set', to='norma.tiponormajuridica', verbose_name='Tipo da Norma Jurídica'),
        ),
    ]
