# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_autor_operadores'),
        ('norma', '0050_alter_normajuridica_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='autores',
            field=models.ManyToManyField(through='norma.AutoriaNorma', through_fields=('norma', 'autor'), to='base.autor'),
        ),
    ]
