# Generated by Django 5.2.3 on 2025-09-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0051_alter_normajuridica_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='sufixo_urlize',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Sufixo URLize'),
        ),
    ]
