# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.utils_files
import django.core.serializers.json
import django.db.models.deletion
import sapl.comissoes.models
import sapl.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoComissao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Cargo")),
                (
                    "unico",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Único",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo de Comissão",
                "verbose_name_plural": "Cargos de Comissão",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Comissao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("sigla", models.CharField(max_length=10, verbose_name="Sigla")),
                ("data_criacao", models.DateField(verbose_name="Data de Criação")),
                (
                    "data_extincao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Extinção"
                    ),
                ),
                (
                    "apelido_temp",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apelido"
                    ),
                ),
                (
                    "data_instalacao_temp",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Instalação"
                    ),
                ),
                (
                    "data_final_prevista_temp",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Prevista Término"
                    ),
                ),
                (
                    "data_prorrogada_temp",
                    models.DateField(blank=True, null=True, verbose_name="Novo Prazo"),
                ),
                (
                    "data_fim_comissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Término"
                    ),
                ),
                (
                    "secretario",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Secretário"
                    ),
                ),
                (
                    "telefone_reuniao",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Tel. Sala Reunião"
                    ),
                ),
                (
                    "endereco_secretaria",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Endereço Secretaria"
                    ),
                ),
                (
                    "telefone_secretaria",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Tel. Secretaria"
                    ),
                ),
                (
                    "fax_secretaria",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Fax Secretaria"
                    ),
                ),
                (
                    "agenda_reuniao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Data/Hora Reunião"
                    ),
                ),
                (
                    "local_reuniao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Local Reunião"
                    ),
                ),
                ("finalidade", models.TextField(blank=True, verbose_name="Finalidade")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, verbose_name="E-mail"
                    ),
                ),
                (
                    "unidade_deliberativa",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Unidade Deliberativa",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Comissão Ativa?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comissão",
                "verbose_name_plural": "Comissões",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoAcessorio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "data",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Data"
                    ),
                ),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("ementa", models.TextField(blank=True, verbose_name="Ementa")),
                ("indexacao", models.TextField(blank=True)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.comissoes.models.anexo_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Texto Integral",
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Data"),
                ),
            ],
            options={
                "verbose_name": "Documento Acessório",
                "verbose_name_plural": "Documentos Acessórios",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
            ],
            options={
                "verbose_name": "Período de composição de Comissão",
                "verbose_name_plural": "Períodos de composição de Comissão",
                "ordering": ["-data_inicio", "-data_fim"],
            },
        ),
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome da Reunião"),
                ),
                (
                    "tema",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Tema da Reunião"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "hora_inicio",
                    models.TimeField(
                        null=True, verbose_name="Horário de Início (hh:mm)"
                    ),
                ),
                (
                    "hora_fim",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Término (hh:mm)"
                    ),
                ),
                (
                    "local_reuniao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Local da Reunião"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "url_audio",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL do Arquivo de Áudio (Formatos MP3 / AAC)",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL do Arquivo de Vídeo (Formatos MP4 / FLV / WebM)",
                    ),
                ),
                (
                    "upload_pauta",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.comissoes.models.pauta_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Pauta da Reunião",
                    ),
                ),
                (
                    "upload_ata",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.comissoes.models.ata_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Ata da Reunião",
                    ),
                ),
                (
                    "upload_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.comissoes.models.anexo_upload_path,
                        verbose_name="Anexo da Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reunião de Comissão",
                "verbose_name_plural": "Reuniões de Comissão",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoComissao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "natureza",
                    models.CharField(
                        choices=[("T", "Temporária"), ("P", "Permanente")],
                        max_length=1,
                        verbose_name="Natureza",
                    ),
                ),
                ("sigla", models.CharField(max_length=10, verbose_name="Sigla")),
                (
                    "dispositivo_regimental",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Dispositivo Regimental"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Comissão",
                "verbose_name_plural": "Tipos de Comissão",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Composicao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comissao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comissoes.comissao",
                        verbose_name="Comissão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composição de Comissão",
                "verbose_name_plural": "Composições de Comissão",
                "ordering": ["periodo"],
            },
        ),
        migrations.CreateModel(
            name="Participacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titular",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Titular",
                    ),
                ),
                ("data_designacao", models.DateField(verbose_name="Data Designação")),
                (
                    "data_desligamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Desligamento"
                    ),
                ),
                (
                    "motivo_desligamento",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Motivo Desligamento"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Observação"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comissoes.cargocomissao",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "composicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participacao_set",
                        to="comissoes.composicao",
                        verbose_name="Composição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participação em Comissão",
                "verbose_name_plural": "Participações em Comissão",
                "ordering": ["id"],
            },
        ),
    ]
