# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comissoes", "0001_initial"),
        ("parlamentares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participacao",
            name="parlamentar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="parlamentares.parlamentar",
                verbose_name="Parlamentar",
            ),
        ),
        migrations.AddField(
            model_name="composicao",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comissoes.periodo",
                verbose_name="Período",
            ),
        ),
        migrations.AddField(
            model_name="reuniao",
            name="comissao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comissoes.comissao",
                verbose_name="Comissão",
            ),
        ),
        migrations.AddField(
            model_name="reuniao",
            name="periodo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comissoes.periodo",
                verbose_name="Periodo da Composicão da Comissão",
            ),
        ),
        migrations.AddField(
            model_name="documentoacessorio",
            name="reuniao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentoacessorio_set",
                to="comissoes.reuniao",
            ),
        ),
        migrations.AddField(
            model_name="comissao",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="comissoes.tipocomissao",
                verbose_name="Tipo",
            ),
        ),
    ]
