# Generated by Django 5.2.14 on 2026-05-29 10:34

import cmj.utils_files
import sapl.comissoes.models
import sapl.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comissoes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoacessorio",
            name="arquivo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.comissoes.models.anexo_upload_path,
                validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                verbose_name="Texto Integral",
            ),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="upload_anexo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.comissoes.models.anexo_upload_path,
                verbose_name="Anexo da Reunião",
            ),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="upload_ata",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.comissoes.models.ata_upload_path,
                validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                verbose_name="Ata da Reunião",
            ),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="upload_pauta",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.comissoes.models.pauta_upload_path,
                validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                verbose_name="Pauta da Reunião",
            ),
        ),
    ]
