# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-05 18:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0020_auto_20190712_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
