# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0021_auto_20200505_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargocomissao',
            options={'ordering': ['id'], 'verbose_name': 'Cargo de Comissão', 'verbose_name_plural': 'Cargos de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='documentoacessorio',
            options={'ordering': ['id'], 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='participacao',
            options={'ordering': ['id'], 'verbose_name': 'Participação em Comissão', 'verbose_name_plural': 'Participações em Comissão'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'ordering': ['id'], 'verbose_name': 'Reunião de Comissão', 'verbose_name_plural': 'Reuniões de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='tipocomissao',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Comissão', 'verbose_name_plural': 'Tipos de Comissão'},
        ),
    ]
