# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Página..',
                'verbose_name_plural': 'Páginas',
            },
            bases=('wagtailcore.page',),
        ),
    ]
