# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
    ]
