# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160615_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Página..', 'verbose_name_plural': 'Páginas'},
        ),
    ]
