# Generated by Django 5.2.9 on 2025-12-20 23:49

import cmj.mixins
import django.core.serializers.json
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True, verbose_name='Vetor de embedding')),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embeddings',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='search_embe_content_e04942_idx')],
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX embedding_hnsw_index
            ON search_embedding
            USING hnsw ((embedding::halfvec(3072)) halfvec_cosine_ops)
            WITH (m = 32, ef_construction = 128);
            """,
            reverse_sql="DROP INDEX embedding_hnsw_index;",
        ),

    ]
