# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.mixins
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.serializers.json
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("title", models.CharField(default="Nova Conversa", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_use_chat_module", "Usuário pode usar o módulo de chat")
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("model", "Model")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="search.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "chunk",
                    models.TextField(
                        blank=True, default="", verbose_name="Chunk de texto"
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Número de tokens"
                    ),
                ),
                (
                    "vetor",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        default=None,
                        dimensions=3072,
                        null=True,
                        verbose_name="Vetor de embedding",
                    ),
                ),
                (
                    "vetor1536",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True,
                        default=None,
                        dimensions=1536,
                        null=True,
                        verbose_name="Vetor de embedding 1536",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Vetor de busca full-text",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding",
                "verbose_name_plural": "Embeddings",
                "ordering": ("-id",),
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-updated_at"], name="search_chat_user_id_f4d0c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat", "timestamp"], name="search_chat_chat_id_e46ade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="search_embe_content_e04942_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["vetor1536"],
                m=16,
                name="embedding_vetor1536_hnsw",
                opclasses=["halfvec_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="embedding_search_vector_gin"
            ),
        ),
    ]
