# Generated by Django 4.2.18 on 2025-01-16 22:47

from django.db import migrations
from pgvector.django.extensions import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension()
    ]