# Generated by Django 5.2.9 on 2025-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='chunk',
            field=models.TextField(blank=True, default='', verbose_name='Chunk de texto'),
        ),
    ]
