# Generated by Django 5.2.9 on 2025-12-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_embedding_chunk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embedding',
            old_name='embedding',
            new_name='vetor',
        ),
        migrations.RunSQL(
            sql="ALTER INDEX embedding_hnsw_index RENAME TO vetor_hnsw_index;",
            reverse_sql="ALTER INDEX vetor_hnsw_index RENAME TO embedding_hnsw_index;"
        ),
    ]
