# Generated by Django 5.2.9 on 2025-12-21 16:21

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_embedding_embedding_vetor'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='count_tokens',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de tokens'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='vetor',
            field=pgvector.django.vector.VectorField(blank=True, default=None, dimensions=3072, null=True, verbose_name='Vetor de embedding'),
        ),
    ]
