# Generated by Django 5.2.9 on 2025-12-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_embedding_count_tokens_alter_embedding_vetor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embedding',
            old_name='count_tokens',
            new_name='total_tokens',
        ),
    ]
