# Generated by Django 5.2.9 on 2025-12-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'permissions': [('can_use_chat_module', 'Usuário pode usar o módulo de chat')]},
        ),
    ]
