# Generated by Django 5.2.9 on 2026-02-06 13:09

import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('search', '0006_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='vetor1536',
            field=pgvector.django.halfvec.HalfVectorField(blank=True, default=None, dimensions=1536, null=True, verbose_name='Vetor de embedding 1536'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vetor1536'], m=16, name='embedding_vetor1536_hnsw', opclasses=['halfvec_cosine_ops']),
        ),
    ]
