# Generated by Django 5.2.11 on 2026-02-25 15:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('search', '0007_embedding_vetor1536_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, default=None, null=True, verbose_name='Vetor de busca full-text'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='embedding_search_vector_gin'),
        ),
    ]
