# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import cmj.utils_files
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materia", "0001_initial"),
        ("parlamentares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumoOrdenacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primeiro", models.CharField(default="id_basica", max_length=50)),
                ("segundo", models.CharField(default="cont_mult", max_length=50)),
                ("terceiro", models.CharField(default="mesa_d", max_length=50)),
                ("quarto", models.CharField(default="lista_p", max_length=50)),
                ("quinto", models.CharField(default="exp", max_length=50)),
                ("sexto", models.CharField(default="mat_exp", max_length=50)),
                ("setimo", models.CharField(default="v_n_mat_exp", max_length=50)),
                ("oitavo", models.CharField(default="oradores_exped", max_length=50)),
                ("nono", models.CharField(default="lista_p_o_d", max_length=50)),
                ("decimo", models.CharField(default="mat_o_d", max_length=50)),
                (
                    "decimo_primeiro",
                    models.CharField(default="v_n_mat_o_d", max_length=50),
                ),
                (
                    "decimo_segundo",
                    models.CharField(default="oradores_o_d", max_length=50),
                ),
                (
                    "decimo_terceiro",
                    models.CharField(default="oradores_expli", max_length=50),
                ),
                (
                    "decimo_quarto",
                    models.CharField(default="ocorr_sessao", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Ordenação do Resumo de uma Sessão",
                "verbose_name_plural": "Ordenação do Resumo de uma Sessão",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoExpediente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Tipo")),
                (
                    "ordenacao",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ordenação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Expediente",
                "verbose_name_plural": "Tipos de Expediente",
                "ordering": ["ordenacao"],
            },
        ),
        migrations.CreateModel(
            name="TipoJustificativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Justificativa",
                "verbose_name_plural": "Tipos de Justificativa",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="TipoResultadoVotacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome do Tipo")),
                (
                    "natureza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Aprovado"),
                            ("R", "Rejeitado"),
                            ("P", "Pedidos de Prazo"),
                        ],
                        max_length=1,
                        verbose_name="Natureza do Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Resultado de Votação",
                "verbose_name_plural": "Tipos de Resultado de Votação",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoRetiradaPauta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Retirada de Pauta",
                "verbose_name_plural": "Tipos de Retirada de Pauta",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="TipoSessaoPlenaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, verbose_name="Descrição do Tipo"),
                ),
                (
                    "quorum_minimo",
                    models.PositiveIntegerField(verbose_name="Quórum mínimo"),
                ),
                (
                    "tipo_numeracao",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Quinzenal"),
                            (2, "Mensal"),
                            (10, "Anual"),
                            (11, "Sessão Legislativa"),
                            (12, "Legislatura"),
                            (99, "Numeração Única"),
                        ],
                        default=11,
                        verbose_name="Tipo de Numeração",
                    ),
                ),
                (
                    "tipogeral",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "Sessão"),
                            (20, "Reunião"),
                            (30, "Audiência"),
                            (40, "Jovem Vereador"),
                        ],
                        default=10,
                        verbose_name="Tipo Geral",
                    ),
                ),
                (
                    "gera_selo_votacao",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Gera Selo de Votação?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Sessão Plenária",
                "verbose_name_plural": "Tipos de Sessão Plenária",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ExpedienteMateria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ordem", models.DateField(verbose_name="Data da Sessão")),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("numero_ordem", models.PositiveIntegerField(verbose_name="Nº Ordem")),
                ("resultado", models.TextField(blank=True, verbose_name="Resultado")),
                (
                    "tipo_votacao",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Simbólica"),
                            (2, "Nominal"),
                            (3, "Secreta"),
                            (4, "Leitura"),
                        ],
                        default=1,
                        verbose_name="Tipo de votação",
                    ),
                ),
                (
                    "discussao_aberta",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Discussão aberta?",
                    ),
                ),
                (
                    "votacao_aberta",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Votação iniciada?",
                    ),
                ),
                (
                    "votacao_aberta_pedido_prazo",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Votação de Pedido de Prazo?",
                    ),
                ),
                (
                    "registro_aberto",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Registro de Votação Iniciado?",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.materialegislativa",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.expedientemateria",
                        verbose_name="Expendiente Principal",
                    ),
                ),
                (
                    "tramitacao",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tramitacao",
                        verbose_name="Situação quando pautada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria do Expediente",
                "verbose_name_plural": "Matérias do Expediente",
                "ordering": ("-sessao_plenaria", "numero_ordem"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrdemDia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ordem", models.DateField(verbose_name="Data da Sessão")),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("numero_ordem", models.PositiveIntegerField(verbose_name="Nº Ordem")),
                ("resultado", models.TextField(blank=True, verbose_name="Resultado")),
                (
                    "tipo_votacao",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Simbólica"),
                            (2, "Nominal"),
                            (3, "Secreta"),
                            (4, "Leitura"),
                        ],
                        default=1,
                        verbose_name="Tipo de votação",
                    ),
                ),
                (
                    "discussao_aberta",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Discussão aberta?",
                    ),
                ),
                (
                    "votacao_aberta",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Votação iniciada?",
                    ),
                ),
                (
                    "votacao_aberta_pedido_prazo",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Votação de Pedido de Prazo?",
                    ),
                ),
                (
                    "registro_aberto",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Registro de Votação Iniciado?",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.materialegislativa",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="childs",
                        to="sessao.ordemdia",
                        verbose_name="Ordem Dia Principal",
                    ),
                ),
                (
                    "tramitacao",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tramitacao",
                        verbose_name="Situação quando pautada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria da Ordem do Dia",
                "verbose_name_plural": "Matérias da Ordem do Dia",
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistroLeitura",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="IP"
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Data/Hora"
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.expedientemateria",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.ordemdia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura",
                "verbose_name_plural": "Leituras",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SessaoPlenaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "cod_andamento_sessao",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "painel_aberto",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Painel está aberto?"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Título"
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Abertura")),
                (
                    "hora_inicio",
                    models.CharField(max_length=5, verbose_name="Horário (hh:mm)"),
                ),
                (
                    "hora_fim",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Horário (hh:mm)"
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Encerramento"
                    ),
                ),
                (
                    "url_audio",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Áudio (Formatos MP3 / AAC)",
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True,
                        max_length=150,
                        verbose_name="URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)",
                    ),
                ),
                (
                    "upload_pauta",
                    sapl.utils.PortalFileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.pauta_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Pauta da Sessão",
                    ),
                ),
                (
                    "upload_ata",
                    sapl.utils.PortalFileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.ata_upload_path,
                        validators=[cmj.utils_files.restringe_tipos_de_arquivo_txt],
                        verbose_name="Ata da Sessão",
                    ),
                ),
                (
                    "upload_anexo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.anexo_upload_path,
                        verbose_name="Anexo da Sessão",
                    ),
                ),
                (
                    "iniciada",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        null=True,
                        verbose_name="Sessão iniciada?",
                    ),
                ),
                (
                    "finalizada",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        null=True,
                        verbose_name="Sessão finalizada?",
                    ),
                ),
                (
                    "selo_votacao_adicionado",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        null=True,
                        verbose_name="Selo de Votação Adicionado?",
                    ),
                ),
                (
                    "interativa",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        null=True,
                        verbose_name="Sessão interativa",
                    ),
                ),
                (
                    "tema_solene",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Tema da Sessão Solene"
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Data"),
                ),
                (
                    "legislatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.legislatura",
                        verbose_name="Legislatura",
                    ),
                ),
                (
                    "sessao_legislativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.sessaolegislativa",
                        verbose_name="Sessão Legislativa",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessao.tiposessaoplenaria",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão Plenária",
                "verbose_name_plural": "Sessões Plenárias",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PresencaOrdemDia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença da Ordem do Dia",
                "verbose_name_plural": "Presenças da Ordem do Dia",
                "ordering": ["parlamentar__nome_parlamentar"],
            },
        ),
        migrations.AddField(
            model_name="ordemdia",
            name="sessao_plenaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessao.sessaoplenaria"
            ),
        ),
        migrations.CreateModel(
            name="OradorOrdemDia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "numero_ordem",
                    models.PositiveIntegerField(verbose_name="Ordem de pronunciamento"),
                ),
                (
                    "url_discurso",
                    models.URLField(
                        blank=True, max_length=150, verbose_name="URL Vídeo"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Observação"
                    ),
                ),
                (
                    "upload_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.anexo_upload_path,
                        verbose_name="Anexo do Orador",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orador da Ordem do Dia",
                "verbose_name_plural": "Oradores da Ordem do Dia",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OradorExpediente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "numero_ordem",
                    models.PositiveIntegerField(verbose_name="Ordem de pronunciamento"),
                ),
                (
                    "url_discurso",
                    models.URLField(
                        blank=True, max_length=150, verbose_name="URL Vídeo"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Observação"
                    ),
                ),
                (
                    "upload_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.anexo_upload_path,
                        verbose_name="Anexo do Orador",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orador do Expediente",
                "verbose_name_plural": "Oradores do Expediente",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Orador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "numero_ordem",
                    models.PositiveIntegerField(verbose_name="Ordem de pronunciamento"),
                ),
                (
                    "url_discurso",
                    models.URLField(
                        blank=True, max_length=150, verbose_name="URL Vídeo"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Observação"
                    ),
                ),
                (
                    "upload_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.anexo_upload_path,
                        verbose_name="Anexo do Orador",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orador das Explicações Pessoais",
                "verbose_name_plural": "Oradores das Explicações Pessoais",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaSessao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ordem",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Ordem de ocorrência"
                    ),
                ),
                (
                    "local",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "Vinculada a Projeto"),
                            (20, "Início da Sessão"),
                            (30, "Entre Grande Expediente e Ordem do Dia"),
                            (99, "Fim da Sessão"),
                        ],
                        default=10,
                        verbose_name="Local da Ocorrência",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Título da Ocorrência",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Descrição da Ocorrência")),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocorrenciasessao_set",
                        to="sessao.expedientemateria",
                        verbose_name="Matéria do Expediente",
                    ),
                ),
                (
                    "ordemdia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocorrenciasessao_set",
                        to="sessao.ordemdia",
                        verbose_name="Matéria da Ordem do Dia",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência da Sessão Plenaria",
                "verbose_name_plural": "Ocorrências da Sessão Plenaria",
                "ordering": ["local", "numero_ordem"],
            },
        ),
        migrations.CreateModel(
            name="IntegranteMesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assina_ata",
                    models.BooleanField(default=False, verbose_name="Assina Ata"),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.cargomesa",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantemesa",
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participação em Mesa de Sessão Plenaria",
                "verbose_name_plural": "Participações em Mesas de Sessão Plenaria",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="expedientemateria",
            name="sessao_plenaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessao.sessaoplenaria"
            ),
        ),
        migrations.CreateModel(
            name="SessaoPlenariaPresenca",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_sessao", models.DateField(blank=True, null=True)),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença em Sessão Plenária",
                "verbose_name_plural": "Presenças em Sessões Plenárias",
                "ordering": ["parlamentar__nome_parlamentar"],
            },
        ),
        migrations.CreateModel(
            name="ExpedienteSessao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(blank=True, verbose_name="Conteúdo do expediente"),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedientesessao_set",
                        to="sessao.sessaoplenaria",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessao.tipoexpediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente de Sessão Plenaria",
                "verbose_name_plural": "Expedientes de Sessão Plenaria",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="JustificativaAusencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "hora",
                    models.CharField(max_length=5, verbose_name="Horário (hh:mm)"),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True, max_length=150, verbose_name="Observação"
                    ),
                ),
                (
                    "ausencia",
                    models.PositiveIntegerField(
                        choices=[(1, "Matéria"), (2, "Sessão")],
                        default=1,
                        verbose_name="Ausente em",
                    ),
                ),
                (
                    "upload_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.sessao.models.anexo_upload_path,
                        verbose_name="Anexo de Justificativa",
                    ),
                ),
                (
                    "materias_do_expediente",
                    models.ManyToManyField(
                        blank=True,
                        to="sessao.expedientemateria",
                        verbose_name="Matérias do Expediente",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
                (
                    "materias_da_ordem_do_dia",
                    models.ManyToManyField(
                        blank=True,
                        to="sessao.ordemdia",
                        verbose_name="Matérias do Ordem do Dia",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                        verbose_name="Sessão Plenária",
                    ),
                ),
                (
                    "tipo_ausencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessao.tipojustificativa",
                        verbose_name="Tipo de Justificativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Justificativa de Ausência",
                "verbose_name_plural": "Justificativas de Ausências",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RegistroVotacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_votos_sim", models.PositiveIntegerField(verbose_name="Sim")),
                ("numero_votos_nao", models.PositiveIntegerField(verbose_name="Não")),
                (
                    "numero_abstencoes",
                    models.PositiveIntegerField(verbose_name="Abstenções"),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="IP"
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Data/Hora"
                    ),
                ),
                (
                    "selo_votacao",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        null=True,
                        verbose_name="Selo de Votação Adicionado",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.expedientemateria",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrovotacao_set",
                        to="sessao.ordemdia",
                    ),
                ),
                (
                    "subscricoes",
                    models.ManyToManyField(
                        related_name="subscricoes", to="parlamentares.parlamentar"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_resultado_votacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessao.tiporesultadovotacao",
                        verbose_name="Resultado da Votação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votação",
                "verbose_name_plural": "Votações",
                "ordering": ("data_hora", "id"),
            },
        ),
        migrations.CreateModel(
            name="RetiradaPauta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.expedientemateria",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materialegislativa",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.ordemdia",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                        verbose_name="Requerente",
                    ),
                ),
                (
                    "sessao_plenaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.sessaoplenaria",
                        verbose_name="Sessão Plenária",
                    ),
                ),
                (
                    "tipo_de_retirada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessao.tiporetiradapauta",
                        verbose_name="Motivo de Retirada de Pauta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retirada de Pauta",
                "verbose_name_plural": "Retirada de Pauta",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VotoParlamentar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voto", models.CharField(max_length=10)),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="IP"
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Data/Hora"
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.expedientemateria",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.ordemdia",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parlamentares.parlamentar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "votacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessao.registrovotacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Votação de Parlamentar",
                "verbose_name_plural": "Registros de Votações de Parlamentares",
                "ordering": ["id"],
                "unique_together": {("votacao", "parlamentar", "ordem", "expediente")},
            },
        ),
    ]
