# Generated by Django 5.2.14 on 2026-05-29 10:34

import sapl.sessao.models
import sapl.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="justificativaausencia",
            name="upload_anexo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.sessao.models.anexo_upload_path,
                verbose_name="Anexo de Justificativa",
            ),
        ),
        migrations.AlterField(
            model_name="orador",
            name="upload_anexo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.sessao.models.anexo_upload_path,
                verbose_name="Anexo do Orador",
            ),
        ),
        migrations.AlterField(
            model_name="oradorexpediente",
            name="upload_anexo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.sessao.models.anexo_upload_path,
                verbose_name="Anexo do Orador",
            ),
        ),
        migrations.AlterField(
            model_name="oradorordemdia",
            name="upload_anexo",
            field=sapl.utils.PortalFileField(
                blank=True,
                null=True,
                storage=sapl.utils.OverwriteStorage(),
                upload_to=sapl.sessao.models.anexo_upload_path,
                verbose_name="Anexo do Orador",
            ),
        ),
    ]
