# Generated by Django 5.2.14 on 2026-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0002_alter_justificativaausencia_upload_anexo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaoplenaria",
            name="pauta_publicada",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                null=True,
                verbose_name="Pauta publicada?",
            ),
        ),
    ]
