# Generated by Django 5.2.16 on 2026-08-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comissoes", "0003_alter_documentoacessorio_arquivo_and_more"),
        ("sessao", "0003_sessaoplenaria_pauta_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessaoplenaria",
            name="comissao",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessaoplenaria_set",
                to="comissoes.comissao",
                verbose_name="Comissão",
            ),
        ),
    ]
