# Generated by Django 5.2.16 on 2026-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0004_sessaoplenaria_comissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessaoplenaria",
            name="iniciada",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Sim"), (False, "Não")],
                default=False,
                null=True,
                verbose_name="Sessão iniciada?",
            ),
        ),
    ]
