# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0046_auto_20190809_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data'),
        ),
    ]
