# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0047_sessaoplenaria_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovotacao',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrovotacao_set', to='sessao.OrdemDia'),
        ),
        migrations.AlterField(
            model_name='tiporesultadovotacao',
            name='natureza',
            field=models.CharField(blank=True, choices=[('A', 'Aprovado'), ('R', 'Rejeitado'), ('P', 'Pedidos de Prazo')], max_length=1, verbose_name='Natureza do Tipo'),
        ),
    ]
