# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 12:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0048_auto_20190922_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
