# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0049_sessaoplenaria_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovotacao',
            options={'ordering': ('id',), 'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
    ]
