# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-12 17:24
from __future__ import unicode_literals

from django.db import migrations
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0051_auto_20200505_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_anexo',
            field=sapl.utils.PortalFileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_ata',
            field=sapl.utils.PortalFileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_pauta',
            field=sapl.utils.PortalFileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Sessão'),
        ),
    ]
