# Generated by Django 2.2.12 on 2020-05-26 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0074_auto_20200520_2037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessao', '0053_auto_20200520_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientemateria',
            name='tipo_votacao',
            field=models.PositiveIntegerField(choices=[(1, 'Simbólica'), (2, 'Nominal'), (3, 'Secreta'), (4, 'Leitura')], default=1, verbose_name='Tipo de votação'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='tipo_votacao',
            field=models.PositiveIntegerField(choices=[(1, 'Simbólica'), (2, 'Nominal'), (3, 'Secreta'), (4, 'Leitura')], default=1, verbose_name='Tipo de votação'),
        ),
        migrations.CreateModel(
            name='RegistroLeitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('ip', models.CharField(blank=True, default='', max_length=60, verbose_name='IP')),
                ('data_hora', models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.ExpedienteMateria')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.OrdemDia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
            },
        ),
    ]
