# Generated by Django 2.2.12 on 2020-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0041_auto_20200602_1029'),
        ('sessao', '0054_auto_20200526_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotacao',
            name='subscricoes',
            field=models.ManyToManyField(related_name='subscricoes', to='parlamentares.Parlamentar'),
        ),
    ]
