# Generated by Django 2.2.16 on 2020-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0055_registrovotacao_subscricoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedientemateria',
            options={'ordering': ('-sessao_plenaria', 'numero_ordem'), 'verbose_name': 'Matéria do Expediente', 'verbose_name_plural': 'Matérias do Expediente'},
        ),
        migrations.AlterModelOptions(
            name='ordemdia',
            options={'ordering': ('-sessao_plenaria', 'numero_ordem'), 'verbose_name': 'Matéria da Ordem do Dia', 'verbose_name_plural': 'Matérias da Ordem do Dia'},
        ),
        migrations.AddField(
            model_name='expedientemateria',
            name='url_video',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='url_video',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'),
        ),
    ]
