# Generated by Django 2.2.20 on 2021-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0056_auto_20201112_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='selo_votacao_adicionado',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Selo de Votação Adicionado?'),
        ),
    ]
