# Generated by Django 2.2.20 on 2021-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0057_sessaoplenaria_selo_votacao_adicionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='selo_votacao_adicionado',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Selo de Votação Adicionado?'),
        ),
    ]
