# Generated by Django 2.2.20 on 2021-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0058_auto_20210511_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotacao',
            name='selo_votacao',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Selo de Votação Adicionado'),
        ),
    ]
