# Generated by Django 2.2.24 on 2021-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0059_registrovotacao_selo_votacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposessaoplenaria',
            name='gera_selo_votacao',
            field=models.BooleanField(blank=True, default=True, verbose_name='Gera Selo de Votação?'),
        ),
    ]
