# Generated by Django 2.2.24 on 2021-10-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0060_tiposessaoplenaria_gera_selo_votacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrovotacao',
            options={'ordering': ('data_hora', 'id'), 'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
    ]
