# Generated by Django 2.2.24 on 2021-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0061_auto_20211007_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposessaoplenaria',
            name='tipogeral',
            field=models.PositiveIntegerField(choices=[(10, 'Sessão'), (20, 'Reunião'), (30, 'Audiência')], default=10, verbose_name='Tipo Geral'),
        ),
    ]
