# Generated by Django 2.2.24 on 2021-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0062_tiposessaoplenaria_tipogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Título'),
        ),
    ]
