# Generated by Django 2.2.28 on 2023-02-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0063_sessaoplenaria_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemateria',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.ExpedienteMateria', verbose_name='Expendiente Principal'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.OrdemDia', verbose_name='Ordem Dia Principal'),
        ),
    ]
