# Generated by Django 2.2.28 on 2023-03-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0064_auto_20230205_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdia',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='sessao.OrdemDia', verbose_name='Ordem Dia Principal'),
        ),
    ]
