# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0065_auto_20230327_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedientesessao',
            options={'ordering': ['id'], 'verbose_name': 'Expediente de Sessão Plenaria', 'verbose_name_plural': 'Expedientes de Sessão Plenaria'},
        ),
        migrations.AlterModelOptions(
            name='integrantemesa',
            options={'ordering': ['id'], 'verbose_name': 'Participação em Mesa de Sessão Plenaria', 'verbose_name_plural': 'Participações em Mesas de Sessão Plenaria'},
        ),
        migrations.AlterModelOptions(
            name='justificativaausencia',
            options={'ordering': ['id'], 'verbose_name': 'Justificativa de Ausência', 'verbose_name_plural': 'Justificativas de Ausências'},
        ),
        migrations.AlterModelOptions(
            name='ocorrenciasessao',
            options={'ordering': ['id'], 'verbose_name': 'Ocorrência da Sessão Plenaria', 'verbose_name_plural': 'Ocorrências da Sessão Plenaria'},
        ),
        migrations.AlterModelOptions(
            name='orador',
            options={'ordering': ['id'], 'verbose_name': 'Orador das Explicações Pessoais', 'verbose_name_plural': 'Oradores das Explicações Pessoais'},
        ),
        migrations.AlterModelOptions(
            name='oradorexpediente',
            options={'ordering': ['id'], 'verbose_name': 'Orador do Expediente', 'verbose_name_plural': 'Oradores do Expediente'},
        ),
        migrations.AlterModelOptions(
            name='oradorordemdia',
            options={'ordering': ['id'], 'verbose_name': 'Orador da Ordem do Dia', 'verbose_name_plural': 'Oradores da Ordem do Dia'},
        ),
        migrations.AlterModelOptions(
            name='ordemdia',
            options={'ordering': ['id'], 'verbose_name': 'Matéria da Ordem do Dia', 'verbose_name_plural': 'Matérias da Ordem do Dia'},
        ),
        migrations.AlterModelOptions(
            name='registroleitura',
            options={'ordering': ['id'], 'verbose_name': 'Leitura', 'verbose_name_plural': 'Leituras'},
        ),
        migrations.AlterModelOptions(
            name='resumoordenacao',
            options={'ordering': ['id'], 'verbose_name': 'Ordenação do Resumo de uma Sessão', 'verbose_name_plural': 'Ordenação do Resumo de uma Sessão'},
        ),
        migrations.AlterModelOptions(
            name='retiradapauta',
            options={'ordering': ['id'], 'verbose_name': 'Retirada de Pauta', 'verbose_name_plural': 'Retirada de Pauta'},
        ),
        migrations.AlterModelOptions(
            name='sessaoplenaria',
            options={'ordering': ['id'], 'verbose_name': 'Sessão Plenária', 'verbose_name_plural': 'Sessões Plenárias'},
        ),
        migrations.AlterModelOptions(
            name='tiporesultadovotacao',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Resultado de Votação', 'verbose_name_plural': 'Tipos de Resultado de Votação'},
        ),
        migrations.AlterModelOptions(
            name='votoparlamentar',
            options={'ordering': ['id'], 'verbose_name': 'Registro de Votação de Parlamentar', 'verbose_name_plural': 'Registros de Votações de Parlamentares'},
        ),
    ]
