# Generated by Django 2.2.28 on 2024-04-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0066_auto_20240325_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantemesa',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantemesa', to='sessao.SessaoPlenaria'),
        ),
    ]
