# Generated by Django 2.2.28 on 2024-06-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0089_regimetramitacao_sequencia_regimental'),
        ('sessao', '0067_auto_20240401_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemateria',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação Atual'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação Atual'),
        ),
    ]
