# Generated by Django 2.2.28 on 2024-06-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0068_auto_20240619_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientemateria',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação quando pautada'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação quando pautada'),
        ),
    ]
