# Generated by Django 4.2.16 on 2024-10-03 20:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0069_auto_20240621_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientemateria',
            name='registro_aberto',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Registro de Votação Iniciado?'),
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='votacao_aberta',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Votação iniciada?'),
        ),
        migrations.AlterField(
            model_name='justificativaausencia',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='oradorordemdia',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='registro_aberto',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Registro de Votação Iniciado?'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='votacao_aberta',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Votação iniciada?'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='selo_votacao',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Selo de Votação Adicionado'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='finalizada',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Sessão finalizada?'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='iniciada',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=True, null=True, verbose_name='Sessão iniciada?'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='interativa',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Sessão interativa'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='selo_votacao_adicionado',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Selo de Votação Adicionado?'),
        ),
    ]
