# Generated by Django 4.2.16 on 2024-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0070_alter_expedientemateria_registro_aberto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemateria',
            name='votacao_aberta_pedido_prazo',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Votação de Pedido de Prazo?'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='votacao_aberta_pedido_prazo',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Votação de Pedido de Prazo?'),
        ),
    ]
