# Generated by Django 4.2.18 on 2025-02-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0071_expedientemateria_votacao_aberta_pedido_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposessaoplenaria',
            name='tipogeral',
            field=models.PositiveIntegerField(choices=[(10, 'Sessão'), (20, 'Reunião'), (30, 'Audiência'), (40, 'Jovem Vereador')], default=10, verbose_name='Tipo Geral'),
        ),
    ]
