# Generated by Django 5.2.3 on 2025-11-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0072_alter_tiposessaoplenaria_tipogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemateria',
            name='discussao_aberta',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Discussão aberta?'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='discussao_aberta',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True, verbose_name='Discussão aberta?'),
        ),
    ]
