# Generated by Django 5.2.3 on 2025-11-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0051_filiacao_autor_alter_filiacao_parlamentar'),
        ('sessao', '0073_expedientemateria_discussao_aberta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votoparlamentar',
            unique_together={('votacao', 'parlamentar', 'ordem', 'expediente')},
        ),
    ]
