# Generated by Django 5.2.11 on 2026-03-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0074_alter_votoparlamentar_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciasessao",
            name="expediente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrenciasessao_set",
                to="sessao.expedientemateria",
                verbose_name="Matéria do Expediente",
            ),
        ),
        migrations.AddField(
            model_name="ocorrenciasessao",
            name="ordemdia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrenciasessao_set",
                to="sessao.ordemdia",
                verbose_name="Matéria da Ordem do Dia",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrenciasessao",
            name="sessao_plenaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sessao.sessaoplenaria"
            ),
        ),
    ]
