# Generated by Django 5.2.11 on 2026-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0075_ocorrenciasessao_expediente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciasessao",
            name="numero_ordem",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Ordem de ocorrência"
            ),
        ),
    ]
