# Generated by Django 5.2.11 on 2026-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0076_ocorrenciasessao_numero_ordem"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciasessao",
            name="titulo",
            field=models.CharField(
                default="", max_length=255, verbose_name="Título da Ocorrência"
            ),
        ),
        migrations.AlterField(
            model_name="ocorrenciasessao",
            name="conteudo",
            field=models.TextField(verbose_name="Descrição da Ocorrência"),
        ),
    ]
