# Generated by Django 5.2.11 on 2026-03-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0077_ocorrenciasessao_titulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrantemesa",
            name="assina_ata",
            field=models.BooleanField(default=False, verbose_name="Assina Ata"),
        ),
    ]
