# Generated by Django 5.2.11 on 2026-03-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0078_integrantemesa_assina_ata"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrenciasessao",
            name="local",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "Vinculada a Projeto"),
                    (20, "Início da Sessão"),
                    (30, "Entre Grande Expediente e Ordem do Dia"),
                    (99, "Fim da Sessão"),
                ],
                default=10,
                verbose_name="Local da Ocorrência",
            ),
        ),
    ]
