# Generated by Django 5.2.11 on 2026-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0079_ocorrenciasessao_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrenciasessao",
            name="titulo",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Título da Ocorrência",
            ),
        ),
    ]
