# Generated by Django 5.2.11 on 2026-03-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sessao", "0080_alter_ocorrenciasessao_titulo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ocorrenciasessao",
            options={
                "ordering": ["local", "numero_ordem"],
                "verbose_name": "Ocorrência da Sessão Plenaria",
                "verbose_name_plural": "Ocorrências da Sessão Plenaria",
            },
        ),
    ]
