version: '3.8'

services:
  redis-dev:
    container_name: redis-dev
    image: redis
    restart: always
    ports:
      - "6379:6379"

  node-dev:
    image: node:10.22.0
    container_name: node-dev
    restart: always
    command: yarn serve
    working_dir: /frontend
    ports:
      - 8080:8080
    networks:
      - cmj-dev
    volumes:
      - "./frontend:/frontend"
  zk-dev:
    image: zookeeper:latest
    container_name: zk-dev
    restart: always
    hostname: zk-dev
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    networks:
      - solr-dev

  solr-dev:
    image: solr:latest
    restart: always
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev
    container_name: solr-dev
    networks:
      - solr-dev
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zk-dev:2181
    volumes:
      - "../solr_data_dev:/opt/solr/server/solr"
      - ".:/cmj-dev"
    depends_on:
      - zk-dev

networks:
  solr-dev:
  cmj-dev:
    name: cmj-dev
    driver: bridge