export const LOAGING_STATE = 'LOAGING_STATE';

// export const NOTIFICATIONS_OBJECT = 'NOTIFICATIONS_OBJECT';
// export const NOTIFICATIONS_COLLECTION = 'NOTIFICATIONS_COLLECTION';
// export const SET_NOTIFICATIONS_BAR_STATUS = 'SET_NOTIFICATIONS_BAR_STATUS';
