# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procuradoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoprocuradoria',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='DocumentoProcuradoria',
        ),
        migrations.DeleteModel(
            name='TipoDocumentoProcuradoria',
        ),
    ]
