# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compilacao", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dono da Nota",
            ),
        ),
        migrations.AddField(
            model_name="perfilestruturaltextoarticulado",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="perfil_parent_set",
                to="compilacao.perfilestruturaltextoarticulado",
                verbose_name="Perfil Herdado",
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="publicacao",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.publicacao",
                verbose_name="Publicação",
            ),
        ),
        migrations.AddField(
            model_name="textoarticulado",
            name="clone",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="original",
                to="compilacao.textoarticulado",
                verbose_name="Clone",
            ),
        ),
        migrations.AddField(
            model_name="textoarticulado",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="textoarticulado",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Donos do Texto Articulado",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="ta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.textoarticulado",
                verbose_name="Texto Articulado",
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="ta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispositivos_set",
                to="compilacao.textoarticulado",
                verbose_name="Texto Articulado",
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="ta_publicado",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos_alterados_pelo_ta_set",
                to="compilacao.textoarticulado",
                verbose_name="Texto Articulado Publicado",
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="tipo_dispositivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos_do_tipo_set",
                to="compilacao.tipodispositivo",
                verbose_name="Tipo do Dispositivo",
            ),
        ),
        migrations.AddField(
            model_name="tipodispositivorelationship",
            name="filho_permitido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="possiveis_pais",
                to="compilacao.tipodispositivo",
            ),
        ),
        migrations.AddField(
            model_name="tipodispositivorelationship",
            name="pai",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="filhos_permitidos",
                to="compilacao.tipodispositivo",
            ),
        ),
        migrations.AddField(
            model_name="tipodispositivorelationship",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.perfilestruturaltextoarticulado",
            ),
        ),
        migrations.AddField(
            model_name="tipodispositivo",
            name="relacoes_diretas_pai_filho",
            field=models.ManyToManyField(
                related_name="relacaoes_pai_filho",
                through="compilacao.TipoDispositivoRelationship",
                through_fields=("pai", "filho_permitido"),
                to="compilacao.tipodispositivo",
            ),
        ),
        migrations.AddField(
            model_name="nota",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.tiponota",
                verbose_name="Tipo da Nota",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="tipo_publicacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.tipopublicacao",
                verbose_name="Tipo de Publicação",
            ),
        ),
        migrations.AddField(
            model_name="tipotextoarticulado",
            name="content_type",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Modelo Integrado",
            ),
        ),
        migrations.AddField(
            model_name="tipotextoarticulado",
            name="perfis",
            field=models.ManyToManyField(
                blank=True,
                help_text="\n                    Apenas os perfis selecionados aqui estarão disponíveis\n                    para o editor de Textos Articulados cujo Tipo seja este\n                    em edição.\n                    ",
                to="compilacao.perfilestruturaltextoarticulado",
                verbose_name="Perfis Estruturais de Textos Articulados",
            ),
        ),
        migrations.AddField(
            model_name="textoarticulado",
            name="tipo_ta",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.tipotextoarticulado",
                verbose_name="Tipo de Texto Articulado",
            ),
        ),
        migrations.AddField(
            model_name="urlizereferencia",
            name="citacao",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="urlize_referencias",
                to="compilacao.citacaodereferencia",
                verbose_name="Citação de Referência",
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="veiculo_publicacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.veiculopublicacao",
                verbose_name="Veículo de Publicação",
            ),
        ),
        migrations.AddField(
            model_name="vide",
            name="dispositivo_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivo_base_set",
                to="compilacao.dispositivo",
                verbose_name="Dispositivo Base",
            ),
        ),
        migrations.AddField(
            model_name="vide",
            name="dispositivo_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivo_citado_set",
                to="compilacao.dispositivo",
                verbose_name="Dispositivo Referido",
            ),
        ),
        migrations.AddField(
            model_name="vide",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compilacao.tipovide",
                verbose_name="Tipo do Vide",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dispositivo",
            unique_together={
                (
                    "ta",
                    "dispositivo0",
                    "dispositivo1",
                    "dispositivo2",
                    "dispositivo3",
                    "dispositivo4",
                    "dispositivo5",
                    "tipo_dispositivo",
                    "contagem_continua",
                    "dispositivo_raiz",
                    "dispositivo_atualizador",
                    "ta_publicado",
                    "publicacao",
                ),
                (
                    "ta",
                    "dispositivo0",
                    "dispositivo1",
                    "dispositivo2",
                    "dispositivo3",
                    "dispositivo4",
                    "dispositivo5",
                    "tipo_dispositivo",
                    "dispositivo_raiz",
                    "dispositivo_pai",
                    "dispositivo_atualizador",
                    "ta_publicado",
                    "publicacao",
                ),
                ("ta", "ordem"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="tipodispositivorelationship",
            unique_together={("pai", "filho_permitido", "perfil")},
        ),
        migrations.AlterUniqueTogether(
            name="vide",
            unique_together={("dispositivo_base", "dispositivo_ref", "tipo")},
        ),
    ]
