# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0013_auto_20190924_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textoarticulado',
            options={'ordering': ['-data', '-numero'], 'permissions': (('view_restricted_textoarticulado', 'Pode ver qualquer Texto Articulado'), ('lock_textoarticulado', 'Pode bloquear edição de Texto Articulado'), ('unlock_textoarticulado', 'Pode desbloquear edição de Texto Articulado')), 'verbose_name': 'Texto Articulado', 'verbose_name_plural': 'Textos Articulados'},
        ),
    ]
