# Generated by Django 2.2.24 on 2021-12-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0015_auto_20200520_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoarticulado',
            name='clone',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original', to='compilacao.TextoArticulado', verbose_name='Clone'),
        ),
    ]
