# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0016_textoarticulado_clone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['id'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='tiponota',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Nota', 'verbose_name_plural': 'Tipos de Nota'},
        ),
        migrations.AlterModelOptions(
            name='tipopublicacao',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Publicação', 'verbose_name_plural': 'Tipos de Publicação'},
        ),
        migrations.AlterModelOptions(
            name='tipotextoarticulado',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Texto Articulado', 'verbose_name_plural': 'Tipos de Texto Articulados'},
        ),
        migrations.AlterModelOptions(
            name='tipovide',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Vide', 'verbose_name_plural': 'Tipos de Vide'},
        ),
        migrations.AlterModelOptions(
            name='veiculopublicacao',
            options={'ordering': ['id'], 'verbose_name': 'Veículo de Publicação', 'verbose_name_plural': 'Veículos de Publicação'},
        ),
        migrations.AlterModelOptions(
            name='vide',
            options={'ordering': ['id'], 'verbose_name': 'Vide', 'verbose_name_plural': 'Vides'},
        ),
    ]
