# Generated by Django 2.2.28 on 2024-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0017_auto_20240325_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlizeReferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Chave')),
                ('url', models.CharField(max_length=256, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Link de Referência',
                'verbose_name_plural': 'Links de Referências',
                'ordering': ['chave'],
            },
        ),
    ]
