# Generated by Django 2.2.28 on 2024-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0018_urlizereferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlizereferencia',
            name='url',
            field=models.CharField(default='', max_length=256, verbose_name='Url'),
        ),
    ]
