# Generated by Django 2.2.28 on 2024-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0019_auto_20240521_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlizereferencia',
            name='chave_automatica',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Gerada Automaticamente?'),
        ),
    ]
