# Generated by Django 4.2.18 on 2025-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0021_alter_textoarticulado_participacao_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='custom_text_link',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Texto Customizado do Link de Referência'),
        ),
    ]
