# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0022_dispositivo_custom_text_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodispositivo',
            name='relacoes_diretas_pai_filho',
            field=models.ManyToManyField(related_name='relacaoes_pai_filho', through='compilacao.TipoDispositivoRelationship', through_fields=('pai', 'filho_permitido'), to='compilacao.tipodispositivo'),
        ),
    ]
