# Generated by Django 5.2.3 on 2025-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0023_alter_tipodispositivo_relacoes_diretas_pai_filho'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlizereferencia',
            name='search',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunSQL(
            """
            UPDATE compilacao_urlizereferencia
            SET search = lower(chave || ' ' || url || ' ' || chave_automatica::text);
            """,
            reverse_sql="""
            UPDATE compilacao_urlizereferencia
            SET search = '';
            """
        ),
    ]
