# Generated by Django 5.2.3 on 2025-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0024_urlizereferencia_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitacaoDeReferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epigrafe', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Epigrafe da Citação de Referência')),
            ],
            options={
                'verbose_name': 'Citação de Referência',
                'verbose_name_plural': 'Citações de Referências',
                'ordering': ['epigrafe'],
            },
        ),
        migrations.AddField(
            model_name='urlizereferencia',
            name='citacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='compilacao.citacaodereferencia', verbose_name='Citação de Referência'),
        ),
    ]
