# Generated by Django 5.2.3 on 2025-09-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0025_citacaodereferencia_urlizereferencia_citacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlizereferencia',
            name='citacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urlize_referencias', to='compilacao.citacaodereferencia', verbose_name='Citação de Referência'),
        ),
    ]
