# Generated by Django 2.2.28 on 2024-01-03 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=50, verbose_name='Descrição de Componente de Tela')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nome Vue do Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.BooleanField(default=False, verbose_name='Tela de Timer Individual')),
                ('cols', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(3)])),
                ('rows', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='PainelSET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=50, verbose_name='Descrição do Conjunto de Paineis')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('descricao',),
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=50, verbose_name='Descrição do Painel')),
                ('painelset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='painelset.PainelSET', verbose_name='Conjunto de Paineis')),
                ('tela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='painel_tela_set', to='painelset.Tela', verbose_name='Tela Associada ao Painel')),
                ('timer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='painel_timer_set', to='painelset.Tela', verbose_name='Tela de Timer Individual de Falas')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteTela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField(default=5)),
                ('h', models.PositiveSmallIntegerField(default=2)),
                ('componente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='painelset.ComponenteBase', verbose_name='Componente Base')),
                ('tela', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='painelset.Tela', verbose_name='Tela do Componente')),
            ],
        ),
    ]
