# Generated by Django 2.2.28 on 2024-01-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentebase',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nome Vue do Componente'),
        ),
    ]
