# Generated by Django 2.2.28 on 2024-01-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0002_auto_20240106_1809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='painelset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='painelset',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='painelset',
            name='object_id',
        ),
    ]
