# Generated by Django 2.2.28 on 2024-01-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0003_auto_20240106_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentebase',
            options={'ordering': ('descricao',), 'verbose_name': 'Componente Base', 'verbose_name_plural': 'Componentes Base'},
        ),
        migrations.AlterModelOptions(
            name='painelset',
            options={'ordering': ('descricao',), 'verbose_name': 'Conjunto de Paineis', 'verbose_name_plural': 'Conjuntos de Paineis'},
        ),
        migrations.AddField(
            model_name='tela',
            name='descricao',
            field=models.CharField(default='', max_length=50, verbose_name='Descrição da Tela'),
        ),
    ]
