# Generated by Django 5.2.12 on 2026-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Início")),
                (
                    "fim",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim"),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "caracteristica",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Eventos Diversos"), (1, "Feriado")],
                        default=0,
                        verbose_name="Caracteristica?",
                    ),
                ),
                (
                    "link_externo",
                    models.URLField(blank=True, default="", verbose_name="Url Externa"),
                ),
                (
                    "solicitante",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Solicitante"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ("-inicio",),
            },
        ),
        migrations.CreateModel(
            name="Programacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Início")),
                ("fim", models.DateTimeField(verbose_name="Fim")),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Tipo de Evento",
                "verbose_name_plural": "Tipos de Eventos",
                "ordering": ["id"],
            },
        ),
    ]
