# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evento_set",
                to="core.areatrabalho",
                verbose_name="Área de Trabalho",
            ),
        ),
        migrations.AddField(
            model_name="programacao",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programacao_set",
                to="agenda.evento",
                verbose_name="Programacao do Evento",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="agenda.tipoevento",
                verbose_name="Tipo de Evento",
            ),
        ),
    ]
