# Generated by Django 5.2.12 on 2026-04-04 16:18

from decimal import Decimal

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import cmj.loa.models.m_ajusteloa
import cmj.loa.models.m_prestacaoconta
import sapl.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DespesaConsulta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_materia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Despesa Matéria (R$)",
                    ),
                ),
                (
                    "valor_norma",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Despesa Norma (R$)",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                ("especificacao", models.TextField(verbose_name="Especificação")),
                ("cod_orgao", models.TextField(verbose_name="Código do Órgão")),
                ("esp_orgao", models.TextField(verbose_name="Órgão")),
                ("cod_unidade", models.TextField(verbose_name="Código da Unidade")),
                ("esp_unidade", models.TextField(verbose_name="Unidade Orçamentária")),
                ("cod_natureza", models.TextField(verbose_name="Código Natureza")),
                ("esp_natureza", models.TextField(verbose_name="Natureza da Despesa")),
                ("cod_fonte", models.TextField(verbose_name="Fonte")),
            ],
            options={
                "db_table": "loa_despesa_consulta",
                "ordering": ("cod_orgao", "cod_unidade", "codigo", "cod_natureza"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Acao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação",
                "verbose_name_plural": "Ações",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Agrupamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=256, verbose_name="Nome do Agrupamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agrupamento de Emenda Impositiva/Modificativas",
                "verbose_name_plural": "Agrupamentos de Emendas Impositivas/Modificativas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ArquivoPrestacaoContaLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=cmj.loa.models.m_prestacaoconta.prestacaoconta_upload_path,
                        verbose_name="Arquivo Anexo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo da Prestação de Conta LOA",
                "verbose_name_plural": "Arquivos da Prestação de Conta LOA",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ArquivoPrestacaoContaRegistro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        upload_to=cmj.loa.models.m_prestacaoconta.prestacaocontaregistro_upload_path,
                        verbose_name="Arquivo Anexo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo do Registro de Prestação de Conta",
                "verbose_name_plural": "Arquivos do Registro de Prestação de Conta",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DespesaPaga",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "cpfcnpj",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="CpfCNPJ"
                    ),
                ),
                (
                    "nome",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "historico",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Histórico"
                    ),
                ),
                (
                    "tipo",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Tipo"
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Paga",
                "verbose_name_plural": "Despesas Pagas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EmendaLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.TextField(blank=True, default="")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "tipo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Em.Imp. Saúde"),
                            (99, "Em.Imp. Áreas Diversas"),
                            (0, "Emenda Modificativa"),
                        ],
                        default=99,
                        verbose_name="Área de aplicação",
                    ),
                ),
                (
                    "fase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Proposta Legislativa"),
                            (12, "Proposta Liberada para Edição Contábil"),
                            (15, "Em edição pela Contabilidade"),
                            (
                                17,
                                "Liberado pela Contabilidade e/ou Aguardando Protocolo",
                            ),
                            (20, "Matéria protocolada, em tramitação"),
                            (25, "Aprovada no Processo Legislativo"),
                            (30, "Aprovada"),
                            (40, "Impedimento Técnico"),
                            (50, "Emenda Redefinida/Sanada"),
                            (60, "Em Execução"),
                            (99, "Finalizada"),
                        ],
                        default=10,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "indicacao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Indicação"
                    ),
                ),
                ("finalidade", models.TextField(verbose_name="Finalidade")),
                (
                    "prefixo_indicacao",
                    models.CharField(
                        blank=True,
                        default="o(a)",
                        max_length=30,
                        verbose_name="Prefixo da Indicação",
                    ),
                ),
                (
                    "prefixo_finalidade",
                    models.CharField(
                        blank=True,
                        default="destinado a",
                        max_length=30,
                        verbose_name="Prefixo da Finalidade",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Global da Emenda (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emenda Impositiva/Modificativa",
                "verbose_name_plural": "Emendas Impositivas/Modificativas",
                "ordering": ["id"],
                "permissions": (
                    (
                        "emendaloa_full_editor",
                        "Edição completa de Emendas Impositivas.",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="EmendaLoaHistoricoFase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Proposta Legislativa"),
                            (12, "Proposta Liberada para Edição Contábil"),
                            (15, "Em edição pela Contabilidade"),
                            (
                                17,
                                "Liberado pela Contabilidade e/ou Aguardando Protocolo",
                            ),
                            (20, "Matéria protocolada, em tramitação"),
                            (25, "Aprovada no Processo Legislativo"),
                            (30, "Aprovada"),
                            (40, "Impedimento Técnico"),
                            (50, "Emenda Redefinida/Sanada"),
                            (60, "Em Execução"),
                            (99, "Finalizada"),
                        ],
                        default=10,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
            ],
            options={
                "verbose_name": "Histórico de Fase da Emenda Impositiva",
                "verbose_name_plural": "Históricos de Fase das Emendas Impositivas",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmendaLoaParlamentar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor por Parlamentar (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participação Parlamentar na Emenda Impositiva",
                "verbose_name_plural": "Participações Parlamentares na Emenda Impositiva",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EmendaLoaRegistroContabil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Contábil de Dedução e Inserção em Emendas",
                "verbose_name_plural": "Registros Contábeis de Dedução e Inserção em Emendas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Empenho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.TextField(blank=True, default="")),
                (
                    "codigo",
                    models.PositiveIntegerField(unique=True, verbose_name="Código"),
                ),
                (
                    "cpfcnpj",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="CpfCNPJ"
                    ),
                ),
                (
                    "nome",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "tipo",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Tipo"
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "modalidade",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Modalidade"
                    ),
                ),
                (
                    "numero_licitacao",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Número da Licitação",
                    ),
                ),
                (
                    "historico",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Histórico"
                    ),
                ),
                (
                    "dotacao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Dotação"
                    ),
                ),
                (
                    "processo",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Processo"
                    ),
                ),
                (
                    "valor_empenhado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Empenhado (R$)",
                    ),
                ),
                (
                    "valor_anulado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Anulado (R$)",
                    ),
                ),
                (
                    "valor_liquidado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Liquidado (R$)",
                    ),
                ),
                (
                    "valor_pago_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Pago (Bruto) (R$)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empenho",
                "verbose_name_plural": "Empenhos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EmpenhoEmendaAjuste",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empenho de Emenda e/ou Ajuste Técnico",
                "verbose_name_plural": "Empenhos de Emendas e/ou Ajustes Técnicos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=256, verbose_name="Nome"),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=256, verbose_name="Nome Empresarial"),
                ),
                (
                    "cpfcnpj",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=18,
                        null=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "cnes",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{7}$", "CNES inválido"
                            )
                        ],
                        verbose_name="CNES",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("ativo", models.BooleanField(default=False, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Entidade",
                "verbose_name_plural": "Entidades",
                "ordering": ["nome_fantasia"],
            },
        ),
        migrations.CreateModel(
            name="Fonte",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonte",
                "verbose_name_plural": "Fontes",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Funcao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função",
                "verbose_name_plural": "Funções",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Loa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                (
                    "rcl_previa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Receita Corrente Líquida - Prévia (R$)",
                    ),
                ),
                (
                    "receita_corrente_liquida",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Receita Corrente Líquida - RCL (R$)",
                    ),
                ),
                (
                    "perc_disp_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Disp. Global da RCL (%)",
                    ),
                ),
                (
                    "perc_disp_saude",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Disp. Saúde da RCL (%)",
                    ),
                ),
                (
                    "perc_disp_diversos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Disp. Diversos da RCL (%)",
                    ),
                ),
                (
                    "disp_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Disp. Global da RCL (R$)",
                    ),
                ),
                (
                    "disp_saude",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Disp. Saúde da RCL (R$)",
                    ),
                ),
                (
                    "disp_diversos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Disp. Diversos da RCL (R$)",
                    ),
                ),
                (
                    "yaml_obs",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Observações de Rodapé (yaml format)",
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(default=False, verbose_name="Publicado?"),
                ),
            ],
            options={
                "verbose_name": "LOA",
                "verbose_name_plural": "LOAs",
                "ordering": ["-id"],
                "permissions": (
                    ("view_despesasexecutadas", "View Despesas Executadas"),
                ),
            },
        ),
        migrations.CreateModel(
            name="LoaParlamentar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disp_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Disp. Global da RCL (R$)",
                    ),
                ),
                (
                    "disp_saude",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Disp. Saúde da RCL (R$)",
                    ),
                ),
                (
                    "disp_diversos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Disp. Diversos da RCL (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valores do Parlamentar",
                "verbose_name_plural": "Valores dos Parlamentares",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Natureza",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natureza",
                "verbose_name_plural": "Naturezas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="NaturezaJuridica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}$", "Código inválido"
                            )
                        ],
                        verbose_name="Código",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=256, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Natureza Jurídica",
                "verbose_name_plural": "Naturezas Jurídicas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="OficioAjusteLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epigrafe", models.CharField(max_length=100, verbose_name="Epígrafe")),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=cmj.loa.models.m_ajusteloa.ajuste_upload_path,
                        verbose_name="Ofício",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ofício de Ajuste Técnico",
                "verbose_name_plural": "Ofícios de Ajuste Técnico",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Orgao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Órgão",
                "verbose_name_plural": "Órgãos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="PrestacaoContaLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_envio",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Data de Envio",
                    ),
                ),
                ("epigrafe", models.CharField(max_length=100, verbose_name="Epígrafe")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestação de Contas das Emendas Impositivas",
                "verbose_name_plural": "Prestações de Contas das Emendas Impositivas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PrestacaoContaRegistro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detalhamento",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Detalhamento"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("EM_EXECUCAO", "Em Execução"),
                            ("FINALIZADO", "Finalizada"),
                        ],
                        default="EM_EXECUCAO",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Prestação de Conta",
                "verbose_name_plural": "Registros de Prestação de Conta",
                "ordering": ["prestacao_conta__data_envio", "id"],
            },
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa",
                "verbose_name_plural": "Programas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="ReceitaArrecadada",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "tipo",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "historico",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Histórico"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Arrecadada",
                "verbose_name_plural": "Receitas Arrecadadas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReceitaOrcamentaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "historico",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Histórico"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Orçamentária",
                "verbose_name_plural": "Receitas Orçamentárias",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAjusteLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.TextField(blank=True, default="")),
                (
                    "tipo",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Saúde"), (99, "Áreas Diversas")],
                        default=99,
                        verbose_name="Área de aplicação",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Registro do Ajuste Técnico",
                "verbose_name_plural": "Registros do Ajuste Técnico",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAjusteLoaParlamentar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor por Parlamentar (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participação Parlamentar no Registro de Ajuste Técnico",
                "verbose_name_plural": "Participações Parlamentares no Registro de Ajuste Técnico",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ScrapRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mes")),
                ("ano", models.PositiveSmallIntegerField(verbose_name="Ano")),
                ("orgao", models.TextField(verbose_name="Órgão")),
                ("codigo", models.TextField(default="", verbose_name="Código")),
                ("url", models.TextField(unique=True, verbose_name="Órgão")),
                ("content", models.BinaryField(default=b"", editable=True)),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("erro", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "ScrapRecord",
                "verbose_name_plural": "ScrapRecord",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SubFuncao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubFunção",
                "verbose_name_plural": "SubFunções",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="TipoEntidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{3}$", "Código inválido"
                            )
                        ],
                        verbose_name="Código",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=256, verbose_name="Descrição"),
                ),
                (
                    "tipo_geral",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Saúde"),
                            (20, "Educação"),
                            (30, "Assistência Social"),
                            (40, "Segurança Pública"),
                            (50, "Cultura"),
                            (60, "Esporte"),
                            (70, "Outros"),
                        ],
                        default=70,
                        verbose_name="Tipo Geral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Entidade",
                "verbose_name_plural": "Tipos de Entidades",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="UnidadeOrcamentaria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.TextField(verbose_name="Código")),
                (
                    "especificacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Especificação",
                    ),
                ),
                (
                    "recebe_emenda_impositiva",
                    models.BooleanField(
                        default=False, verbose_name="Recebe Verbas Emenda Impositiva"
                    ),
                ),
                (
                    "area",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Saúde"),
                            (20, "Educação"),
                            (30, "Assistência Social"),
                            (40, "Segurança Pública"),
                            (50, "Cultura"),
                            (60, "Esporte"),
                            (70, "Outros"),
                        ],
                        default=70,
                        verbose_name="Tipo Geral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade Orçamentária",
                "verbose_name_plural": "Unidades Orçamentárias",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AgrupamentoEmendaLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agrupamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agrupamentoemendaloa_set",
                        to="loa.agrupamento",
                        verbose_name="Agrupamento de Emenda Impositiva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agrupamento de Emenda Impositiva",
                "verbose_name_plural": "Agrupamentos de Emendas Impositivas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_materia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Despesa Matéria (R$)",
                    ),
                ),
                (
                    "valor_norma",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Despesa Norma (R$)",
                    ),
                ),
                (
                    "acao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="despesa_set",
                        to="loa.acao",
                        verbose_name="Ação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AgrupamentoRegistroContabil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operacao",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "Dedução"), (20, "Inserção")],
                        default=10,
                        verbose_name="Operação",
                    ),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percentual do Valor da Emenda",
                    ),
                ),
                (
                    "agrupamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agrupamentoregistrocontabil_set",
                        to="loa.agrupamento",
                        verbose_name="Agrupamento de Emenda Impositiva",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agrupamentoregistrocontabil_set",
                        to="loa.despesa",
                        verbose_name="Despesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Contábil de Dedução e Inserção em Emendas",
                "verbose_name_plural": "Registros Contábeis de Dedução e Inserção em Emendas",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="agrupamento",
            name="despesas",
            field=models.ManyToManyField(
                related_name="agrupamento_set",
                through="loa.AgrupamentoRegistroContabil",
                through_fields=("agrupamento", "despesa"),
                to="loa.despesa",
                verbose_name="Registro Contabeis Agrupamento",
            ),
        ),
    ]
