# Generated by Django 2.2.28 on 2024-08-02 17:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parlamentares', '0045_auto_20240420_1344'),
        ('materia', '0090_tipomaterialegislativa_nivel_agrupamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('receita_corrente_liquida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Receita Corrente Líquida')),
                ('perc_disp_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Global da RCL (%)')),
                ('perc_disp_saude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Saúde da RCL (%)')),
                ('perc_disp_diversos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Diversos da RCL (%)')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('materia', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loa', to='materia.MateriaLegislativa', verbose_name='Matéria Legislativa')),
            ],
            options={
                'verbose_name': 'Loa - Emendas Impositivas',
                'verbose_name_plural': 'Loa - Emendas Impositivas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoaParlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaparlamentar_set', to='loa.Loa', verbose_name='Loa - Emendas Impositivas')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaparlamentar_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar - Emendas Impositivas')),
            ],
        ),
        migrations.AddField(
            model_name='loa',
            name='parlamentares',
            field=models.ManyToManyField(related_name='loa_set', through='loa.LoaParlamentar', to='parlamentares.Parlamentar', verbose_name='Parlamentares'),
        ),
    ]
