# Generated by Django 2.2.28 on 2024-08-02 20:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0002_auto_20240802_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaparlamentar',
            name='disp_diversos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Diversos da RCL (R$)'),
        ),
        migrations.AddField(
            model_name='loaparlamentar',
            name='disp_saude',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Saúde da RCL (R$)'),
        ),
        migrations.AddField(
            model_name='loaparlamentar',
            name='disp_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Global da RCL (R$)'),
        ),
    ]
