# Generated by Django 2.2.28 on 2024-08-02 20:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0003_auto_20240802_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loa',
            name='disp_diversos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Diversos da RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='disp_saude',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Saúde da RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='disp_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Global da RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='perc_disp_diversos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Diversos da RCL (%)'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='perc_disp_saude',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Saúde da RCL (%)'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='perc_disp_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Global da RCL (%)'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='receita_corrente_liquida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Corrente Líquida'),
        ),
        migrations.AlterField(
            model_name='loaparlamentar',
            name='disp_diversos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Diversos da RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='loaparlamentar',
            name='disp_saude',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Saúde da RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='loaparlamentar',
            name='disp_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disp. Global da RCL (R$)'),
        ),
    ]
