# Generated by Django 5.2.12 on 2026-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0003_viewdb_loa_despesa_consulta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroajusteloa",
            name="emendaloa_old",
        ),
        migrations.AddField(
            model_name="registroajusteloa",
            name="fase",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Registrado"),
                    (40, "Impedimento Técnico"),
                    (60, "Em Execução"),
                    (99, "Finalizado"),
                ],
                default=10,
                verbose_name="Fase",
            ),
        ),
    ]
