# Generated by Django 5.2.15 on 2026-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0004_remove_registroajusteloa_emendaloa_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacaocontaregistro",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("EM_EXECUCAO", "Em Análise/Execução"),
                    ("FINALIZADO", "Finalizada"),
                ],
                default="EM_EXECUCAO",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
    ]
