# Generated by Django 5.2.15 on 2026-08-10 20:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0005_alter_prestacaocontaregistro_situacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivoprestacaocontaloa",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="arquivoprestacaocontaregistro",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
    ]
