# Generated by Django 2.2.28 on 2024-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0005_auto_20240805_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Proposta Legislativa'), (20, 'Aprovada no Poder Legislativo'), (30, 'Aprovada'), (40, 'Impedimento Técnico')], default=10, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Saúde'), (99, 'Áreas Diversas')], default=99, verbose_name='Área de aplicação'),
        ),
    ]
