# Generated by Django 5.2.16 on 2026-08-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("loa", "0006_arquivoprestacaocontaloa_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emendaloa",
            name="bairro",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emendaloa_set",
                to="core.bairro",
                verbose_name="Bairro",
            ),
        ),
    ]
