# Generated by Django 5.2.15 on 2026-08-11 21:37

import cmj.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0006_arquivoprestacaocontaloa_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoHabilitacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=256, verbose_name="Documento")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "nivel_obrigatoriedade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Obrigatório"),
                            (2, "Opcional"),
                            (3, "Facultativo"),
                        ],
                        default=2,
                        verbose_name="Nível de Obrigatoriedade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Habilitação",
                "verbose_name_plural": "Documentos de Habilitação",
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="DocHabEntidadeLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "validado",
                    models.BooleanField(default=False, verbose_name="Validado"),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifier",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "documento_habilitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loa.documentohabilitacao",
                        verbose_name="Documento Habilitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Habilitação da Entidade",
                "verbose_name_plural": "Documentos de Habilitação das Entidades",
            },
            bases=(cmj.mixins.CmjCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DocHabEntidadeLoaArquivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos_habilitacao/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "doc_hab_entidade_loa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loa.dochabentidadeloa",
                        verbose_name="Documento Habilitação Entidade LOA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Documento de Habilitação da Entidade",
                "verbose_name_plural": "Arquivos de Documentos de Habilitação das Entidades",
            },
        ),
        migrations.CreateModel(
            name="EntidadeLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loa.entidade",
                        verbose_name="Entidade",
                    ),
                ),
                (
                    "loa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loa.loa",
                        verbose_name="LOA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidade da LOA",
                "verbose_name_plural": "Entidades da LOA",
                "unique_together": {("loa", "entidade")},
            },
        ),
        migrations.AddField(
            model_name="dochabentidadeloa",
            name="entidade_loa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loa.entidadeloa",
                verbose_name="Entidade LOA",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dochabentidadeloa",
            unique_together={("entidade_loa", "documento_habilitacao")},
        ),
    ]
