# Generated by Django 2.2.28 on 2024-08-12 13:36

import cmj.loa.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0045_auto_20240420_1344'),
        ('loa', '0006_auto_20240805_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioAjusteLoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epigrafe', models.CharField(max_length=100, verbose_name='Epígrafe')),
                ('arquivo', sapl.utils.PortalFileField(blank=True, max_length=512, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=cmj.loa.models.ajuste_upload_path, verbose_name='Ofício')),
            ],
            options={
                'verbose_name': 'Ofício de Ajuste Técnico',
                'verbose_name_plural': 'Ofícios de Ajuste Técnico',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='loa',
            options={'ordering': ['-id'], 'verbose_name': 'LOA - Emendas Impositivas', 'verbose_name_plural': 'LOA - Emendas Impositivas'},
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Proposta Legislativa'), (20, 'Aprovada no Processo Legislativo'), (30, 'Aprovada'), (40, 'Impedimento Técnico'), (50, 'Impedimento Técnico Oficiado')], default=10, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='receita_corrente_liquida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Corrente Líquida - RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='loaparlamentar',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaparlamentar_set', to='loa.Loa', verbose_name='LOA - Emendas Impositivas'),
        ),
        migrations.CreateModel(
            name='RegistroAjusteLoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('emendaloa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registroajusteloa_set', to='loa.EmendaLoa', verbose_name='Emenda Impositiva')),
                ('oficio_ajuste_loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registroajusteloa_set', to='loa.OficioAjusteLoa', verbose_name='Ofício de Ajuste Técnico')),
            ],
            options={
                'verbose_name': 'Registro do Ajuste Técnico',
                'verbose_name_plural': 'Registros do Ajuste Técnico',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='oficioajusteloa',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajusteloa_set', to='loa.Loa', verbose_name='Loa - Emendas Impositivas'),
        ),
        migrations.AddField(
            model_name='oficioajusteloa',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajusteloa_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
