# Generated by Django 2.2.28 on 2024-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0007_auto_20240812_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroajusteloa',
            options={'ordering': ['-id'], 'verbose_name': 'Registro do Ajuste Técnico', 'verbose_name_plural': 'Registros do Ajuste Técnico'},
        ),
        migrations.AddField(
            model_name='registroajusteloa',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Saúde'), (99, 'Áreas Diversas')], default=99, verbose_name='Área de aplicação'),
        ),
    ]
