# Generated by Django 5.2.16 on 2026-08-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0007_emendaloa_bairro"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="acao",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_acao_loa_id_ee4aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=[
                    "loa",
                    "orgao",
                    "unidade",
                    "funcao",
                    "subfuncao",
                    "programa",
                    "acao",
                    "natureza",
                    "fonte",
                ],
                name="loa_despesa_loa_id_003a6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emendaloaregistrocontabil",
            index=models.Index(
                fields=["emendaloa", "despesa"], name="loa_emendal_emendal_51fa13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emendaloaregistrocontabil",
            index=models.Index(
                fields=["despesa", "valor"], name="loa_emendal_despesa_b5768e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fonte",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_fonte_loa_id_dccf51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funcao",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_funcao_loa_id_db5d52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="natureza",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_naturez_loa_id_5f9e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgao",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_orgao_loa_id_3f9b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programa",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_program_loa_id_7c2af1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subfuncao",
            index=models.Index(
                fields=["loa", "codigo"], name="loa_subfunc_loa_id_1f3771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unidadeorcamentaria",
            index=models.Index(
                fields=["loa", "orgao", "codigo"], name="loa_unidade_loa_id_1dc111_idx"
            ),
        ),
    ]
