# Generated by Django 2.2.28 on 2024-08-19 11:20

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0008_auto_20240812_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroajusteloa',
            options={'ordering': ['id'], 'verbose_name': 'Registro do Ajuste Técnico', 'verbose_name_plural': 'Registros do Ajuste Técnico'},
        ),
        migrations.AddField(
            model_name='oficioajusteloa',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
