# Generated by Django 5.2.16 on 2026-09-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0008_acao_loa_acao_loa_id_ee4aae_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loa",
            name="forcar_detalhamento_de_fonte",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Forçar detalhamento de fonte com 3 caracteres para destinação de Emendas Impositivas",
                max_length=3,
                null=True,
                verbose_name="Detalhamento de Fonte ",
            ),
        ),
        migrations.AlterField(
            model_name="emendaloa",
            name="prefixo_indicacao",
            field=models.CharField(
                blank=True,
                default="o(a)",
                max_length=30,
                verbose_name="Prefixo da Unidade",
            ),
        ),
    ]
