# Generated by Django 5.2.16 on 2026-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0009_loa_forcar_detalhamento_de_fonte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loa",
            name="forcar_detalhamento_de_fonte",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Forçar detalhamento de fonte com 3 caracteres para destinação de Emendas Impositivas",
                max_length=3,
                verbose_name="Detalhamento de Fonte",
            ),
        ),
    ]
