# Generated by Django 2.2.28 on 2024-08-26 12:47

from django.db import migrations, models


def transfere_parlamantar_FK2M2M(apps, schema_editor):
    OficioAjusteLoa = apps.get_model('loa', 'OficioAjusteLoa')

    for oficio in OficioAjusteLoa.objects.all():
        oficio.parlamentares.add(oficio.parlamentar)


class Migration(migrations.Migration): 

    dependencies = [
        ('parlamentares', '0045_auto_20240420_1344'),
        ('loa', '0009_auto_20240819_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emendaloa',
            options={'ordering': ['id'], 'permissions': (('emendaloa_full_editor', 'Edição completa de Emendas Impositivas.'),),
                     'verbose_name': 'Emenda Impositiva', 'verbose_name_plural': 'Emendas Impositivas'},
        ),
        migrations.AddField(
            model_name='oficioajusteloa',
            name='parlamentares',
            field=models.ManyToManyField(
                related_name='oficioajusteloa_set', to='parlamentares.Parlamentar', verbose_name='Parlamentares'),
        ),

        migrations.RunPython(transfere_parlamantar_FK2M2M),
    ]
