# Generated by Django 5.2.16 on 2026-10-06 15:58

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0010_alter_loa_forcar_detalhamento_de_fonte"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScrapRecord",
            new_name="ScrapRecordSigep",
        ),
    ]
