# Generated by Django 2.2.28 on 2024-08-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0010_auto_20240826_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficioajusteloa',
            name='parlamentar',
        ),
    ]
