# Generated by Django 5.2.16 on 2026-10-07 12:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0011_scraprecordsigep_rename_scraprecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scraprecordsigep",
            options={
                "ordering": ["id"],
                "verbose_name": "ScrapRecordSigep",
                "verbose_name_plural": "ScrapRecordSigep",
            },
        ),
        migrations.AddField(
            model_name="acao",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="fonte",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="funcao",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="natureza",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="orgao",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="programa",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="subfuncao",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="unidadeorcamentaria",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AlterField(
            model_name="scraprecordsigep",
            name="url",
            field=models.TextField(unique=True, verbose_name="URL"),
        ),
    ]
