# Generated by Django 2.2.28 on 2024-08-26 13:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def transfere_parlamantar_registro_FK2M2M(apps, schema_editor):
    RegistroAjusteLoa = apps.get_model('loa', 'RegistroAjusteLoa')
    RegistroAjusteLoaParlamentar = apps.get_model(
        'loa', 'RegistroAjusteLoaParlamentar')

    for registro in RegistroAjusteLoa.objects.all():
        rp = RegistroAjusteLoaParlamentar()
        rp.registro = registro
        rp.parlamentar = registro.oficio_ajuste_loa.parlamentares.all().first()
        rp.valor = registro.valor
        rp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0045_auto_20240420_1344'),
        ('loa', '0011_remove_oficioajusteloa_parlamentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAjusteLoaParlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=14, verbose_name='Valor por Parlamentar (R$)')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='registroajusteloaparlamentar_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='registroajusteloaparlamentar_set', to='loa.RegistroAjusteLoa', verbose_name='Registro de Ajuste')),
            ],
            options={
                'verbose_name': 'Participação Parlamentar no Registro de Ajuste Técnico',
                'verbose_name_plural': 'Participações Parlamentares no Registro de Ajuste Técnico',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='registroajusteloa',
            name='parlamentares_valor',
            field=models.ManyToManyField(related_name='registroajusteloa_set', through='loa.RegistroAjusteLoaParlamentar',
                                         to='parlamentares.Parlamentar', verbose_name='Parlamentares'),
        ),

        migrations.RunPython(transfere_parlamantar_registro_FK2M2M),
    ]
