# Generated by Django 5.2.16 on 2026-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0012_alter_scraprecordsigep_options_acao_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="search",
            field=models.TextField(blank=True, default=""),
        ),
    ]
