# Generated by Django 2.2.28 on 2024-08-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0012_auto_20240826_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroajusteloa',
            name='valor',
        ),
    ]
