# Generated by Django 2.2.28 on 2024-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0013_remove_registroajusteloa_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='indicacao',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Descrição'),
        ),
    ]
