# Generated by Django 5.2.16 on 2026-10-09 19:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0013_despesa_search"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="despesa",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass("search", name="gin_trgm_ops"),
                name="despesa_search_gin_trgm",
            ),
        ),
    ]
