# Generated by Django 2.2.28 on 2024-08-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0014_emendaloa_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='indicacao',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Indicação'),
        ),
        migrations.CreateModel(
            name='UnidadeOrcamentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Unidade Orçamentária',
                'verbose_name_plural': 'Unidades Orçamentárias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubFuncao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_set', to='loa.Funcao', verbose_name='Função')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'SubFunção',
                'verbose_name_plural': 'SubFunções',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Natureza',
                'verbose_name_plural': 'Naturezas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('especificacao', models.CharField(max_length=256, verbose_name='Especificação')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='loa.Loa', verbose_name='Loa')),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fontes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Acao', verbose_name='Ação')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Fonte', verbose_name='Fonte')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Funcao', verbose_name='Função')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Loa', verbose_name='Loa')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Natureza', verbose_name='Natureza')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Orgao', verbose_name='Órgão')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Programa', verbose_name='Programa')),
                ('subfuncao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.SubFuncao', verbose_name='SubFunção')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.UnidadeOrcamentaria', verbose_name='Unidade Orçamentária')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['id'],
            },
        ),
    ]
