# Generated by Django 2.2.28 on 2024-08-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0015_auto_20240828_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeorcamentaria',
            name='orgao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unidadeorcamentaria_set', to='loa.Orgao', verbose_name='Órgão'),
            preserve_default=False,
        ),
    ]
