# Generated by Django 2.2.28 on 2024-08-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0016_unidadeorcamentaria_orgao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='fonte',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_set', to='loa.Fonte', verbose_name='Fonte'),
        ),
    ]
