# Generated by Django 2.2.28 on 2024-08-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0017_auto_20240828_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='despesa',
            unique_together={('loa', 'orgao', 'unidade', 'funcao', 'subfuncao', 'programa', 'acao', 'fonte', 'natureza')},
        ),
    ]
