# Generated by Django 2.2.28 on 2024-09-01 01:55

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0020_despesaconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
