# Generated by Django 2.2.28 on 2024-09-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0022_emendaloaregistrocontabil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emendaloaregistrocontabil',
            options={'ordering': ['id'], 'verbose_name': 'Registro Contábil de Dedução e Inserção em Emendas', 'verbose_name_plural': 'Registros Contábeis de Dedução e Inserção em Emendas'},
        ),
        migrations.AlterUniqueTogether(
            name='emendaloaregistrocontabil',
            unique_together={('emendaloa', 'despesa')},
        ),
    ]
