# Generated by Django 2.2.28 on 2024-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0024_auto_20240902_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emendaloaregistrocontabil',
            name='natureza',
        ),
        migrations.RemoveField(
            model_name='emendaloaregistrocontabil',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='emendaloaregistrocontabil',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='acao',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='prefixo_finalidade',
            field=models.CharField(blank=True, default='destinado a', max_length=30, verbose_name='Prefixo da Finalidade'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='prefixo_indicacao',
            field=models.CharField(blank=True, default='o(a)', max_length=30, verbose_name='Prefixo da Indicação'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='natureza',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='subfuncao',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
        migrations.AlterField(
            model_name='unidadeorcamentaria',
            name='especificacao',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Especificação'),
        ),
    ]
