# Generated by Django 2.2.28 on 2024-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0026_recria_view_despesa_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emendaloa',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Proposta Legislativa'), (15, 'Em edição pela Contabilidade'), (17, 'Liberado pela Contabilidade'), (20, 'Aprovada no Processo Legislativo'), (30, 'Aprovada'), (40, 'Impedimento Técnico'), (50, 'Impedimento Técnico Oficiado')], default=10, verbose_name='Fase'),
        ),
    ]
