# Generated by Django 2.2.28 on 2024-09-06 18:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0027_auto_20240903_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='valor_materia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Disp. Diversos da RCL (R$)'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='valor_norma',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Disp. Diversos da RCL (R$)'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Proposta Legislativa'), (12, 'Proposta Liberada para Edição Contábil'), (15, 'Em edição pela Contabilidade'), (17, 'Liberado pela Contabilidade'), (20, 'Aprovada no Processo Legislativo'), (30, 'Aprovada'), (40, 'Impedimento Técnico'), (50, 'Impedimento Técnico Oficiado')], default=10, verbose_name='Fase'),
        ),
    ]
