# Generated by Django 2.2.28 on 2024-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0028_auto_20240906_1546'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                drop view if exists loa_despesa_consulta;
                create or replace view loa_despesa_consulta as
                    select
                        d.id as id,
                        d.loa_id as loa_id,

                        d.valor_materia as valor_materia,
                        d.valor_norma as valor_norma,

                        f.codigo || '.' || sf.codigo || '.' || p.codigo || '.' || a.codigo as codigo,
                        a.especificacao as especificacao,

                        o.codigo as cod_orgao,
                        o.especificacao as esp_orgao,

                        u.codigo as cod_unidade,
                        u.especificacao as esp_unidade,

                        n.codigo as cod_natureza,
                        n.especificacao as esp_natureza,

                        fte.codigo as cod_fonte


                    from loa_despesa d
                        inner join loa_loa        l on (d.loa_id = l.id)

                        inner join loa_funcao     f on (d.funcao_id = f.id)
                        inner join loa_subfuncao sf on (d.subfuncao_id = sf.id)

                        inner join loa_programa   p on (d.programa_id = p.id)
                        inner join loa_acao       a on (d.acao_id = a.id)

                        inner join loa_natureza   n on (d.natureza_id = n.id)

                        left join loa_fonte     fte on (d.fonte_id = fte.id)

                        inner join loa_orgao                  o on (d.orgao_id = o.id)
                        inner join loa_unidadeorcamentaria    u on (d.unidade_id = u.id)


            ;'''
        ),
    ]
