# Generated by Django 2.2.28 on 2024-09-06 19:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0029_recria_view_despesa_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor_materia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor Despesa Matéria (R$)'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_norma',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor Despesa Norma (R$)'),
        ),
    ]
