# Generated by Django 2.2.28 on 2024-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0030_auto_20240906_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='loa',
            name='yaml_obs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observações de Rodapé (yaml format)'),
        ),
    ]
