# Generated by Django 2.2.28 on 2024-09-15 01:00

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0031_loa_yaml_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('orgao', models.TextField(verbose_name='Órgão')),
                ('codigo', models.TextField(default='', verbose_name='Código')),
                ('url', models.TextField(unique=True, verbose_name='Órgão')),
                ('content', models.BinaryField()),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrap_set', to='loa.ScrapRecord')),
            ],
            options={
                'verbose_name': 'ScrapRecord',
                'verbose_name_plural': 'ScrapRecord',
                'ordering': ['id'],
            },
        ),
    ]
