# Generated by Django 2.2.28 on 2024-09-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0032_scraprecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraprecord',
            name='content',
        ),
    ]
