# Generated by Django 2.2.28 on 2024-09-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0033_remove_scraprecord_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprecord',
            name='content',
            field=models.BinaryField(default=b'', editable=True),
        ),
    ]
