# Generated by Django 2.2.28 on 2024-09-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0034_scraprecord_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprecord',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
