# Generated by Django 2.2.28 on 2024-09-16 16:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0035_scraprecord_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaPaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(verbose_name='Código')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor (R$)')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesapaga_set', to='loa.Orgao', verbose_name='Órgão')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesapaga_set', to='loa.UnidadeOrcamentaria', verbose_name='Unidade Financeira')),
            ],
            options={
                'verbose_name': 'Despesa Paga',
                'verbose_name_plural': 'Despesas Pagas',
                'ordering': ['id'],
            },
        ),
    ]
