# Generated by Django 2.2.28 on 2024-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0036_despesapaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesapaga',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
