# Generated by Django 2.2.28 on 2024-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0037_auto_20240916_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesapaga',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
