# Generated by Django 2.2.28 on 2024-09-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0038_auto_20240917_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesapaga',
            name='unidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesapaga_set', to='loa.UnidadeOrcamentaria', verbose_name='Unidade Financeira'),
        ),
    ]
