# Generated by Django 2.2.28 on 2024-09-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0039_auto_20240921_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesapaga',
            name='natureza',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesapaga_set', to='loa.Natureza', verbose_name='Natureza'),
        ),
    ]
