# Generated by Django 2.2.28 on 2024-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0041_auto_20240922_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesapaga',
            name='tipo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='scraprecord',
            name='erro',
            field=models.BooleanField(default=False),
        ),
    ]
