# Generated by Django 2.2.28 on 2024-09-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0043_receitaarrecadada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceitaArrecadada',
        ),
    ]
