# Generated by Django 2.2.28 on 2024-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0045_receitaarrecadada_receitaorcamentaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitaarrecadada',
            name='historico',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Histórico'),
        ),
    ]
