# Generated by Django 4.2.16 on 2024-11-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0049_alter_emendaloa_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='unidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emendaloa_set', to='loa.unidadeorcamentaria', verbose_name='Unidade Orçamentária'),
        ),
    ]
