# Generated by Django 4.2.16 on 2024-11-06 13:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0051_unidadeorcamentaria_recebe_emenda_impositiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome do Agrupamento')),
                ('observacoes', models.TextField(verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Agrupamento de Emenda Impositiva',
                'verbose_name_plural': 'Agrupamentos de Emendas Impositivas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgrupamentoEmendaLoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentoemendaloa_set', to='loa.agrupamento', verbose_name='Agrupamento de Emenda Impositiva')),
                ('emendaloa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentoemendaloa_set', to='loa.emendaloa', verbose_name='Emenda Impositiva')),
            ],
            options={
                'verbose_name': 'Agrupamento de Emenda Impositiva',
                'verbose_name_plural': 'Agrupamentos de Emendas Impositivas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='agrupamento',
            name='emendas',
            field=models.ManyToManyField(related_name='agrupamento_set', through='loa.AgrupamentoEmendaLoa', to='loa.emendaloa', verbose_name='Emendas Impositivas'),
        ),
        migrations.AddField(
            model_name='agrupamento',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agrupamento_set', to='loa.loa', verbose_name='LOA - Emendas Impositivas'),
        ),
        migrations.CreateModel(
            name='AgrupamentoRegistroContabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.PositiveSmallIntegerField(choices=[(10, 'Dedução'), (20, 'Inserção')], default=10, verbose_name='Operação')),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual do Valor da Emenda')),
                ('agrupamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentoregistrocontabil_set', to='loa.agrupamento', verbose_name='Agrupamento de Emenda Impositiva')),
                ('despesa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentoregistrocontabil_set', to='loa.despesa', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Registro Contábil de Dedução e Inserção em Emendas',
                'verbose_name_plural': 'Registros Contábeis de Dedução e Inserção em Emendas',
                'ordering': ['id'],
                'unique_together': {('agrupamento', 'despesa')},
            },
        ),
    ]
