# Generated by Django 4.2.16 on 2024-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0052_agrupamento_alter_emendaloa_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupamentoemendaloa',
            name='emendaloa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentoemendaloa', to='loa.emendaloa', verbose_name='Emenda Impositiva'),
        ),
    ]
