# Generated by Django 4.2.16 on 2024-11-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0048_alter_votante_user'),
        ('loa', '0053_alter_agrupamentoemendaloa_emendaloa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emendaloa',
            options={'ordering': ['id'], 'permissions': (('emendaloa_full_editor', 'Edição completa de Emendas Impositivas.'),), 'verbose_name': 'Emenda Impositiva/Modificativa', 'verbose_name_plural': 'Emendas Impositivas/Modificativas'},
        ),
        migrations.AlterField(
            model_name='acao',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Em.Imp. Saúde'), (99, 'Em.Imp. Áreas Diversas'), (0, 'Emenda Modificativa')], default=99, verbose_name='Área de aplicação'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='unidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendaloa_set', to='loa.unidadeorcamentaria', verbose_name='Unidade Orçamentária'),
        ),
        migrations.AlterField(
            model_name='emendaloaregistrocontabil',
            name='despesa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrocontabil_set', to='loa.despesa', verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='funcao',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='natureza',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='oficioajusteloa',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajusteloa_set', to='loa.loa', verbose_name='Loa - Emendas Impositivas'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='registroajusteloa',
            name='emendaloa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registroajusteloa_set', to='loa.emendaloa', verbose_name='Emenda Impositiva'),
        ),
        migrations.AlterField(
            model_name='registroajusteloa',
            name='oficio_ajuste_loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registroajusteloa_set', to='loa.oficioajusteloa', verbose_name='Ofício de Ajuste Técnico'),
        ),
        migrations.AlterField(
            model_name='registroajusteloaparlamentar',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registroajusteloaparlamentar_set', to='parlamentares.parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='registroajusteloaparlamentar',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registroajusteloaparlamentar_set', to='loa.registroajusteloa', verbose_name='Registro de Ajuste'),
        ),
        migrations.AlterField(
            model_name='subfuncao',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
        migrations.AlterField(
            model_name='unidadeorcamentaria',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loa.loa', verbose_name='Loa'),
        ),
    ]
