# Generated by Django 4.2.16 on 2024-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0054_alter_emendaloa_options_alter_acao_loa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrupamento',
            options={'ordering': ['id'], 'verbose_name': 'Agrupamento de Emenda Impositiva/Modificativas', 'verbose_name_plural': 'Agrupamentos de Emendas Impositivas/Modificativas'},
        ),
        migrations.AddField(
            model_name='agrupamento',
            name='despesas',
            field=models.ManyToManyField(related_name='agrupamento_set', through='loa.AgrupamentoRegistroContabil', to='loa.despesa', verbose_name='Registro Contabeis Agrupamento'),
        ),
        migrations.AlterField(
            model_name='agrupamento',
            name='emendas',
            field=models.ManyToManyField(related_name='agrupamento_set', through='loa.AgrupamentoEmendaLoa', to='loa.emendaloa', verbose_name='Emendas Impositivas/Modificativas'),
        ),
        migrations.AlterField(
            model_name='unidadeorcamentaria',
            name='recebe_emenda_impositiva',
            field=models.BooleanField(default=False, verbose_name='Recebe Verbas Emenda Impositiva'),
        ),
    ]
