# Generated by Django 4.2.19 on 2025-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0056_alter_emendaloa_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emendaloa',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Proposta Legislativa'), (12, 'Proposta Liberada para Edição Contábil'), (15, 'Em edição pela Contabilidade'), (17, 'Liberado pela Contabilidade'), (20, 'Matéria protocolada, em tramitação'), (25, 'Aprovada no Processo Legislativo'), (30, 'Aprovada'), (40, 'Impedimento Técnico'), (50, 'Impedimento Técnico Sanado')], default=10, verbose_name='Fase'),
        ),
    ]
