# Generated by Django 4.2.19 on 2025-03-08 01:58

from decimal import Decimal
from django.db import migrations, models


def update_rcl_previa(apps, schema_editor):

    Loa = apps.get_model('loa', 'loa')

    for loa in Loa.objects.all():
        loa.rcl_previa = loa.receita_corrente_liquida
        loa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0057_alter_emendaloa_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='loa',
            name='rcl_previa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Receita Corrente Líquida - Prévia (R$)'),
        ),

        migrations.RunPython(update_rcl_previa)
    ]
