# Generated by Django 4.2.19 on 2025-04-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0058_loa_rcl_previa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loa',
            options={'ordering': ['-id'], 'verbose_name': 'LOA', 'verbose_name_plural': 'LOAs'},
        ),
        migrations.AlterField(
            model_name='agrupamento',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agrupamento_set', to='loa.loa', verbose_name='LOA'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emendaloa_set', to='loa.loa', verbose_name='LOA'),
        ),
        migrations.AlterField(
            model_name='loaparlamentar',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaparlamentar_set', to='loa.loa', verbose_name='LOA'),
        ),
        migrations.AlterField(
            model_name='oficioajusteloa',
            name='loa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajusteloa_set', to='loa.loa', verbose_name='LOA'),
        ),
    ]
