# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0059_alter_loa_options_alter_agrupamento_loa_and_more'),
        ('parlamentares', '0050_alter_composicaomesa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupamento',
            name='despesas',
            field=models.ManyToManyField(related_name='agrupamento_set', through='loa.AgrupamentoRegistroContabil', through_fields=('agrupamento', 'despesa'), to='loa.despesa', verbose_name='Registro Contabeis Agrupamento'),
        ),
        migrations.AlterField(
            model_name='agrupamento',
            name='emendas',
            field=models.ManyToManyField(related_name='agrupamento_set', through='loa.AgrupamentoEmendaLoa', through_fields=('agrupamento', 'emendaloa'), to='loa.emendaloa', verbose_name='Emendas Impositivas/Modificativas'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='parlamentares',
            field=models.ManyToManyField(related_name='emendaloa_set', through='loa.EmendaLoaParlamentar', through_fields=('emendaloa', 'parlamentar'), to='parlamentares.parlamentar', verbose_name='Parlamentares'),
        ),
        migrations.AlterField(
            model_name='loa',
            name='parlamentares',
            field=models.ManyToManyField(related_name='loa_set', through='loa.LoaParlamentar', through_fields=('loa', 'parlamentar'), to='parlamentares.parlamentar', verbose_name='Parlamentares'),
        ),
        migrations.AlterField(
            model_name='registroajusteloa',
            name='parlamentares_valor',
            field=models.ManyToManyField(related_name='registroajusteloa_set', through='loa.RegistroAjusteLoaParlamentar', through_fields=('registro', 'parlamentar'), to='parlamentares.parlamentar', verbose_name='Parlamentares'),
        ),
    ]
