# Generated by Django 5.2.3 on 2025-09-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0060_alter_agrupamento_despesas_alter_agrupamento_emendas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loa',
            options={'ordering': ['-id'], 'permissions': (('view_despesasexecutadas', 'View Despesas Executadas'),), 'verbose_name': 'LOA', 'verbose_name_plural': 'LOAs'},
        ),
    ]
