# Generated by Django 5.2.3 on 2025-09-19 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0061_alter_loa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loa',
            name='despesa_default_deducao_diversos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loa_despesa_default_deducao_diversos', to='loa.despesa', verbose_name='Despesa Default Dedução Diversos'),
        ),
        migrations.AddField(
            model_name='loa',
            name='despesa_default_deducao_saude',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loa_despesa_default_deducao_saude', to='loa.despesa', verbose_name='Despesa Default Dedução Saúde'),
        ),
    ]
