# Generated by Django 5.2.3 on 2025-09-23 17:31

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0062_loa_despesa_default_deducao_diversos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Código inválido')], verbose_name='Código')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Natureza Jurídica',
                'verbose_name_plural': 'Naturezas Jurídicas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=256, verbose_name='Nome')),
                ('razao_social', models.CharField(max_length=256, verbose_name='Nome Empresarial')),
                ('cpfcnpj', models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ')),
                ('cnes', models.CharField(blank=True, default=None, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'CNES inválido')], verbose_name='CNES')),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('natureza_juridica', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loa.naturezajuridica', verbose_name='Natureza Jurídica')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nome_fantasia'],
                'unique_together': {('cpfcnpj', 'cnes')},
            },
        ),
    ]
