# Generated by Django 5.2.3 on 2025-09-23 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0062_loa_despesa_default_deducao_diversos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome')),
                ('nome_empresarial', models.CharField(max_length=256, verbose_name='Nome Empresarial')),
                ('cnpj', models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ')),
                ('cnes', models.CharField(blank=True, default=None, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'CNES inválido')], verbose_name='CNES')),
                ('natureza_juridica', models.PositiveSmallIntegerField(choices=[(10, 'Administração Pública'), (20, 'Entidades empresariais'), (30, 'Entidades sem fins lucrativos'), (99, 'Outras')], default=99, verbose_name='Natureza Jurídica')),
                ('logradouro', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='Jataí', max_length=128, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], default='GO', max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, default=None, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP inválido')], verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default=None, max_length=256, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nome'],
            },
        ),
    ]
