# Generated by Django 5.2.3 on 2025-09-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0063_naturezajuridica_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='entidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendaloa_set', to='loa.entidade', verbose_name='Entidade'),
        ),
    ]
