# Generated by Django 5.2.3 on 2025-09-23 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0064_emendaloa_entidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Código inválido')], verbose_name='Código')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descrição')),
                ('tipo_geral', models.PositiveSmallIntegerField(choices=[(10, 'Saúde'), (20, 'Educação'), (30, 'Assistência Social'), (40, 'Segurança Pública'), (50, 'Cultura'), (60, 'Esporte'), (70, 'Outros')], default=70, verbose_name='Tipo Geral')),
            ],
            options={
                'verbose_name': 'Tipo de Entidade',
                'verbose_name_plural': 'Tipos de Entidades',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='entidade',
            name='tipo_entidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loa.tipoentidade', verbose_name='Tipo de Entidade'),
        ),
    ]
