# Generated by Django 5.2.3 on 2025-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0065_tipoentidade_entidade_tipo_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
