# Generated by Django 5.2.3 on 2025-09-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0066_entidade_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loa',
            name='despesa_default_deducao_educacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loa_despesa_default_deducao_educacao', to='loa.despesa', verbose_name='Despesa Default Dedução Educação'),
        ),
    ]
