# Generated by Django 5.2.3 on 2025-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0067_loa_despesa_default_deducao_educacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeorcamentaria',
            name='area',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Saúde'), (20, 'Educação'), (30, 'Assistência Social'), (40, 'Segurança Pública'), (50, 'Cultura'), (60, 'Esporte'), (70, 'Outros')], default=70, verbose_name='Tipo Geral'),
        ),
    ]
