# Generated by Django 5.2.3 on 2025-10-31 15:44

import cmj.loa.models
import django.core.serializers.json
import django.db.models.deletion
import sapl.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0068_unidadeorcamentaria_area'),
        ('materia', '0103_statustramitacao_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emendaloa',
            name='materia',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emendaloa', to='materia.materialegislativa', verbose_name='Matéria Legislativa'),
        ),
        migrations.CreateModel(
            name='PrestacaoContaLoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(blank=True, default=None, null=True, verbose_name='Data de Envio')),
                ('epigrafe', models.CharField(max_length=100, verbose_name='Epígrafe')),
                ('metadata', models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados')),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacaoconta_set', to='loa.loa', verbose_name='LOA')),
            ],
            options={
                'verbose_name': 'Prestação de Conta',
                'verbose_name_plural': 'Prestações de Conta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoPrestacaoContaLoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', sapl.utils.PortalFileField(blank=True, max_length=512, null=True, upload_to=cmj.loa.models.prestacaoconta_upload_path, verbose_name='Arquivo Anexo')),
                ('descricao', models.CharField(blank=True, default='', max_length=256, verbose_name='Descrição')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivoprestacaocontaloa_set', to='loa.prestacaocontaloa', verbose_name='Prestação de Conta LOA')),
            ],
            options={
                'verbose_name': 'Arquivo da Prestação de Conta LOA',
                'verbose_name_plural': 'Arquivos da Prestação de Conta LOA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrestacaoContaRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.TextField(blank=True, default='', null=True, verbose_name='Detalhamento')),
                ('situacao', models.CharField(choices=[('EM_TRAMITACAO', 'Em Tramitação'), ('FINALIZADO', 'Finalizado'), ('OUTRO', 'Outros (Detalhar)')], default='EM_TRAMITACAO', max_length=20, verbose_name='Situação')),
                ('emendaloa', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacaocontaregistro_set', to='loa.emendaloa', verbose_name='Emenda Impositiva')),
                ('prestacao_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacaocontaregistro_set', to='loa.prestacaocontaloa', verbose_name='Prestação de Conta LOA')),
                ('registro_ajuste', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestacaocontaregistro_set', to='loa.registroajusteloa', verbose_name='Registro de Ajuste Técnico')),
            ],
            options={
                'verbose_name': 'Registro de Prestação de Conta',
                'verbose_name_plural': 'Registros de Prestação de Conta',
                'ordering': ['id'],
            },
        ),
    ]
