# Generated by Django 5.2.8 on 2025-12-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0069_alter_emendaloa_materia_prestacaocontaloa_and_more'),
        ('materia', '0105_materiaemtramitacao_replace'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='proposicao',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emendaloa', to='materia.proposicao', verbose_name='Proposição Legislativa'),
        ),
        migrations.AlterField(
            model_name='emendaloa',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Proposta Legislativa'), (12, 'Proposta Liberada para Edição Contábil'), (15, 'Em edição pela Contabilidade'), (17, 'Liberado pela Contabilidade e/ou Aguardando Protocolo'), (20, 'Matéria protocolada, em tramitação'), (25, 'Aprovada no Processo Legislativo'), (30, 'Aprovada'), (40, 'Impedimento Técnico'), (50, 'Impedimento Técnico Sanado')], default=10, verbose_name='Fase'),
        ),
    ]
