# Generated by Django 5.2.8 on 2025-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0070_emendaloa_proposicao_alter_emendaloa_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendaloa',
            name='search',
            field=models.TextField(blank=True, default=''),
        ),
    ]
