# Generated by Django 5.2.11 on 2026-02-27 12:09

import cmj.loa.models
import django.db.models.deletion
import sapl.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0071_emendaloa_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPrestacaoContaRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', sapl.utils.PortalFileField(blank=True, max_length=512, null=True, upload_to=cmj.loa.models.prestacaoconta_upload_path, verbose_name='Arquivo Anexo')),
                ('descricao', models.CharField(blank=True, default='', max_length=256, verbose_name='Descrição')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivoprestacaocontaregistro_set', to='loa.prestacaocontaregistro', verbose_name='Registro de Prestação de Conta')),
            ],
            options={
                'verbose_name': 'Arquivo do Registro de Prestação de Conta',
                'verbose_name_plural': 'Arquivos dos Registros de Prestação de Conta',
                'ordering': ['id'],
            },
        ),
    ]
