# Generated by Django 5.2.11 on 2026-03-01 00:23

import cmj.loa.models
import sapl.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0072_arquivoprestacaocontaregistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivoprestacaocontaregistro',
            options={'ordering': ['id'], 'verbose_name': 'Arquivo do Registro de Prestação de Conta', 'verbose_name_plural': 'Arquivos do Registro de Prestação de Conta'},
        ),
        migrations.AlterField(
            model_name='arquivoprestacaocontaregistro',
            name='arquivo',
            field=sapl.utils.PortalFileField(blank=True, max_length=512, null=True, upload_to=cmj.loa.models.prestacaocontaregistro_upload_path, verbose_name='Arquivo Anexo'),
        ),
    ]
