# Generated by Django 5.2.11 on 2026-03-01 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0074_trigram_extension_emendaloa_search_gin_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroajusteloa',
            name='unidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registroajusteloa_set', to='loa.unidadeorcamentaria', verbose_name='Unidade Orçamentária'),
        ),
    ]
