# Generated by Django 5.2.11 on 2026-03-02 17:09

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0075_registroajusteloa_unidade'),
        ('parlamentares', '0052_cargomesa_presidente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestacaocontaloa',
            options={'ordering': ['id'], 'verbose_name': 'Prestação de Contas do Orçamento Impositivo', 'verbose_name_plural': 'Prestações de Contas do Orçamento Impositivo'},
        ),
        migrations.AddField(
            model_name='registroajusteloa',
            name='search',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='registroajusteloa',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('search', name='gin_trgm_ops'), name='loa_rjl_search_gin_trgm'),
        ),
    ]
