# Generated by Django 5.2.11 on 2026-03-19 18:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0078_registroajusteloa_emendaloa_m2m_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loa",
            name="disp_diversos",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Disp. Diversos da RCL (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="loa",
            name="disp_saude",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Disp. Saúde da RCL (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="loa",
            name="disp_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Disp. Global da RCL (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="loaparlamentar",
            name="disp_diversos",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Disp. Diversos da RCL (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="loaparlamentar",
            name="disp_saude",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Disp. Saúde da RCL (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="loaparlamentar",
            name="disp_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Disp. Global da RCL (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="registroajusteloaparlamentar",
            name="registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registroajusteloaparlamentar_set",
                to="loa.registroajusteloa",
                verbose_name="Registro de Ajuste",
            ),
        ),
    ]
