# Generated by Django 5.2.11 on 2026-03-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0079_alter_loa_disp_diversos_alter_loa_disp_saude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestacaocontaloa",
            options={
                "ordering": ["id"],
                "verbose_name": "Prestação de Contas das Emendas Impositivas",
                "verbose_name_plural": "Prestações de Contas das Emendas Impositivas",
            },
        ),
        migrations.AlterModelOptions(
            name="prestacaocontaregistro",
            options={
                "ordering": ["prestacao_conta__data_envio", "id"],
                "verbose_name": "Registro de Prestação de Conta",
                "verbose_name_plural": "Registros de Prestação de Conta",
            },
        ),
        migrations.AlterField(
            model_name="emendaloa",
            name="fase",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "Proposta Legislativa"),
                    (12, "Proposta Liberada para Edição Contábil"),
                    (15, "Em edição pela Contabilidade"),
                    (17, "Liberado pela Contabilidade e/ou Aguardando Protocolo"),
                    (20, "Matéria protocolada, em tramitação"),
                    (25, "Aprovada no Processo Legislativo"),
                    (30, "Aprovada"),
                    (40, "Impedimento Técnico"),
                    (50, "Emenda Redefinida/Sanada"),
                    (60, "Em Execução"),
                    (99, "Finalizada"),
                ],
                default=10,
                verbose_name="Fase",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaocontaregistro",
            name="situacao",
            field=models.CharField(
                choices=[("EM_EXECUCAO", "Em Execução"), ("FINALIZADO", "Finalizada")],
                default="EM_EXECUCAO",
                max_length=20,
                verbose_name="Situação",
            ),
        ),
        migrations.CreateModel(
            name="EmendaLoaHistoricoFase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Proposta Legislativa"),
                            (12, "Proposta Liberada para Edição Contábil"),
                            (15, "Em edição pela Contabilidade"),
                            (
                                17,
                                "Liberado pela Contabilidade e/ou Aguardando Protocolo",
                            ),
                            (20, "Matéria protocolada, em tramitação"),
                            (25, "Aprovada no Processo Legislativo"),
                            (30, "Aprovada"),
                            (40, "Impedimento Técnico"),
                            (50, "Emenda Redefinida/Sanada"),
                            (60, "Em Execução"),
                            (99, "Finalizada"),
                        ],
                        default=10,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
                (
                    "emendaloa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emendaloahistoricofase_set",
                        to="loa.emendaloa",
                        verbose_name="Emenda Impositiva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Fase da Emenda Impositiva",
                "verbose_name_plural": "Históricos de Fase das Emendas Impositivas",
                "ordering": ["timestamp"],
            },
        ),
    ]
