# Generated by Django 5.2.11 on 2026-03-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0080_alter_prestacaocontaloa_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emendaloahistoricofase",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Histórico de Fase da Emenda Impositiva",
                "verbose_name_plural": "Históricos de Fase das Emendas Impositivas",
            },
        ),
        migrations.AddField(
            model_name="registroajusteloa",
            name="entidade",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registroajusteloa_set",
                to="loa.entidade",
                verbose_name="Entidade",
            ),
        ),
    ]
