# Generated by Django 5.2.11 on 2026-03-30 12:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0081_alter_emendaloahistoricofase_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empenho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.PositiveIntegerField(verbose_name="Código")),
                (
                    "cpfcnpj",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="CpfCNPJ"
                    ),
                ),
                (
                    "nome",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "tipo",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Tipo"
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "modalidade",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Modalidade"
                    ),
                ),
                (
                    "numero_licitacao",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Número da Licitação",
                    ),
                ),
                (
                    "historico",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Histórico"
                    ),
                ),
                (
                    "dotacao",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Dotação"
                    ),
                ),
                (
                    "processo",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Processo"
                    ),
                ),
                (
                    "valor_empenhado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Empenhado (R$)",
                    ),
                ),
                (
                    "valor_liquidado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Liquidado (R$)",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor Pago (R$)",
                    ),
                ),
                (
                    "acao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.acao",
                        verbose_name="Ação",
                    ),
                ),
                (
                    "fonte",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.fonte",
                        verbose_name="Fonte",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.funcao",
                        verbose_name="Função",
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.natureza",
                        verbose_name="Natureza",
                    ),
                ),
                (
                    "orgao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.orgao",
                        verbose_name="Órgão",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.programa",
                        verbose_name="Programa",
                    ),
                ),
                (
                    "subfuncao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.subfuncao",
                        verbose_name="Subfunção",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenho_set",
                        to="loa.unidadeorcamentaria",
                        verbose_name="Unidade Financeira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empenho",
                "verbose_name_plural": "Empenhos",
                "ordering": ["id"],
            },
        ),
    ]
