# Generated by Django 5.2.11 on 2026-03-30 13:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0082_empenho"),
    ]

    operations = [
        migrations.AddField(
            model_name="empenho",
            name="valor_anulado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Valor Anulado (R$)",
            ),
        ),
    ]
