# Generated by Django 5.2.11 on 2026-03-30 13:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0083_empenho_valor_anulado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empenho",
            name="valor_pago",
        ),
        migrations.AddField(
            model_name="empenho",
            name="valor_pago_bruto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Valor Pago Bruto (R$)",
            ),
        ),
    ]
