# Generated by Django 5.2.11 on 2026-03-30 19:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0084_remove_empenho_valor_pago_empenho_valor_pago_bruto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empenho",
            name="valor_pago_bruto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Valor Pago (Bruto) (R$)",
            ),
        ),
        migrations.CreateModel(
            name="EmpenhosDeEmendaLoa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emendaloa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhosdeemendaloa_set",
                        to="loa.emendaloa",
                        verbose_name="Emenda Impositiva",
                    ),
                ),
                (
                    "empenho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhosdeemendaloa_set",
                        to="loa.empenho",
                        verbose_name="Empenho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empenho de Emenda Impositiva",
                "verbose_name_plural": "Empenhos de Emendas Impositivas",
                "ordering": ["id"],
            },
        ),
    ]
