# Generated by Django 5.2.11 on 2026-03-30 19:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0085_alter_empenho_valor_pago_bruto_empenhosdeemendaloa"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesapaga",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
        migrations.AddField(
            model_name="empenho",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="Metadados",
            ),
        ),
    ]
