# Generated by Django 5.2.11 on 2026-03-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0086_despesapaga_metadata_empenho_metadata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="empenhosdeemendaloa",
            unique_together={("emendaloa", "empenho")},
        ),
    ]
