# Generated by Django 5.2.11 on 2026-03-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0087_alter_empenhosdeemendaloa_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="empenhosdeemendaloa",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="empenhosdeemendaloa",
            name="ajuste",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empenhosdeemendaloa_set",
                to="loa.registroajusteloa",
                verbose_name="Registro de Ajuste Técnico",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="empenhosdeemendaloa",
            unique_together={("emendaloa", "ajuste", "empenho")},
        ),
    ]
