# Generated by Django 5.2.12 on 2026-04-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0088_alter_empenhosdeemendaloa_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpenhoEmendaAjuste",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ajuste",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhoemendaajuste_set",
                        to="loa.registroajusteloa",
                        verbose_name="Registro de Ajuste Técnico",
                    ),
                ),
                (
                    "emendaloa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhoemendaajuste_set",
                        to="loa.emendaloa",
                        verbose_name="Emenda Impositiva",
                    ),
                ),
                (
                    "empenho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhoemendaajuste_set",
                        to="loa.empenho",
                        verbose_name="Empenho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empenho de Emenda e/ou Ajuste Técnico",
                "verbose_name_plural": "Empenhos de Emendas e/ou Ajustes Técnicos",
                "ordering": ["id"],
                "unique_together": {("emendaloa", "ajuste", "empenho")},
            },
        ),
        migrations.DeleteModel(
            name="EmpenhosDeEmendaLoa",
        ),
    ]
