# Generated by Django 5.2.12 on 2026-04-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0089_empenhoemendaajuste_delete_empenhosdeemendaloa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empenhoemendaajuste",
            name="emendaloa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empenhoemendaajuste_set",
                to="loa.emendaloa",
                verbose_name="Emenda Impositiva",
            ),
        ),
    ]
