# Generated by Django 5.2.12 on 2026-04-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0091_alter_despesa_acao_alter_despesa_fonte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empenho",
            name="codigo",
            field=models.PositiveIntegerField(unique=True, verbose_name="Código"),
        ),
    ]
