# Generated by Django 5.2.12 on 2026-04-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0092_alter_empenho_codigo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="empenho",
            index=models.Index(fields=["codigo"], name="idx_empenho_codigo"),
        ),
    ]
