# Generated by Django 5.2.12 on 2026-04-03 14:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loa", "0093_empenho_idx_empenho_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empenho",
            name="search",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="empenho",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass("search", name="gin_trgm_ops"),
                name="empenho_search_gin_trgm",
            ),
        ),
    ]
