# Generated by Django 5.2.3 on 2025-10-08 20:27

import cmj.painelset.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parlamentares', '0051_filiacao_autor_alter_filiacao_parlamentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Nome do Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('start_previsto', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora Prevista de Início')),
                ('start_real', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora Real de Início')),
                ('end_real', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora Real de Término')),
                ('duration', models.DurationField(help_text='Duração total planejada do evento', verbose_name='Duração do Evento')),
                ('ips_mesas', models.CharField(blank=True, default='', help_text='IPs das mesas associadas a este indivíduo, separados por vírgula', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_ip', message='IP inválido. Formato esperado: xxx.xxx.xxx.xxx (separados por espaço para múltiplos IPs).', regex='^(\\d{1,3}(\\.\\d{1,3}){3})*(\\s(\\d{1,3}(\\.\\d{1,3}){3}))*$')])),
                ('comunicar_com_mesas', models.BooleanField(default=False, help_text='Comunicar com mesas via OSC?', verbose_name='Comunicar com Mesas')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, cmj.painelset.models.CronometroMixin),
        ),
        migrations.CreateModel(
            name='Cronometro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('duration', models.DurationField(help_text='Duração planejada do cronômetro')),
                ('state', models.CharField(choices=[('stopped', 'Parado'), ('running', 'Executando'), ('paused', 'Pausado'), ('finished', 'Finalizado')], default='stopped', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pause_parent_on_start', models.BooleanField(default=False, help_text='Pausar o cronômetro pai quando este iniciar')),
                ('accumulated_time', models.DurationField(default=datetime.timedelta(0))),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='painelset.cronometro')),
            ],
            options={
                'verbose_name': 'Cronômetro',
                'verbose_name_plural': 'Cronômetros',
                'ordering': ['created_at'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='CronometroEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Iniciado'), ('paused', 'Pausado'), ('resumed', 'Retomado'), ('stopped', 'Parado'), ('finished', 'Finalizado'), ('reset', 'Resetado'), ('time_added', 'Tempo Adicionado')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cronometro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='painelset.cronometro')),
                ('triggered_by_child', models.ForeignKey(blank=True, help_text='Cronômetro filho que causou este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to='painelset.cronometro')),
            ],
            options={
                'verbose_name': 'Evento de Cronômetro',
                'verbose_name_plural': 'Eventos de Cronômetros',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('role', models.CharField(blank=True, choices=[('PARLAMENTAR', 'Parlamentar'), ('TRIBUNA', 'Tribuna'), ('INDIVIDUO', 'Indivíduo')], help_text='Função ou papel do indivíduo', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem do indivíduo no Evento')),
                ('canal', models.PositiveIntegerField(default=0, help_text='Canal do indivíduo no Evento')),
                ('ips_mesas', models.CharField(blank=True, default='', help_text='IPs das mesas associadas a este indivíduo, separados por vírgula', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_ip', message='IP inválido. Formato esperado: xxx.xxx.xxx.xxx (separados por espaço para múltiplos IPs).', regex='^(\\d{1,3}(\\.\\d{1,3}){3})*(\\s(\\d{1,3}(\\.\\d{1,3}){3}))*$')])),
                ('status_microfone', models.BooleanField(default=False, help_text='Indica se o microfone está ativo para este indivíduo')),
                ('microfone_sempre_ativo', models.BooleanField(default=False, help_text='Indica se o microfone deste indivíduo deve estar sempre ativo')),
                ('com_a_palavra', models.BooleanField(default=False, help_text='Indica se o indivíduo está com a palavra')),
                ('aparteante', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aparteado', to='painelset.individuo')),
                ('evento', models.ForeignKey(help_text='Evento ao qual este indivíduo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='individuos', to='painelset.evento', verbose_name='Evento')),
                ('parlamentar', models.ForeignKey(blank=True, help_text='Parlamentar associado ao indivíduo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuos', to='parlamentares.parlamentar', verbose_name='Parlamentar')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(models.Model, cmj.painelset.models.CronometroMixin),
        ),
        migrations.CreateModel(
            name='ParteEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField(help_text='Duração planejada da parte')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem da parte no Evento')),
                ('evento', models.ForeignKey(help_text='Evento ao qual esta parte pertence', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='painelset.evento')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
