# Generated by Django 5.2.12 on 2026-04-04 16:18

import cmj.painelset.models
import datetime
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import image_cropping.fields
import sapl.parlamentares.models
import sapl.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("parlamentares", "0001_initial"),
        ("sessao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Nome do Evento"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrição do Evento"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "start_previsto",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data e hora Prevista de Início",
                    ),
                ),
                (
                    "start_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e hora Real de Início"
                    ),
                ),
                (
                    "end_real",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data e hora Real de Término",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Duração total planejada do evento",
                        verbose_name="Duração do Evento",
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID do vídeo do YouTube associado ao evento (para exibição no painel)",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_youtube_id",
                                message="ID do YouTube inválido. Deve conter 11 caracteres alfanuméricos, hífens ou underscores.",
                                regex="^[a-zA-Z0-9_-]{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "ips_mesas",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IPs das mesas associadas a este indivíduo, separados por vírgula",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_ip",
                                message="IP inválido. Formato esperado: xxx.xxx.xxx.xxx (separados por espaço para múltiplos IPs).",
                                regex="^(\\d{1,3}(\\.\\d{1,3}){3})*(\\s(\\d{1,3}(\\.\\d{1,3}){3}))*$",
                            )
                        ],
                    ),
                ),
                (
                    "comunicar_com_mesas",
                    models.BooleanField(
                        default=False,
                        help_text="Comunicar com mesas via OSC?",
                        verbose_name="Comunicar com Mesas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, cmj.painelset.models.CronometroMixin),
        ),
        migrations.CreateModel(
            name="Cronometro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "duration",
                    models.DurationField(help_text="Duração planejada do cronômetro"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("stopped", "Parado"),
                            ("running", "Executando"),
                            ("paused", "Pausado"),
                            ("finished", "Finalizado"),
                        ],
                        default="stopped",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pause_parent_on_start",
                    models.BooleanField(
                        default=False,
                        help_text="Pausar o cronômetro pai quando este iniciar",
                    ),
                ),
                (
                    "accumulated_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="painelset.cronometro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronômetro",
                "verbose_name_plural": "Cronômetros",
                "ordering": ["created_at"],
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="CronometroEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Iniciado"),
                            ("paused", "Pausado"),
                            ("resumed", "Retomado"),
                            ("stopped", "Parado"),
                            ("finished", "Finalizado"),
                            ("reset", "Resetado"),
                            ("time_added", "Tempo Adicionado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                (
                    "cronometro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="painelset.cronometro",
                    ),
                ),
                (
                    "triggered_by_child",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cronômetro filho que causou este evento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_events",
                        to="painelset.cronometro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Cronômetro",
                "verbose_name_plural": "Eventos de Cronômetros",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Individuo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PARLAMENTAR", "Parlamentar"),
                            ("TRIBUNA", "Tribuna"),
                            ("INDIVIDUO", "Indivíduo"),
                        ],
                        help_text="Função ou papel do indivíduo",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem do indivíduo no Evento"
                    ),
                ),
                (
                    "canal",
                    models.PositiveIntegerField(
                        default=0, help_text="Canal do indivíduo no Evento"
                    ),
                ),
                (
                    "ips_mesas",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IPs das mesas associadas a este indivíduo, separados por vírgula",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_ip",
                                message="IP inválido. Formato esperado: xxx.xxx.xxx.xxx (separados por espaço para múltiplos IPs).",
                                regex="^(\\d{1,3}(\\.\\d{1,3}){3})*(\\s(\\d{1,3}(\\.\\d{1,3}){3}))*$",
                            )
                        ],
                    ),
                ),
                (
                    "status_microfone",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o microfone está ativo para este indivíduo",
                    ),
                ),
                (
                    "auto_corte_microfone",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o microfone foi cortado automaticamente",
                    ),
                ),
                (
                    "microfone_sempre_ativo",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o microfone deste indivíduo deve estar sempre ativo",
                    ),
                ),
                (
                    "tempo_de_corte_microfone",
                    models.DurationField(
                        default=datetime.timedelta(seconds=5),
                        help_text="Duração do corte de microfone após o tempo do cronômetro zerar",
                    ),
                ),
                (
                    "com_a_palavra",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o indivíduo está com a palavra",
                    ),
                ),
                (
                    "fotografia",
                    sapl.utils.PortalImageCropField(
                        blank=True,
                        null=True,
                        upload_to=sapl.parlamentares.models.foto_upload_path,
                        verbose_name="Fotografia",
                    ),
                ),
                (
                    "fotografia_cropping",
                    image_cropping.fields.ImageRatioField(
                        "fotografia",
                        "128x128",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text="A configuração do Avatar é possível após a atualização da fotografia.",
                        hide_image_field=False,
                        size_warning=True,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "aparteante",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aparteado",
                        to="painelset.individuo",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        help_text="Evento ao qual este indivíduo pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individuos",
                        to="painelset.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "parlamentar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parlamentar associado ao indivíduo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individuos",
                        to="parlamentares.parlamentar",
                        verbose_name="Parlamentar",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
            bases=(models.Model, cmj.painelset.models.CronometroMixin),
        ),
        migrations.CreateModel(
            name="Painel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nome único do painel", max_length=256),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descrição do painel"),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, help_text="Indica se este painel é o principal"
                    ),
                ),
                (
                    "auto_select_visoes",
                    models.BooleanField(
                        default=True,
                        help_text="Selecionar automaticamente visões com base no contexto do evento",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuração específica da visão neste painel em formato JSON",
                        null=True,
                        verbose_name="Configuração Específica",
                    ),
                ),
                (
                    "styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Estilos específicos da visão neste painel em formato JSON",
                        null=True,
                        verbose_name="Estilos Específicos",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Evento ao qual este painel pertence",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paineis",
                        to="painelset.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sessão ao qual este painel pertence",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paineis",
                        to="sessao.sessaoplenaria",
                        verbose_name="Sessão Plenária Associada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Painel",
                "verbose_name_plural": "Painéis",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VisaoDePainel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Nome da Visão no Painel Associado",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição da visão no Painel Associado"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Posição da visão no painel"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a visão está ativa no painel",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuração específica da visão neste painel em formato JSON",
                        null=True,
                        verbose_name="Configuração Específica",
                    ),
                ),
                (
                    "styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Estilos específicos da visão neste painel em formato JSON",
                        null=True,
                        verbose_name="Estilos Específicos",
                    ),
                ),
                (
                    "painel",
                    models.ForeignKey(
                        help_text="Painel associado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visoes",
                        to="painelset.painel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visão do Painel",
                "verbose_name_plural": "Visões dos Painéis",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do Widget na Visão Associada",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição do Widget na Visão Associada"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Posição do widget na visão"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o widget está visível na visão",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Configuração específica do widget nesta visão em formato JSON",
                        null=True,
                        verbose_name="Configuração Específica",
                    ),
                ),
                (
                    "styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Estilos específicos do widget nesta visão em formato JSON",
                        null=True,
                        verbose_name="Estilos Específicos",
                    ),
                ),
                (
                    "vue_component",
                    models.CharField(
                        blank=True,
                        help_text="Nome do componente Vue.js associado ao widget",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_component_name",
                                message="Nome do componente inválido. Deve começar com uma letra maiúscula e conter apenas letras, números e underscores.",
                                regex="^[A-Z][A-Za-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Widget pai para hierarquia",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="painelset.widget",
                    ),
                ),
                (
                    "visao",
                    models.ForeignKey(
                        help_text="Visão associada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="painelset.visaodepainel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget da Visão",
                "verbose_name_plural": "Widgets das Visões",
                "ordering": ["position", "id"],
            },
        ),
    ]
