# Generated by Django 5.2.3 on 2025-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Evento'),
        ),
    ]
