# Generated by Django 5.2.3 on 2025-10-09 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='tempo_de_corte_microfone',
            field=models.DurationField(default=datetime.timedelta(seconds=5), help_text='Duração do corte de microfone após o tempo do cronômetro zerar'),
        ),
    ]
