# Generated by Django 5.2.3 on 2025-10-11 22:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0002_individuo_tempo_de_corte_microfone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronometroevent',
            name='metadata',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Metadados'),
        ),
    ]
