# Generated by Django 5.2.3 on 2025-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0002_alter_evento_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem do indivíduo no Evento'),
        ),
        migrations.AlterField(
            model_name='parteevento',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem da parte no Evento'),
        ),
    ]
