# Generated by Django 5.2.3 on 2025-10-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0003_alter_individuo_order_alter_parteevento_order'),
        ('parlamentares', '0051_filiacao_autor_alter_filiacao_parlamentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='end_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora Real de Término'),
        ),
        migrations.AddField(
            model_name='evento',
            name='start_previsto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora Prevista de Início'),
        ),
        migrations.AddField(
            model_name='evento',
            name='start_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora Real de Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duration',
            field=models.DurationField(help_text='Duração total planejada do evento', verbose_name='Duração do Evento'),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='evento',
            field=models.ForeignKey(help_text='Evento ao qual este indivíduo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='individuos', to='painelset.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='parlamentar',
            field=models.ForeignKey(blank=True, help_text='Parlamentar associado ao indivíduo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuos', to='parlamentares.parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='role',
            field=models.CharField(blank=True, choices=[('PARLAMENTAR', 'Parlamentar'), ('TRIBUNA', 'Tribuna'), ('INDIVIDUO', 'Indivíduo')], help_text='Função ou papel do indivíduo', max_length=100),
        ),
    ]
