# Generated by Django 5.2.3 on 2025-10-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0003_cronometroevent_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParteEvento',
        ),
    ]
