# Generated by Django 5.2.3 on 2025-10-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0004_evento_end_real_evento_start_previsto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='sound_status',
            field=models.BooleanField(default=False, help_text='Indica se o som está ativo para este indivíduo'),
        ),
    ]
