# Generated by Django 5.2.3 on 2025-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0004_delete_parteevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nome do Evento'),
        ),
    ]
