# Generated by Django 5.2.3 on 2025-10-15 19:11

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0005_alter_evento_name'),
        ('sessao', '0072_alter_tiposessaoplenaria_tipogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único da visão', max_length=256, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição da visão')),
            ],
            options={
                'verbose_name': 'Visão',
                'verbose_name_plural': 'Visões',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único do painel', max_length=256, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do painel')),
                ('evento', models.ForeignKey(blank=True, help_text='Evento ao qual este painel pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='painels', to='painelset.evento', verbose_name='Evento')),
                ('sessao', models.ForeignKey(blank=True, help_text='Sessão ao qual este painel pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='painels', to='sessao.sessaoplenaria', verbose_name='Sessão Plenária Associada')),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Painéis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PainelVisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Posição da visão no painel')),
                ('active', models.BooleanField(default=True, help_text='Indica se a visão está ativa no painel')),
                ('config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Configuração específica da visão neste painel em formato JSON', null=True, verbose_name='Configuração Específica')),
                ('styles', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Estilos específicos da visão neste painel em formato JSON', null=True, verbose_name='Estilos Específicos')),
                ('painel', models.ForeignKey(help_text='Painel associado', on_delete=django.db.models.deletion.CASCADE, to='painelset.painel')),
                ('visao', models.ForeignKey(help_text='Visão associada', on_delete=django.db.models.deletion.CASCADE, to='painelset.visao')),
            ],
            options={
                'verbose_name': 'Visão do Painel',
                'verbose_name_plural': 'Visões dos Painéis',
                'ordering': ['position'],
                'unique_together': {('painel', 'visao')},
            },
        ),
        migrations.AddField(
            model_name='painel',
            name='visoes',
            field=models.ManyToManyField(blank=True, help_text='Visões associadas a este painel', related_name='painels', through='painelset.PainelVisao', through_fields=('painel', 'visao'), to='painelset.visao'),
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome único do widget', max_length=256, unique=True)),
                ('vue_component', models.CharField(help_text='Nome do componente Vue.js associado ao widget', max_length=256, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_component_name', message='Nome do componente inválido. Deve começar com uma letra minúscula e conter apenas letras, números e underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('styles', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Configuração de estilos do widget em formato JSON', null=True, verbose_name='Estilos')),
                ('config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Configuração específica do widget em formato JSON', null=True, verbose_name='Configuração')),
                ('parent', models.ForeignKey(blank=True, help_text='Widget pai para hierarquia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='painelset.widget')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisaoWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Posição do widget na visão')),
                ('visible', models.BooleanField(default=True, help_text='Indica se o widget está visível na visão')),
                ('config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Configuração específica do widget nesta visão em formato JSON', null=True, verbose_name='Configuração Específica')),
                ('styles', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Estilos específicos do widget nesta visão em formato JSON', null=True, verbose_name='Estilos Específicos')),
                ('visao', models.ForeignKey(help_text='Visão associada', on_delete=django.db.models.deletion.CASCADE, to='painelset.visao')),
                ('widget', models.ForeignKey(help_text='Widget associado', on_delete=django.db.models.deletion.CASCADE, to='painelset.widget')),
            ],
            options={
                'verbose_name': 'Widget da Visão',
                'verbose_name_plural': 'Widgets das Visões',
                'ordering': ['position'],
                'unique_together': {('widget', 'visao')},
            },
        ),
        migrations.AddField(
            model_name='visao',
            name='widgets',
            field=models.ManyToManyField(blank=True, help_text='Widgets associados a esta visão', related_name='visoes', through='painelset.VisaoWidget', through_fields=('visao', 'widget'), to='painelset.widget'),
        ),
    ]
