# Generated by Django 5.2.3 on 2025-10-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0005_individuo_sound_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='com_a_palavra',
            field=models.BooleanField(default=False, help_text='Indica se o indivíduo está com a palavra'),
        ),
    ]
