# Generated by Django 5.2.3 on 2025-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0006_individuo_com_a_palavra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuo',
            name='sound_status',
        ),
        migrations.AddField(
            model_name='individuo',
            name='microfone_sempre_ativo',
            field=models.BooleanField(default=False, help_text='Indica se o microfone deste indivíduo deve estar sempre ativo'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='status_microfone',
            field=models.BooleanField(default=False, help_text='Indica se o microfone está ativo para este indivíduo'),
        ),
    ]
