# Generated by Django 5.2.3 on 2025-10-17 19:04

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0006_visao_painel_painelvisao_painel_visoes_widget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel',
            name='config',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Configuração específica da visão neste painel em formato JSON', null=True, verbose_name='Configuração Específica'),
        ),
        migrations.AddField(
            model_name='painel',
            name='styles',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Estilos específicos da visão neste painel em formato JSON', null=True, verbose_name='Estilos Específicos'),
        ),
        migrations.AlterField(
            model_name='painelvisao',
            name='painel',
            field=models.ForeignKey(help_text='Painel associado', on_delete=django.db.models.deletion.CASCADE, related_name='painelvisao_set', to='painelset.painel'),
        ),
        migrations.AlterField(
            model_name='painelvisao',
            name='visao',
            field=models.ForeignKey(help_text='Visão associada', on_delete=django.db.models.deletion.CASCADE, related_name='painelvisao_set', to='painelset.visao'),
        ),
    ]
