# Generated by Django 5.2.3 on 2025-10-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0007_remove_individuo_sound_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='aparteante',
            field=models.ForeignKey(blank=True, help_text='Indivíduo que fez o aparte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aparteados', to='painelset.individuo', verbose_name='Aparteante'),
        ),
        migrations.AlterField(
            model_name='cronometroevent',
            name='event_type',
            field=models.CharField(choices=[('started', 'Iniciado'), ('paused', 'Pausado'), ('resumed', 'Retomado'), ('stopped', 'Parado'), ('finished', 'Finalizado'), ('reset', 'Resetado'), ('time_added', 'Tempo Adicionado')], max_length=20),
        ),
    ]
