# Generated by Django 5.2.3 on 2025-10-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0007_painel_config_painel_styles_painelvisao_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painel',
            name='visoes',
        ),
        migrations.DeleteModel(
            name='PainelVisao',
        ),
    ]
