# Generated by Django 5.2.3 on 2025-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0007_painel_config_painel_styles_alter_painelvisao_painel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelvisao',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da visão no Painel Associado'),
        ),
        migrations.AddField(
            model_name='painelvisao',
            name='name',
            field=models.CharField(blank=True, help_text='Nome da Visão no Painel Associado', max_length=256),
        ),
    ]
