# Generated by Django 5.2.3 on 2025-10-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0008_remove_painel_visoes_delete_painelvisao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visao',
            name='widgets',
        ),
        migrations.DeleteModel(
            name='VisaoWidget',
        ),
    ]
