# Generated by Django 5.2.3 on 2025-10-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0008_individuo_aparteante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Nome do Evento'),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='aparteante',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aparteado', to='painelset.individuo'),
        ),
    ]
