# Generated by Django 5.2.3 on 2025-10-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0008_painelvisao_description_painelvisao_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaowidget',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do Widget na Visão Associada'),
        ),
        migrations.AddField(
            model_name='visaowidget',
            name='name',
            field=models.CharField(blank=True, help_text='Nome do Widget na Visão Associada', max_length=256),
        ),
    ]
