# Generated by Django 5.2.3 on 2025-10-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0009_remove_visao_widgets_delete_visaowidget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visao',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
