# Generated by Django 5.2.3 on 2025-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0009_alter_evento_name_alter_individuo_aparteante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronometro',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='individuo',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
