# Generated by Django 5.2.3 on 2025-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0010_alter_cronometro_name_alter_individuo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='canal',
            field=models.PositiveIntegerField(default=0, help_text='Canal do indivíduo no Evento'),
        ),
    ]
