# Generated by Django 5.2.3 on 2025-10-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0010_delete_visao_delete_widget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Painel',
        ),
    ]
