# Generated by Django 5.2.3 on 2025-10-08 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0011_individuo_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ips_mesas',
            field=models.CharField(blank=True, default='', help_text='IPs das mesas associadas a este indivíduo, separados por vírgula', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_ip', message='IP inválido. Formato esperado: xxx.xxx.xxx.xxx (separados por espaço para múltiplos IPs).', regex='^(\\d{1,3}(\\.\\d{1,3}){3})*(\\s(\\d{1,3}(\\.\\d{1,3}){3}))*$')]),
        ),
        migrations.AddField(
            model_name='individuo',
            name='ips_mesas',
            field=models.CharField(blank=True, default='', help_text='IPs das mesas associadas a este indivíduo, separados por vírgula', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_ip', message='IP inválido. Formato esperado: xxx.xxx.xxx.xxx (separados por espaço para múltiplos IPs).', regex='^(\\d{1,3}(\\.\\d{1,3}){3})*(\\s(\\d{1,3}(\\.\\d{1,3}){3}))*$')]),
        ),
    ]
