# Generated by Django 5.2.3 on 2025-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0012_evento_ips_mesas_individuo_ips_mesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='comunicar_com_mesas',
            field=models.BooleanField(default=False, help_text='Comunicar com mesas via OSC?', verbose_name='Comunicar com Mesas'),
        ),
    ]
