# Generated by Django 5.2.3 on 2025-10-20 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0012_painel_visaodepainel_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='vue_component',
            field=models.CharField(blank=True, help_text='Nome do componente Vue.js associado ao widget', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_component_name', message='Nome do componente inválido. Deve começar com uma letra minúscula e conter apenas letras, números e underscores.', regex='^[a-z][a-z0-9_]*$')]),
        ),
    ]
