# Generated by Django 5.2.3 on 2025-10-21 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0013_alter_widget_vue_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='vue_component',
            field=models.CharField(blank=True, help_text='Nome do componente Vue.js associado ao widget', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_component_name', message='Nome do componente inválido. Deve começar com uma letra maiúscula e conter apenas letras, números e underscores.', regex='^[A-Z][A-Za-z0-9_]*$')]),
        ),
    ]
