# Generated by Django 5.2.3 on 2025-10-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0014_alter_widget_vue_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaodepainel',
            name='painel',
            field=models.ForeignKey(help_text='Painel associado', on_delete=django.db.models.deletion.CASCADE, related_name='visoes', to='painelset.painel'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='visao',
            field=models.ForeignKey(help_text='Visão associada', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='painelset.visaodepainel'),
        ),
    ]
