# Generated by Django 5.2.3 on 2025-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0015_alter_visaodepainel_painel_alter_widget_visao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='name',
            field=models.CharField(help_text='Nome único do painel', max_length=256),
        ),
    ]
