# Generated by Django 5.2.3 on 2025-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0016_alter_painel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='auto_corte_microfone',
            field=models.BooleanField(default=False, help_text='Indica se o microfone foi cortado automaticamente'),
        ),
    ]
