# Generated by Django 5.2.3 on 2025-10-25 00:09

import image_cropping.fields
import sapl.parlamentares.models
import sapl.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0017_individuo_auto_corte_microfone'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='fotografia',
            field=sapl.utils.PortalImageCropField(blank=True, null=True, upload_to=sapl.parlamentares.models.foto_upload_path, verbose_name='Fotografia'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='fotografia_cropping',
            field=image_cropping.fields.ImageRatioField('fotografia', '128x128', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='A configuração do Avatar é possível após a atualização da fotografia.', hide_image_field=False, size_warning=True, verbose_name='Avatar'),
        ),
    ]
