# Generated by Django 5.2.3 on 2025-10-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0018_individuo_fotografia_individuo_fotografia_cropping'),
        ('sessao', '0072_alter_tiposessaoplenaria_tipogeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Evento ao qual este painel pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to='painelset.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='painel',
            name='sessao',
            field=models.ForeignKey(blank=True, help_text='Sessão ao qual este painel pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paineis', to='sessao.sessaoplenaria', verbose_name='Sessão Plenária Associada'),
        ),
    ]
