# Generated by Django 5.2.3 on 2025-10-31 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0019_alter_painel_evento_alter_painel_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='youtube_id',
            field=models.CharField(blank=True, default='', help_text='ID do vídeo do YouTube associado ao evento (para exibição no painel)', max_length=256, validators=[django.core.validators.RegexValidator(code='invalid_youtube_id', message='ID do YouTube inválido. Deve conter 11 caracteres alfanuméricos, hífens ou underscores.', regex='^[a-zA-Z0-9_-]{11}$')]),
        ),
    ]
