# Generated by Django 5.2.3 on 2025-11-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0020_evento_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaodepainel',
            name='active',
            field=models.BooleanField(default=False, help_text='Indica se a visão está ativa no painel'),
        ),
    ]
