# Generated by Django 5.2.3 on 2025-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0021_alter_visaodepainel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel',
            name='auto_select_visoes',
            field=models.BooleanField(default=True, help_text='Selecionar automaticamente visões com base no contexto do evento'),
        ),
        migrations.AddField(
            model_name='painel',
            name='principal',
            field=models.BooleanField(default=False, help_text='Indica se este painel é o principal'),
        ),
    ]
