# Generated by Django 5.2.3 on 2025-11-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0022_painel_auto_select_visoes_painel_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visaodepainel',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Visão do Painel', 'verbose_name_plural': 'Visões dos Painéis'},
        ),
    ]
