# Generated by Django 5.2.8 on 2025-11-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painelset', '0023_alter_visaodepainel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Widget da Visão', 'verbose_name_plural': 'Widgets das Visões'},
        ),
    ]
