export const STATE_UPDATE = 'STATE_UPDATE'
export const STATE_DELETE = 'STATE_DELETE'
export const SET_NIVEL_DETALHE = 'SET_NIVEL_DETALHE'
export const SET_NIVEL_DETALHE_VISIVEL = 'SET_NIVEL_DETALHE_VISIVEL'
