# Generated by Django 5.2.12 on 2026-04-04 16:18

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import sapl.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_initial"),
        ("materia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anexado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_anexacao", models.DateField(verbose_name="Data Anexação")),
                (
                    "data_desanexacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Desanexação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexado",
                "verbose_name_plural": "Anexados",
                "ordering": ("-data_anexacao", "id"),
            },
        ),
        migrations.CreateModel(
            name="DocumentoAdministrativo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "ano",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2027, 2027),
                            (2026, 2026),
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                            (1959, 1959),
                            (1958, 1958),
                            (1957, 1957),
                            (1956, 1956),
                            (1955, 1955),
                            (1954, 1954),
                            (1953, 1953),
                            (1952, 1952),
                            (1951, 1951),
                            (1950, 1950),
                            (1949, 1949),
                            (1948, 1948),
                            (1947, 1947),
                            (1946, 1946),
                            (1945, 1945),
                            (1944, 1944),
                            (1943, 1943),
                            (1942, 1942),
                            (1941, 1941),
                            (1940, 1940),
                            (1939, 1939),
                            (1938, 1938),
                            (1937, 1937),
                            (1936, 1936),
                            (1935, 1935),
                            (1934, 1934),
                            (1933, 1933),
                            (1932, 1932),
                            (1931, 1931),
                            (1930, 1930),
                            (1929, 1929),
                            (1928, 1928),
                            (1927, 1927),
                            (1926, 1926),
                            (1925, 1925),
                            (1924, 1924),
                            (1923, 1923),
                            (1922, 1922),
                            (1921, 1921),
                            (1920, 1920),
                            (1919, 1919),
                            (1918, 1918),
                            (1917, 1917),
                            (1916, 1916),
                            (1915, 1915),
                            (1914, 1914),
                            (1913, 1913),
                            (1912, 1912),
                            (1911, 1911),
                            (1910, 1910),
                            (1909, 1909),
                            (1908, 1908),
                            (1907, 1907),
                            (1906, 1906),
                            (1905, 1905),
                            (1904, 1904),
                            (1903, 1903),
                            (1902, 1902),
                            (1901, 1901),
                            (1900, 1900),
                            (1899, 1899),
                            (1898, 1898),
                            (1897, 1897),
                            (1896, 1896),
                            (1895, 1895),
                            (1894, 1894),
                            (1893, 1893),
                            (1892, 1892),
                            (1891, 1891),
                            (1890, 1890),
                        ],
                        verbose_name="Ano",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "temp_migracao_doc_acessorio",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Field temporário para migração dos docs acessórios da procuradoria",
                    ),
                ),
                (
                    "temp_migracao_sislegis",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Field temporário para migração dos docs adms do sislegis",
                    ),
                ),
                (
                    "old_path",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Path antigo para Sislegis - Publicações",
                    ),
                ),
                (
                    "old_json",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Json from origin import",
                    ),
                ),
                (
                    "epigrafe",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Epigrafe / Título"
                    ),
                ),
                (
                    "interessado",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Interessado"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "dias_prazo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dias Prazo"
                    ),
                ),
                (
                    "data_fim_prazo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim Prazo"
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Efetivo/Estimado",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "tramitacao",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Em Tramitação?",
                    ),
                ),
                (
                    "assunto",
                    models.TextField(blank=True, default="", verbose_name="Assunto"),
                ),
                (
                    "numero_externo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número Externo"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True, default="", verbose_name="Outras Informações"
                    ),
                ),
                (
                    "texto_integral",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.utils.texto_upload_path,
                        verbose_name="Texto Integral",
                    ),
                ),
                (
                    "visibilidade",
                    models.PositiveIntegerField(
                        choices=[(0, "Privado"), (49, "Restrito"), (99, "Público")],
                        default=0,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "link_share",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Link de Compartilhamento",
                    ),
                ),
                (
                    "data_ultima_atualizacao",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Data"),
                ),
                (
                    "anexados",
                    models.ManyToManyField(
                        blank=True,
                        related_name="anexo_de",
                        through="protocoloadm.Anexado",
                        through_fields=("documento_principal", "documento_anexado"),
                        to="protocoloadm.documentoadministrativo",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.autor",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentoadministrativo_set",
                        to="materia.materialegislativa",
                        verbose_name="Matéria Vinculada",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentoadministrativo_set",
                        to="core.areatrabalho",
                        verbose_name="Área de Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Administrativo",
                "verbose_name_plural": "Documentos Administrativos",
                "ordering": ("-ano", "-id"),
                "permissions": (
                    ("link_share_create_documentoadministrativo", "Gerar Link Público"),
                ),
            },
        ),
        migrations.AddField(
            model_name="anexado",
            name="documento_anexado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documento_anexado_set",
                to="protocoloadm.documentoadministrativo",
                verbose_name="Documento Anexado",
            ),
        ),
        migrations.AddField(
            model_name="anexado",
            name="documento_principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documento_principal_set",
                to="protocoloadm.documentoadministrativo",
                verbose_name="Documento Principal",
            ),
        ),
        migrations.CreateModel(
            name="AcompanhamentoDocumento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                ("data_cadastro", models.DateField(auto_now_add=True)),
                ("hash", models.CharField(max_length=8)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocoloadm.documentoadministrativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acompanhamento de Documento",
                "verbose_name_plural": "Acompanhamentos de Documento",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Protocolo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número de Protocolo"),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2027, 2027),
                            (2026, 2026),
                            (2025, 2025),
                            (2024, 2024),
                            (2023, 2023),
                            (2022, 2022),
                            (2021, 2021),
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                            (2008, 2008),
                            (2007, 2007),
                            (2006, 2006),
                            (2005, 2005),
                            (2004, 2004),
                            (2003, 2003),
                            (2002, 2002),
                            (2001, 2001),
                            (2000, 2000),
                            (1999, 1999),
                            (1998, 1998),
                            (1997, 1997),
                            (1996, 1996),
                            (1995, 1995),
                            (1994, 1994),
                            (1993, 1993),
                            (1992, 1992),
                            (1991, 1991),
                            (1990, 1990),
                            (1989, 1989),
                            (1988, 1988),
                            (1987, 1987),
                            (1986, 1986),
                            (1985, 1985),
                            (1984, 1984),
                            (1983, 1983),
                            (1982, 1982),
                            (1981, 1981),
                            (1980, 1980),
                            (1979, 1979),
                            (1978, 1978),
                            (1977, 1977),
                            (1976, 1976),
                            (1975, 1975),
                            (1974, 1974),
                            (1973, 1973),
                            (1972, 1972),
                            (1971, 1971),
                            (1970, 1970),
                            (1969, 1969),
                            (1968, 1968),
                            (1967, 1967),
                            (1966, 1966),
                            (1965, 1965),
                            (1964, 1964),
                            (1963, 1963),
                            (1962, 1962),
                            (1961, 1961),
                            (1960, 1960),
                            (1959, 1959),
                            (1958, 1958),
                            (1957, 1957),
                            (1956, 1956),
                            (1955, 1955),
                            (1954, 1954),
                            (1953, 1953),
                            (1952, 1952),
                            (1951, 1951),
                            (1950, 1950),
                            (1949, 1949),
                            (1948, 1948),
                            (1947, 1947),
                            (1946, 1946),
                            (1945, 1945),
                            (1944, 1944),
                            (1943, 1943),
                            (1942, 1942),
                            (1941, 1941),
                            (1940, 1940),
                            (1939, 1939),
                            (1938, 1938),
                            (1937, 1937),
                            (1936, 1936),
                            (1935, 1935),
                            (1934, 1934),
                            (1933, 1933),
                            (1932, 1932),
                            (1931, 1931),
                            (1930, 1930),
                            (1929, 1929),
                            (1928, 1928),
                            (1927, 1927),
                            (1926, 1926),
                            (1925, 1925),
                            (1924, 1924),
                            (1923, 1923),
                            (1922, 1922),
                            (1921, 1921),
                            (1920, 1920),
                            (1919, 1919),
                            (1918, 1918),
                            (1917, 1917),
                            (1916, 1916),
                            (1915, 1915),
                            (1914, 1914),
                            (1913, 1913),
                            (1912, 1912),
                            (1911, 1911),
                            (1910, 1910),
                            (1909, 1909),
                            (1908, 1908),
                            (1907, 1907),
                            (1906, 1906),
                            (1905, 1905),
                            (1904, 1904),
                            (1903, 1903),
                            (1902, 1902),
                            (1901, 1901),
                            (1900, 1900),
                            (1899, 1899),
                            (1898, 1898),
                            (1897, 1897),
                            (1896, 1896),
                            (1895, 1895),
                            (1894, 1894),
                            (1893, 1893),
                            (1892, 1892),
                            (1891, 1891),
                            (1890, 1890),
                        ],
                        verbose_name="Ano do Protocolo",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        help_text="Informado manualmente",
                        null=True,
                        verbose_name="Data do Protocolo",
                    ),
                ),
                (
                    "hora",
                    models.TimeField(
                        blank=True,
                        help_text="Informado manualmente",
                        null=True,
                        verbose_name="Hora do Protocolo",
                    ),
                ),
                (
                    "timestamp_data_hora_manual",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user_data_hora_manual",
                    models.CharField(
                        blank=True,
                        help_text="Usuário que está realizando Protocolo e informando data e hora manualmente.",
                        max_length=256,
                        verbose_name="IP",
                    ),
                ),
                (
                    "ip_data_hora_manual",
                    models.CharField(
                        blank=True,
                        help_text="Endereço IP da estação de trabalho do usuário que está realizando Protocolo e informando data e hora manualmente.",
                        max_length=256,
                        verbose_name="IP",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "tipo_protocolo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tipo de Protocolo"
                    ),
                ),
                (
                    "interessado",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Interessado"
                    ),
                ),
                ("tipo_processo", models.PositiveIntegerField()),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email do Interessado"
                    ),
                ),
                (
                    "comprovante_automatico_enviado",
                    models.BooleanField(
                        default=False, verbose_name="Comprovante Automático Enviado"
                    ),
                ),
                ("assunto_ementa", models.TextField(blank=True)),
                (
                    "tipo_object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "conteudo_object_id",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "numero_paginas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de Páginas"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("anulado", models.BooleanField(default=False)),
                ("user_anulacao", models.CharField(blank=True, max_length=1000)),
                ("ip_anulacao", models.CharField(blank=True, max_length=15)),
                (
                    "justificativa_anulacao",
                    models.CharField(blank=True, max_length=260, verbose_name="Motivo"),
                ),
                ("timestamp_anulacao", models.DateTimeField(blank=True, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="base.autor",
                    ),
                ),
                (
                    "conteudo_content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conteudo_content_type_set",
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Material Gerado",
                    ),
                ),
                (
                    "tipo_content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipo_content_type_set",
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Material Gerado",
                    ),
                ),
                (
                    "tipo_materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materia.tipomaterialegislativa",
                        verbose_name="Tipo de Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocolo",
                "verbose_name_plural": "Protocolos",
                "ordering": ["id"],
                "permissions": (
                    ("action_anular_protocolo", "Permissão para Anular Protocolo"),
                    (
                        "action_homologar_protocolo",
                        "Permissão para Homologar Protocolo",
                    ),
                ),
            },
        ),
        migrations.AddField(
            model_name="documentoadministrativo",
            name="protocolo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="protocoloadm.protocolo",
                verbose_name="Protocolo",
            ),
        ),
        migrations.CreateModel(
            name="StatusTramitacaoAdministrativo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=10, verbose_name="Sigla")),
                (
                    "descricao",
                    models.CharField(max_length=60, verbose_name="Descrição"),
                ),
                (
                    "descricao_plural",
                    models.CharField(
                        default="", max_length=60, verbose_name="Descrição no plural"
                    ),
                ),
                (
                    "indicador",
                    models.CharField(
                        choices=[("F", "Fim"), ("R", "Retorno")],
                        max_length=1,
                        verbose_name="Indicador da Tramitação",
                    ),
                ),
                (
                    "filtro",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=True,
                        verbose_name="Filtro ?",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statustramitacaoadministrativo_set",
                        to="core.areatrabalho",
                        verbose_name="Área de Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status de Tramitação de Documentos Administrativos",
                "verbose_name_plural": "Status de Tramitação de Documentos Administrativos",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoAdministrativo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=5, verbose_name="Sigla")),
                (
                    "descricao",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "prioridade",
                    models.BooleanField(default=False, verbose_name="Prioridade"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipodocumentoadministrativo_set",
                        to="core.areatrabalho",
                        verbose_name="Área de Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento Administrativo",
                "verbose_name_plural": "Tipos de Documento Administrativo",
                "ordering": ["descricao"],
            },
        ),
        migrations.AddField(
            model_name="protocolo",
            name="tipo_documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="protocoloadm.tipodocumentoadministrativo",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="documentoadministrativo",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="protocoloadm.tipodocumentoadministrativo",
                verbose_name="Tipo Documento",
            ),
        ),
        migrations.CreateModel(
            name="DocumentoAcessorioAdministrativo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_paginas",
                    models.IntegerField(default=0, verbose_name="Número de Páginas"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Metadados",
                    ),
                ),
                ("nome", models.CharField(max_length=30, verbose_name="Nome")),
                (
                    "arquivo",
                    sapl.utils.PortalFileField(
                        blank=True,
                        max_length=512,
                        null=True,
                        storage=sapl.utils.OverwriteStorage(),
                        upload_to=sapl.utils.texto_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "autor",
                    models.CharField(blank=True, max_length=50, verbose_name="Autor"),
                ),
                ("assunto", models.TextField(blank=True, verbose_name="Assunto")),
                ("indexacao", models.TextField(blank=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="protocoloadm.documentoadministrativo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="protocoloadm.tipodocumentoadministrativo",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Acessório",
                "verbose_name_plural": "Documentos Acessórios",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TramitacaoAdministrativo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("data_tramitacao", models.DateField(verbose_name="Data Tramitação")),
                (
                    "data_encaminhamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Encaminhamento"
                    ),
                ),
                (
                    "urgente",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        default=False,
                        verbose_name="Urgente ?",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto da Ação")),
                (
                    "data_fim_prazo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim do Prazo"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="IP"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="protocoloadm.documentoadministrativo",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="protocoloadm.statustramitacaoadministrativo",
                        verbose_name="Status",
                    ),
                ),
                (
                    "unidade_tramitacao_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm_tramitacoes_destino",
                        to="materia.unidadetramitacao",
                        verbose_name="Unidade Destino",
                    ),
                ),
                (
                    "unidade_tramitacao_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adm_tramitacoes_origem",
                        to="materia.unidadetramitacao",
                        verbose_name="Unidade Local",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tramitação de Documento Administrativo",
                "verbose_name_plural": "Tramitações de Documento Administrativo",
                "ordering": ("-data_tramitacao", "-id"),
            },
        ),
        migrations.CreateModel(
            name="VinculoDocAdminMateria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_anexacao", models.DateField(verbose_name="Data Anexação")),
                (
                    "data_desanexacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Desanexação"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculodocadminmateria_set",
                        to="protocoloadm.documentoadministrativo",
                        verbose_name="Documento Administrativo",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculodocadminmateria_set",
                        to="materia.materialegislativa",
                        verbose_name="Matéria Legislativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculo entre Documento Administrativo e Matéria Legislativa",
                "verbose_name_plural": "Vinculos entre Documento Administrativo e Matéria Legislativa",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="documentoadministrativo",
            name="materiasvinculadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="docadmvinculados",
                through="protocoloadm.VinculoDocAdminMateria",
                through_fields=("documento", "materia"),
                to="materia.materialegislativa",
            ),
        ),
        migrations.AddIndex(
            model_name="protocolo",
            index=models.Index(
                fields=["conteudo_content_type", "conteudo_object_id"],
                name="protocoload_conteud_ea2fa4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vinculodocadminmateria",
            unique_together={("documento", "materia")},
        ),
    ]
