# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0027_auto_20190916_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='temp_migracao_doc_acessorio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Field temporário para migração dos docs acessórios da procuradoria'),
        ),
    ]
