# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0029_auto_20190916_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentoadministrativo_set', to='materia.MateriaLegislativa', verbose_name='Matéria Vinculada'),
        ),
    ]
