# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0030_auto_20190917_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='temp_migracao_sislegis',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Field temporário para migração dos docs adms do sislegis'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Resumo'),
        ),
    ]
