# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 12:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0031_auto_20190917_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='old_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Json pra Sislegis - Publicações'),
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='old_path',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Path para Sislegis - Publicações'),
        ),
    ]
