# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0033_statustramitacaoadministrativo_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustramitacaoadministrativo',
            options={'verbose_name': 'Status de Tramitação de Documentos Administrativos', 'verbose_name_plural': 'Status de Tramitação de Documentos Administrativos'},
        ),
    ]
