# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-19 01:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0034_auto_20190918_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='old_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Json from origin import'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='old_path',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Path antigo para Sislegis - Publicações'),
        ),
    ]
