# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0035_auto_20190918_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='user_anulacao',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
