# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0038_auto_20190919_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexado',
            options={'ordering': ('-data_anexacao', '-documento_anexado___certidao__created'), 'verbose_name': 'Anexado', 'verbose_name_plural': 'Anexados'},
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim Prazo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='assunto',
            field=models.TextField(blank=True, null=True, verbose_name='Assunto'),
        ),
    ]
