# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0039_auto_20190922_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumentoadministrativo',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
