# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 13:37
from __future__ import unicode_literals

from django.db import migrations
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0042_auto_20200128_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorioadministrativo',
            name='arquivo',
            field=sapl.utils.PortalFileField(blank=True, max_length=512, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='texto_integral',
            field=sapl.utils.PortalFileField(blank=True, max_length=512, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Texto Integral'),
        ),
    ]
