# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0043_auto_20200129_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorioadministrativo',
            name='_paginas',
            field=models.IntegerField(default=0, verbose_name='Número de Páginas'),
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='_paginas',
            field=models.IntegerField(default=0, verbose_name='Número de Páginas'),
        ),
    ]
