# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0046_documentoadministrativo_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoadministrativo',
            options={'ordering': ('-ano', '-id'), 'verbose_name': 'Documento Administrativo', 'verbose_name_plural': 'Documentos Administrativos'},
        ),
    ]
