# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('protocoloadm', '0047_auto_20200409_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='conteudo_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='conteudo_content_type_set', to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='conteudo_object_id',
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tipo_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='tipo_content_type_set', to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tipo_object_id',
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True),
        ),
    ]
