# Generated by Django 2.2.12 on 2020-05-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0049_documentoacessorioadministrativo_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='conteudo_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteudo_content_type_set', to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='tipo_content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_content_type_set', to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
    ]
