# Generated by Django 2.2.12 on 2020-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0050_auto_20200520_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='comprovante_automatico_enviado',
            field=models.BooleanField(default=False, verbose_name='Comprovante Automático Enviado'),
        ),
    ]
