# Generated by Django 2.2.12 on 2020-06-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0051_protocolo_comprovante_automatico_enviado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolo',
            options={'permissions': (('action_anular_protocolo', 'Permissão para Anular Protocolo'), ('action_homologar_protocolo', 'Permissão para Homologar Protocolo')), 'verbose_name': 'Protocolo', 'verbose_name_plural': 'Protocolos'},
        ),
    ]
