# Generated by Django 2.2.15 on 2020-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0052_auto_20200609_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
