# Generated by Django 2.2.16 on 2020-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0053_documentoadministrativo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='link_share',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Link de Compartilhamento'),
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='visibilidade',
            field=models.PositiveIntegerField(choices=[(0, 'Privado'), (49, 'Restrito'), (99, 'Público')], default=0, verbose_name='Visibilidade'),
        ),
    ]
