# Generated by Django 2.2.16 on 2020-11-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0054_auto_20201106_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoadministrativo',
            options={'ordering': ('-ano', '-id'), 'permissions': (('link_share_create_documentoadministrativo', 'Gerar Link Público'),), 'verbose_name': 'Documento Administrativo', 'verbose_name_plural': 'Documentos Administrativos'},
        ),
    ]
