# Generated by Django 2.2.24 on 2021-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0056_auto_20210302_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustramitacaoadministrativo',
            name='descricao_plural',
            field=models.CharField(default='', max_length=60, verbose_name='Descrição no plural'),
        ),
    ]
