# Generated by Django 2.2.24 on 2021-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0057_statustramitacaoadministrativo_descricao_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustramitacaoadministrativo',
            name='filtro',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Filtro ?'),
        ),
    ]
