# Generated by Django 2.2.24 on 2021-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0058_statustramitacaoadministrativo_filtro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentoadministrativo',
            name='prioridade',
            field=models.BooleanField(default=False, verbose_name='Prioridade'),
        ),
    ]
