# Generated by Django 2.2.28 on 2023-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0061_auto_20230205_1438'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='protocolo',
            index=models.Index(fields=['conteudo_content_type', 'conteudo_object_id'], name='protocoload_conteud_ea2fa4_idx'),
        ),
    ]
