# Generated by Django 2.2.28 on 2024-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0063_auto_20240103_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamentodocumento',
            options={'ordering': ['id'], 'verbose_name': 'Acompanhamento de Documento', 'verbose_name_plural': 'Acompanhamentos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='documentoacessorioadministrativo',
            options={'ordering': ['id'], 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='protocolo',
            options={'ordering': ['id'], 'permissions': (('action_anular_protocolo', 'Permissão para Anular Protocolo'), ('action_homologar_protocolo', 'Permissão para Homologar Protocolo')), 'verbose_name': 'Protocolo', 'verbose_name_plural': 'Protocolos'},
        ),
        migrations.AlterModelOptions(
            name='statustramitacaoadministrativo',
            options={'ordering': ['id'], 'verbose_name': 'Status de Tramitação de Documentos Administrativos', 'verbose_name_plural': 'Status de Tramitação de Documentos Administrativos'},
        ),
    ]
