# Generated by Django 4.2.16 on 2024-10-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0066_alter_documentoacessorioadministrativo_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Outras Informações'),
        ),
    ]
