# Generated by Django 5.2.1 on 2025-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0100_alter_materialegislativa_anexadas_and_more'),
        ('protocoloadm', '0068_alter_documentoadministrativo_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='anexados',
            field=models.ManyToManyField(blank=True, related_name='anexo_de', through='protocoloadm.Anexado', through_fields=('documento_principal', 'documento_anexado'), to='protocoloadm.documentoadministrativo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='materiasvinculadas',
            field=models.ManyToManyField(blank=True, related_name='docadmvinculados', through='protocoloadm.VinculoDocAdminMateria', through_fields=('documento', 'materia'), to='materia.materialegislativa'),
        ),
    ]
