# Generated by Django 5.2.1 on 2025-05-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0069_alter_documentoadministrativo_anexados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexado',
            options={'ordering': ('-data_anexacao', 'id'), 'verbose_name': 'Anexado', 'verbose_name_plural': 'Anexados'},
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado'),
        ),
    ]
