# Generated by Django 5.2.11 on 2026-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocoloadm", "0072_alter_documentoadministrativo_ano_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoadministrativo",
            name="old_path",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Path antigo para Sislegis - Publicações",
            ),
        ),
    ]
