# Generated by Django 5.2.11 on 2026-03-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocoloadm", "0073_alter_documentoadministrativo_old_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoadministrativo",
            name="assunto",
            field=models.TextField(blank=True, default="", verbose_name="Assunto"),
        ),
    ]
