# Generated by Django 5.2.11 on 2026-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocoloadm", "0074_alter_documentoadministrativo_assunto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoadministrativo",
            name="link_share",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Link de Compartilhamento",
            ),
        ),
        migrations.AlterField(
            model_name="documentoadministrativo",
            name="observacao",
            field=models.TextField(
                blank=True, default="", verbose_name="Outras Informações"
            ),
        ),
    ]
